// Code generated by ent, DO NOT EDIT.

package groupbuyplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the groupbuyplan type in the database.
	Label = "group_buy_plan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldProductKey holds the string denoting the product_key field in the database.
	FieldProductKey = "product_key"
	// FieldTotalShares holds the string denoting the total_shares field in the database.
	FieldTotalShares = "total_shares"
	// FieldSeatCount holds the string denoting the seat_count field in the database.
	FieldSeatCount = "seat_count"
	// FieldPricePerShare holds the string denoting the price_per_share field in the database.
	FieldPricePerShare = "price_per_share"
	// FieldPricePerSeat holds the string denoting the price_per_seat field in the database.
	FieldPricePerSeat = "price_per_seat"
	// FieldPriceLabel holds the string denoting the price_label field in the database.
	FieldPriceLabel = "price_label"
	// FieldQuotaPerShareLabel holds the string denoting the quota_per_share_label field in the database.
	FieldQuotaPerShareLabel = "quota_per_share_label"
	// FieldQuotaLabel holds the string denoting the quota_label field in the database.
	FieldQuotaLabel = "quota_label"
	// FieldMaxSharesPerUser holds the string denoting the max_shares_per_user field in the database.
	FieldMaxSharesPerUser = "max_shares_per_user"
	// FieldTargetGroupID holds the string denoting the target_group_id field in the database.
	FieldTargetGroupID = "target_group_id"
	// FieldTierGroupIds holds the string denoting the tier_group_ids field in the database.
	FieldTierGroupIds = "tier_group_ids"
	// FieldValidityDays holds the string denoting the validity_days field in the database.
	FieldValidityDays = "validity_days"
	// FieldTimeoutMinutes holds the string denoting the timeout_minutes field in the database.
	FieldTimeoutMinutes = "timeout_minutes"
	// FieldLaunchMode holds the string denoting the launch_mode field in the database.
	FieldLaunchMode = "launch_mode"
	// FieldRefundMode holds the string denoting the refund_mode field in the database.
	FieldRefundMode = "refund_mode"
	// FieldAgreementText holds the string denoting the agreement_text field in the database.
	FieldAgreementText = "agreement_text"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldLastRoundCreatedAt holds the string denoting the last_round_created_at field in the database.
	FieldLastRoundCreatedAt = "last_round_created_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeTargetGroup holds the string denoting the target_group edge name in mutations.
	EdgeTargetGroup = "target_group"
	// EdgeRounds holds the string denoting the rounds edge name in mutations.
	EdgeRounds = "rounds"
	// EdgeSeats holds the string denoting the seats edge name in mutations.
	EdgeSeats = "seats"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// Table holds the table name of the groupbuyplan in the database.
	Table = "group_buy_plans"
	// TargetGroupTable is the table that holds the target_group relation/edge.
	TargetGroupTable = "group_buy_plans"
	// TargetGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	TargetGroupInverseTable = "groups"
	// TargetGroupColumn is the table column denoting the target_group relation/edge.
	TargetGroupColumn = "target_group_id"
	// RoundsTable is the table that holds the rounds relation/edge.
	RoundsTable = "group_buy_rounds"
	// RoundsInverseTable is the table name for the GroupBuyRound entity.
	// It exists in this package in order to avoid circular dependency with the "groupbuyround" package.
	RoundsInverseTable = "group_buy_rounds"
	// RoundsColumn is the table column denoting the rounds relation/edge.
	RoundsColumn = "plan_id"
	// SeatsTable is the table that holds the seats relation/edge.
	SeatsTable = "group_buy_seats"
	// SeatsInverseTable is the table name for the GroupBuySeat entity.
	// It exists in this package in order to avoid circular dependency with the "groupbuyseat" package.
	SeatsInverseTable = "group_buy_seats"
	// SeatsColumn is the table column denoting the seats relation/edge.
	SeatsColumn = "plan_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "group_buy_events"
	// EventsInverseTable is the table name for the GroupBuyEvent entity.
	// It exists in this package in order to avoid circular dependency with the "groupbuyevent" package.
	EventsInverseTable = "group_buy_events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "plan_id"
)

// Columns holds all SQL columns for groupbuyplan fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTitle,
	FieldDescription,
	FieldProductKey,
	FieldTotalShares,
	FieldSeatCount,
	FieldPricePerShare,
	FieldPricePerSeat,
	FieldPriceLabel,
	FieldQuotaPerShareLabel,
	FieldQuotaLabel,
	FieldMaxSharesPerUser,
	FieldTargetGroupID,
	FieldTierGroupIds,
	FieldValidityDays,
	FieldTimeoutMinutes,
	FieldLaunchMode,
	FieldRefundMode,
	FieldAgreementText,
	FieldStatus,
	FieldSortOrder,
	FieldLastRoundCreatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultProductKey holds the default value on creation for the "product_key" field.
	DefaultProductKey string
	// ProductKeyValidator is a validator for the "product_key" field. It is called by the builders before save.
	ProductKeyValidator func(string) error
	// DefaultTotalShares holds the default value on creation for the "total_shares" field.
	DefaultTotalShares int
	// TotalSharesValidator is a validator for the "total_shares" field. It is called by the builders before save.
	TotalSharesValidator func(int) error
	// DefaultSeatCount holds the default value on creation for the "seat_count" field.
	DefaultSeatCount int
	// SeatCountValidator is a validator for the "seat_count" field. It is called by the builders before save.
	SeatCountValidator func(int) error
	// DefaultPriceLabel holds the default value on creation for the "price_label" field.
	DefaultPriceLabel string
	// PriceLabelValidator is a validator for the "price_label" field. It is called by the builders before save.
	PriceLabelValidator func(string) error
	// DefaultQuotaPerShareLabel holds the default value on creation for the "quota_per_share_label" field.
	DefaultQuotaPerShareLabel string
	// QuotaPerShareLabelValidator is a validator for the "quota_per_share_label" field. It is called by the builders before save.
	QuotaPerShareLabelValidator func(string) error
	// DefaultQuotaLabel holds the default value on creation for the "quota_label" field.
	DefaultQuotaLabel string
	// QuotaLabelValidator is a validator for the "quota_label" field. It is called by the builders before save.
	QuotaLabelValidator func(string) error
	// DefaultMaxSharesPerUser holds the default value on creation for the "max_shares_per_user" field.
	DefaultMaxSharesPerUser int
	// DefaultValidityDays holds the default value on creation for the "validity_days" field.
	DefaultValidityDays int
	// DefaultTimeoutMinutes holds the default value on creation for the "timeout_minutes" field.
	DefaultTimeoutMinutes int
	// DefaultLaunchMode holds the default value on creation for the "launch_mode" field.
	DefaultLaunchMode string
	// LaunchModeValidator is a validator for the "launch_mode" field. It is called by the builders before save.
	LaunchModeValidator func(string) error
	// DefaultRefundMode holds the default value on creation for the "refund_mode" field.
	DefaultRefundMode string
	// RefundModeValidator is a validator for the "refund_mode" field. It is called by the builders before save.
	RefundModeValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
)

// OrderOption defines the ordering options for the GroupBuyPlan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByProductKey orders the results by the product_key field.
func ByProductKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductKey, opts...).ToFunc()
}

// ByTotalShares orders the results by the total_shares field.
func ByTotalShares(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTotalShares, opts...).ToFunc()
}

// BySeatCount orders the results by the seat_count field.
func BySeatCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeatCount, opts...).ToFunc()
}

// ByPricePerShare orders the results by the price_per_share field.
func ByPricePerShare(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePerShare, opts...).ToFunc()
}

// ByPricePerSeat orders the results by the price_per_seat field.
func ByPricePerSeat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricePerSeat, opts...).ToFunc()
}

// ByPriceLabel orders the results by the price_label field.
func ByPriceLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceLabel, opts...).ToFunc()
}

// ByQuotaPerShareLabel orders the results by the quota_per_share_label field.
func ByQuotaPerShareLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaPerShareLabel, opts...).ToFunc()
}

// ByQuotaLabel orders the results by the quota_label field.
func ByQuotaLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaLabel, opts...).ToFunc()
}

// ByMaxSharesPerUser orders the results by the max_shares_per_user field.
func ByMaxSharesPerUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxSharesPerUser, opts...).ToFunc()
}

// ByTargetGroupID orders the results by the target_group_id field.
func ByTargetGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetGroupID, opts...).ToFunc()
}

// ByValidityDays orders the results by the validity_days field.
func ByValidityDays(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidityDays, opts...).ToFunc()
}

// ByTimeoutMinutes orders the results by the timeout_minutes field.
func ByTimeoutMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutMinutes, opts...).ToFunc()
}

// ByLaunchMode orders the results by the launch_mode field.
func ByLaunchMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLaunchMode, opts...).ToFunc()
}

// ByRefundMode orders the results by the refund_mode field.
func ByRefundMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefundMode, opts...).ToFunc()
}

// ByAgreementText orders the results by the agreement_text field.
func ByAgreementText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgreementText, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByLastRoundCreatedAt orders the results by the last_round_created_at field.
func ByLastRoundCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRoundCreatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByTargetGroupField orders the results by target_group field.
func ByTargetGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetGroupStep(), sql.OrderByField(field, opts...))
	}
}

// ByRoundsCount orders the results by rounds count.
func ByRoundsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoundsStep(), opts...)
	}
}

// ByRounds orders the results by rounds terms.
func ByRounds(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoundsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySeatsCount orders the results by seats count.
func BySeatsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSeatsStep(), opts...)
	}
}

// BySeats orders the results by seats terms.
func BySeats(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeatsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTargetGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetGroupTable, TargetGroupColumn),
	)
}
func newRoundsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoundsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoundsTable, RoundsColumn),
	)
}
func newSeatsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeatsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SeatsTable, SeatsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
