// Code generated by ent, DO NOT EDIT.

package groupbuyround

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldID, id))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldPlanID, v))
}

// CafeRoomID applies equality check predicate on the "cafe_room_id" field. It's identical to CafeRoomIDEQ.
func CafeRoomID(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCafeRoomID, v))
}

// AssignedAccountID applies equality check predicate on the "assigned_account_id" field. It's identical to AssignedAccountIDEQ.
func AssignedAccountID(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldAssignedAccountID, v))
}

// RoomCodeSnapshot applies equality check predicate on the "room_code_snapshot" field. It's identical to RoomCodeSnapshotEQ.
func RoomCodeSnapshot(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldRoomCodeSnapshot, v))
}

// RoomNameSnapshot applies equality check predicate on the "room_name_snapshot" field. It's identical to RoomNameSnapshotEQ.
func RoomNameSnapshot(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldRoomNameSnapshot, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldStatus, v))
}

// TotalShares applies equality check predicate on the "total_shares" field. It's identical to TotalSharesEQ.
func TotalShares(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldTotalShares, v))
}

// PaidShares applies equality check predicate on the "paid_shares" field. It's identical to PaidSharesEQ.
func PaidShares(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldPaidShares, v))
}

// ReservedShares applies equality check predicate on the "reserved_shares" field. It's identical to ReservedSharesEQ.
func ReservedShares(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldReservedShares, v))
}

// TotalSeats applies equality check predicate on the "total_seats" field. It's identical to TotalSeatsEQ.
func TotalSeats(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldTotalSeats, v))
}

// PaidSeats applies equality check predicate on the "paid_seats" field. It's identical to PaidSeatsEQ.
func PaidSeats(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldPaidSeats, v))
}

// ReservedSeats applies equality check predicate on the "reserved_seats" field. It's identical to ReservedSeatsEQ.
func ReservedSeats(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldReservedSeats, v))
}

// DeadlineAt applies equality check predicate on the "deadline_at" field. It's identical to DeadlineAtEQ.
func DeadlineAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldDeadlineAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldStartedAt, v))
}

// ClosedAt applies equality check predicate on the "closed_at" field. It's identical to ClosedAtEQ.
func ClosedAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldClosedAt, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldActivatedAt, v))
}

// EntitlementExpiresAt applies equality check predicate on the "entitlement_expires_at" field. It's identical to EntitlementExpiresAtEQ.
func EntitlementExpiresAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldEntitlementExpiresAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCompletedAt, v))
}

// ActivationToken applies equality check predicate on the "activation_token" field. It's identical to ActivationTokenEQ.
func ActivationToken(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldActivationToken, v))
}

// CloseReason applies equality check predicate on the "close_reason" field. It's identical to CloseReasonEQ.
func CloseReason(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCloseReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldUpdatedAt, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldPlanID, vs...))
}

// CafeRoomIDEQ applies the EQ predicate on the "cafe_room_id" field.
func CafeRoomIDEQ(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCafeRoomID, v))
}

// CafeRoomIDNEQ applies the NEQ predicate on the "cafe_room_id" field.
func CafeRoomIDNEQ(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldCafeRoomID, v))
}

// CafeRoomIDIn applies the In predicate on the "cafe_room_id" field.
func CafeRoomIDIn(vs ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldCafeRoomID, vs...))
}

// CafeRoomIDNotIn applies the NotIn predicate on the "cafe_room_id" field.
func CafeRoomIDNotIn(vs ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldCafeRoomID, vs...))
}

// CafeRoomIDIsNil applies the IsNil predicate on the "cafe_room_id" field.
func CafeRoomIDIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldCafeRoomID))
}

// CafeRoomIDNotNil applies the NotNil predicate on the "cafe_room_id" field.
func CafeRoomIDNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldCafeRoomID))
}

// AssignedAccountIDEQ applies the EQ predicate on the "assigned_account_id" field.
func AssignedAccountIDEQ(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldAssignedAccountID, v))
}

// AssignedAccountIDNEQ applies the NEQ predicate on the "assigned_account_id" field.
func AssignedAccountIDNEQ(v int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldAssignedAccountID, v))
}

// AssignedAccountIDIn applies the In predicate on the "assigned_account_id" field.
func AssignedAccountIDIn(vs ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldAssignedAccountID, vs...))
}

// AssignedAccountIDNotIn applies the NotIn predicate on the "assigned_account_id" field.
func AssignedAccountIDNotIn(vs ...int64) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldAssignedAccountID, vs...))
}

// AssignedAccountIDIsNil applies the IsNil predicate on the "assigned_account_id" field.
func AssignedAccountIDIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldAssignedAccountID))
}

// AssignedAccountIDNotNil applies the NotNil predicate on the "assigned_account_id" field.
func AssignedAccountIDNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldAssignedAccountID))
}

// RoomCodeSnapshotEQ applies the EQ predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotNEQ applies the NEQ predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotNEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotIn applies the In predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldRoomCodeSnapshot, vs...))
}

// RoomCodeSnapshotNotIn applies the NotIn predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotNotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldRoomCodeSnapshot, vs...))
}

// RoomCodeSnapshotGT applies the GT predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotGT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotGTE applies the GTE predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotGTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotLT applies the LT predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotLT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotLTE applies the LTE predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotLTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotContains applies the Contains predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotContains(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContains(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotHasPrefix applies the HasPrefix predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotHasPrefix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasPrefix(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotHasSuffix applies the HasSuffix predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotHasSuffix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasSuffix(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotIsNil applies the IsNil predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldRoomCodeSnapshot))
}

// RoomCodeSnapshotNotNil applies the NotNil predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldRoomCodeSnapshot))
}

// RoomCodeSnapshotEqualFold applies the EqualFold predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotEqualFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEqualFold(FieldRoomCodeSnapshot, v))
}

// RoomCodeSnapshotContainsFold applies the ContainsFold predicate on the "room_code_snapshot" field.
func RoomCodeSnapshotContainsFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContainsFold(FieldRoomCodeSnapshot, v))
}

// RoomNameSnapshotEQ applies the EQ predicate on the "room_name_snapshot" field.
func RoomNameSnapshotEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotNEQ applies the NEQ predicate on the "room_name_snapshot" field.
func RoomNameSnapshotNEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotIn applies the In predicate on the "room_name_snapshot" field.
func RoomNameSnapshotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldRoomNameSnapshot, vs...))
}

// RoomNameSnapshotNotIn applies the NotIn predicate on the "room_name_snapshot" field.
func RoomNameSnapshotNotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldRoomNameSnapshot, vs...))
}

// RoomNameSnapshotGT applies the GT predicate on the "room_name_snapshot" field.
func RoomNameSnapshotGT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotGTE applies the GTE predicate on the "room_name_snapshot" field.
func RoomNameSnapshotGTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotLT applies the LT predicate on the "room_name_snapshot" field.
func RoomNameSnapshotLT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotLTE applies the LTE predicate on the "room_name_snapshot" field.
func RoomNameSnapshotLTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotContains applies the Contains predicate on the "room_name_snapshot" field.
func RoomNameSnapshotContains(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContains(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotHasPrefix applies the HasPrefix predicate on the "room_name_snapshot" field.
func RoomNameSnapshotHasPrefix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasPrefix(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotHasSuffix applies the HasSuffix predicate on the "room_name_snapshot" field.
func RoomNameSnapshotHasSuffix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasSuffix(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotIsNil applies the IsNil predicate on the "room_name_snapshot" field.
func RoomNameSnapshotIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldRoomNameSnapshot))
}

// RoomNameSnapshotNotNil applies the NotNil predicate on the "room_name_snapshot" field.
func RoomNameSnapshotNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldRoomNameSnapshot))
}

// RoomNameSnapshotEqualFold applies the EqualFold predicate on the "room_name_snapshot" field.
func RoomNameSnapshotEqualFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEqualFold(FieldRoomNameSnapshot, v))
}

// RoomNameSnapshotContainsFold applies the ContainsFold predicate on the "room_name_snapshot" field.
func RoomNameSnapshotContainsFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContainsFold(FieldRoomNameSnapshot, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContainsFold(FieldStatus, v))
}

// TotalSharesEQ applies the EQ predicate on the "total_shares" field.
func TotalSharesEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldTotalShares, v))
}

// TotalSharesNEQ applies the NEQ predicate on the "total_shares" field.
func TotalSharesNEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldTotalShares, v))
}

// TotalSharesIn applies the In predicate on the "total_shares" field.
func TotalSharesIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldTotalShares, vs...))
}

// TotalSharesNotIn applies the NotIn predicate on the "total_shares" field.
func TotalSharesNotIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldTotalShares, vs...))
}

// TotalSharesGT applies the GT predicate on the "total_shares" field.
func TotalSharesGT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldTotalShares, v))
}

// TotalSharesGTE applies the GTE predicate on the "total_shares" field.
func TotalSharesGTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldTotalShares, v))
}

// TotalSharesLT applies the LT predicate on the "total_shares" field.
func TotalSharesLT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldTotalShares, v))
}

// TotalSharesLTE applies the LTE predicate on the "total_shares" field.
func TotalSharesLTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldTotalShares, v))
}

// PaidSharesEQ applies the EQ predicate on the "paid_shares" field.
func PaidSharesEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldPaidShares, v))
}

// PaidSharesNEQ applies the NEQ predicate on the "paid_shares" field.
func PaidSharesNEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldPaidShares, v))
}

// PaidSharesIn applies the In predicate on the "paid_shares" field.
func PaidSharesIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldPaidShares, vs...))
}

// PaidSharesNotIn applies the NotIn predicate on the "paid_shares" field.
func PaidSharesNotIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldPaidShares, vs...))
}

// PaidSharesGT applies the GT predicate on the "paid_shares" field.
func PaidSharesGT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldPaidShares, v))
}

// PaidSharesGTE applies the GTE predicate on the "paid_shares" field.
func PaidSharesGTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldPaidShares, v))
}

// PaidSharesLT applies the LT predicate on the "paid_shares" field.
func PaidSharesLT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldPaidShares, v))
}

// PaidSharesLTE applies the LTE predicate on the "paid_shares" field.
func PaidSharesLTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldPaidShares, v))
}

// ReservedSharesEQ applies the EQ predicate on the "reserved_shares" field.
func ReservedSharesEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldReservedShares, v))
}

// ReservedSharesNEQ applies the NEQ predicate on the "reserved_shares" field.
func ReservedSharesNEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldReservedShares, v))
}

// ReservedSharesIn applies the In predicate on the "reserved_shares" field.
func ReservedSharesIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldReservedShares, vs...))
}

// ReservedSharesNotIn applies the NotIn predicate on the "reserved_shares" field.
func ReservedSharesNotIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldReservedShares, vs...))
}

// ReservedSharesGT applies the GT predicate on the "reserved_shares" field.
func ReservedSharesGT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldReservedShares, v))
}

// ReservedSharesGTE applies the GTE predicate on the "reserved_shares" field.
func ReservedSharesGTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldReservedShares, v))
}

// ReservedSharesLT applies the LT predicate on the "reserved_shares" field.
func ReservedSharesLT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldReservedShares, v))
}

// ReservedSharesLTE applies the LTE predicate on the "reserved_shares" field.
func ReservedSharesLTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldReservedShares, v))
}

// TotalSeatsEQ applies the EQ predicate on the "total_seats" field.
func TotalSeatsEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldTotalSeats, v))
}

// TotalSeatsNEQ applies the NEQ predicate on the "total_seats" field.
func TotalSeatsNEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldTotalSeats, v))
}

// TotalSeatsIn applies the In predicate on the "total_seats" field.
func TotalSeatsIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldTotalSeats, vs...))
}

// TotalSeatsNotIn applies the NotIn predicate on the "total_seats" field.
func TotalSeatsNotIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldTotalSeats, vs...))
}

// TotalSeatsGT applies the GT predicate on the "total_seats" field.
func TotalSeatsGT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldTotalSeats, v))
}

// TotalSeatsGTE applies the GTE predicate on the "total_seats" field.
func TotalSeatsGTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldTotalSeats, v))
}

// TotalSeatsLT applies the LT predicate on the "total_seats" field.
func TotalSeatsLT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldTotalSeats, v))
}

// TotalSeatsLTE applies the LTE predicate on the "total_seats" field.
func TotalSeatsLTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldTotalSeats, v))
}

// PaidSeatsEQ applies the EQ predicate on the "paid_seats" field.
func PaidSeatsEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldPaidSeats, v))
}

// PaidSeatsNEQ applies the NEQ predicate on the "paid_seats" field.
func PaidSeatsNEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldPaidSeats, v))
}

// PaidSeatsIn applies the In predicate on the "paid_seats" field.
func PaidSeatsIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldPaidSeats, vs...))
}

// PaidSeatsNotIn applies the NotIn predicate on the "paid_seats" field.
func PaidSeatsNotIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldPaidSeats, vs...))
}

// PaidSeatsGT applies the GT predicate on the "paid_seats" field.
func PaidSeatsGT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldPaidSeats, v))
}

// PaidSeatsGTE applies the GTE predicate on the "paid_seats" field.
func PaidSeatsGTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldPaidSeats, v))
}

// PaidSeatsLT applies the LT predicate on the "paid_seats" field.
func PaidSeatsLT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldPaidSeats, v))
}

// PaidSeatsLTE applies the LTE predicate on the "paid_seats" field.
func PaidSeatsLTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldPaidSeats, v))
}

// ReservedSeatsEQ applies the EQ predicate on the "reserved_seats" field.
func ReservedSeatsEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldReservedSeats, v))
}

// ReservedSeatsNEQ applies the NEQ predicate on the "reserved_seats" field.
func ReservedSeatsNEQ(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldReservedSeats, v))
}

// ReservedSeatsIn applies the In predicate on the "reserved_seats" field.
func ReservedSeatsIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldReservedSeats, vs...))
}

// ReservedSeatsNotIn applies the NotIn predicate on the "reserved_seats" field.
func ReservedSeatsNotIn(vs ...int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldReservedSeats, vs...))
}

// ReservedSeatsGT applies the GT predicate on the "reserved_seats" field.
func ReservedSeatsGT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldReservedSeats, v))
}

// ReservedSeatsGTE applies the GTE predicate on the "reserved_seats" field.
func ReservedSeatsGTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldReservedSeats, v))
}

// ReservedSeatsLT applies the LT predicate on the "reserved_seats" field.
func ReservedSeatsLT(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldReservedSeats, v))
}

// ReservedSeatsLTE applies the LTE predicate on the "reserved_seats" field.
func ReservedSeatsLTE(v int) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldReservedSeats, v))
}

// DeadlineAtEQ applies the EQ predicate on the "deadline_at" field.
func DeadlineAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldDeadlineAt, v))
}

// DeadlineAtNEQ applies the NEQ predicate on the "deadline_at" field.
func DeadlineAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldDeadlineAt, v))
}

// DeadlineAtIn applies the In predicate on the "deadline_at" field.
func DeadlineAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldDeadlineAt, vs...))
}

// DeadlineAtNotIn applies the NotIn predicate on the "deadline_at" field.
func DeadlineAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldDeadlineAt, vs...))
}

// DeadlineAtGT applies the GT predicate on the "deadline_at" field.
func DeadlineAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldDeadlineAt, v))
}

// DeadlineAtGTE applies the GTE predicate on the "deadline_at" field.
func DeadlineAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldDeadlineAt, v))
}

// DeadlineAtLT applies the LT predicate on the "deadline_at" field.
func DeadlineAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldDeadlineAt, v))
}

// DeadlineAtLTE applies the LTE predicate on the "deadline_at" field.
func DeadlineAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldDeadlineAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldStartedAt))
}

// ClosedAtEQ applies the EQ predicate on the "closed_at" field.
func ClosedAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldClosedAt, v))
}

// ClosedAtNEQ applies the NEQ predicate on the "closed_at" field.
func ClosedAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldClosedAt, v))
}

// ClosedAtIn applies the In predicate on the "closed_at" field.
func ClosedAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldClosedAt, vs...))
}

// ClosedAtNotIn applies the NotIn predicate on the "closed_at" field.
func ClosedAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldClosedAt, vs...))
}

// ClosedAtGT applies the GT predicate on the "closed_at" field.
func ClosedAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldClosedAt, v))
}

// ClosedAtGTE applies the GTE predicate on the "closed_at" field.
func ClosedAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldClosedAt, v))
}

// ClosedAtLT applies the LT predicate on the "closed_at" field.
func ClosedAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldClosedAt, v))
}

// ClosedAtLTE applies the LTE predicate on the "closed_at" field.
func ClosedAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldClosedAt, v))
}

// ClosedAtIsNil applies the IsNil predicate on the "closed_at" field.
func ClosedAtIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldClosedAt))
}

// ClosedAtNotNil applies the NotNil predicate on the "closed_at" field.
func ClosedAtNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldClosedAt))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldActivatedAt))
}

// EntitlementExpiresAtEQ applies the EQ predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldEntitlementExpiresAt, v))
}

// EntitlementExpiresAtNEQ applies the NEQ predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldEntitlementExpiresAt, v))
}

// EntitlementExpiresAtIn applies the In predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldEntitlementExpiresAt, vs...))
}

// EntitlementExpiresAtNotIn applies the NotIn predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldEntitlementExpiresAt, vs...))
}

// EntitlementExpiresAtGT applies the GT predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldEntitlementExpiresAt, v))
}

// EntitlementExpiresAtGTE applies the GTE predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldEntitlementExpiresAt, v))
}

// EntitlementExpiresAtLT applies the LT predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldEntitlementExpiresAt, v))
}

// EntitlementExpiresAtLTE applies the LTE predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldEntitlementExpiresAt, v))
}

// EntitlementExpiresAtIsNil applies the IsNil predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldEntitlementExpiresAt))
}

// EntitlementExpiresAtNotNil applies the NotNil predicate on the "entitlement_expires_at" field.
func EntitlementExpiresAtNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldEntitlementExpiresAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldCompletedAt))
}

// ActivationTokenEQ applies the EQ predicate on the "activation_token" field.
func ActivationTokenEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldActivationToken, v))
}

// ActivationTokenNEQ applies the NEQ predicate on the "activation_token" field.
func ActivationTokenNEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldActivationToken, v))
}

// ActivationTokenIn applies the In predicate on the "activation_token" field.
func ActivationTokenIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldActivationToken, vs...))
}

// ActivationTokenNotIn applies the NotIn predicate on the "activation_token" field.
func ActivationTokenNotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldActivationToken, vs...))
}

// ActivationTokenGT applies the GT predicate on the "activation_token" field.
func ActivationTokenGT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldActivationToken, v))
}

// ActivationTokenGTE applies the GTE predicate on the "activation_token" field.
func ActivationTokenGTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldActivationToken, v))
}

// ActivationTokenLT applies the LT predicate on the "activation_token" field.
func ActivationTokenLT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldActivationToken, v))
}

// ActivationTokenLTE applies the LTE predicate on the "activation_token" field.
func ActivationTokenLTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldActivationToken, v))
}

// ActivationTokenContains applies the Contains predicate on the "activation_token" field.
func ActivationTokenContains(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContains(FieldActivationToken, v))
}

// ActivationTokenHasPrefix applies the HasPrefix predicate on the "activation_token" field.
func ActivationTokenHasPrefix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasPrefix(FieldActivationToken, v))
}

// ActivationTokenHasSuffix applies the HasSuffix predicate on the "activation_token" field.
func ActivationTokenHasSuffix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasSuffix(FieldActivationToken, v))
}

// ActivationTokenIsNil applies the IsNil predicate on the "activation_token" field.
func ActivationTokenIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldActivationToken))
}

// ActivationTokenNotNil applies the NotNil predicate on the "activation_token" field.
func ActivationTokenNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldActivationToken))
}

// ActivationTokenEqualFold applies the EqualFold predicate on the "activation_token" field.
func ActivationTokenEqualFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEqualFold(FieldActivationToken, v))
}

// ActivationTokenContainsFold applies the ContainsFold predicate on the "activation_token" field.
func ActivationTokenContainsFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContainsFold(FieldActivationToken, v))
}

// CloseReasonEQ applies the EQ predicate on the "close_reason" field.
func CloseReasonEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCloseReason, v))
}

// CloseReasonNEQ applies the NEQ predicate on the "close_reason" field.
func CloseReasonNEQ(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldCloseReason, v))
}

// CloseReasonIn applies the In predicate on the "close_reason" field.
func CloseReasonIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldCloseReason, vs...))
}

// CloseReasonNotIn applies the NotIn predicate on the "close_reason" field.
func CloseReasonNotIn(vs ...string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldCloseReason, vs...))
}

// CloseReasonGT applies the GT predicate on the "close_reason" field.
func CloseReasonGT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldCloseReason, v))
}

// CloseReasonGTE applies the GTE predicate on the "close_reason" field.
func CloseReasonGTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldCloseReason, v))
}

// CloseReasonLT applies the LT predicate on the "close_reason" field.
func CloseReasonLT(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldCloseReason, v))
}

// CloseReasonLTE applies the LTE predicate on the "close_reason" field.
func CloseReasonLTE(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldCloseReason, v))
}

// CloseReasonContains applies the Contains predicate on the "close_reason" field.
func CloseReasonContains(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContains(FieldCloseReason, v))
}

// CloseReasonHasPrefix applies the HasPrefix predicate on the "close_reason" field.
func CloseReasonHasPrefix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasPrefix(FieldCloseReason, v))
}

// CloseReasonHasSuffix applies the HasSuffix predicate on the "close_reason" field.
func CloseReasonHasSuffix(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldHasSuffix(FieldCloseReason, v))
}

// CloseReasonIsNil applies the IsNil predicate on the "close_reason" field.
func CloseReasonIsNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIsNull(FieldCloseReason))
}

// CloseReasonNotNil applies the NotNil predicate on the "close_reason" field.
func CloseReasonNotNil() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotNull(FieldCloseReason))
}

// CloseReasonEqualFold applies the EqualFold predicate on the "close_reason" field.
func CloseReasonEqualFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEqualFold(FieldCloseReason, v))
}

// CloseReasonContainsFold applies the ContainsFold predicate on the "close_reason" field.
func CloseReasonContainsFold(v string) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldContainsFold(FieldCloseReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.GroupBuyPlan) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeats applies the HasEdge predicate on the "seats" edge.
func HasSeats() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SeatsTable, SeatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeatsWith applies the HasEdge predicate on the "seats" edge with a given conditions (other predicates).
func HasSeatsWith(preds ...predicate.GroupBuySeat) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := newSeatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEvents applies the HasEdge predicate on the "events" edge.
func HasEvents() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEventsWith applies the HasEdge predicate on the "events" edge with a given conditions (other predicates).
func HasEventsWith(preds ...predicate.GroupBuyEvent) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := newEventsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCafeRoom applies the HasEdge predicate on the "cafe_room" edge.
func HasCafeRoom() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CafeRoomTable, CafeRoomColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCafeRoomWith applies the HasEdge predicate on the "cafe_room" edge with a given conditions (other predicates).
func HasCafeRoomWith(preds ...predicate.CafeRoom) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := newCafeRoomStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAssignedAccount applies the HasEdge predicate on the "assigned_account" edge.
func HasAssignedAccount() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AssignedAccountTable, AssignedAccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAssignedAccountWith applies the HasEdge predicate on the "assigned_account" edge with a given conditions (other predicates).
func HasAssignedAccountWith(preds ...predicate.Account) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := newAssignedAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountBindings applies the HasEdge predicate on the "account_bindings" edge.
func HasAccountBindings() predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountBindingsTable, AccountBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountBindingsWith applies the HasEdge predicate on the "account_bindings" edge with a given conditions (other predicates).
func HasAccountBindingsWith(preds ...predicate.APIKeyAccountBinding) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(func(s *sql.Selector) {
		step := newAccountBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupBuyRound) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupBuyRound) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupBuyRound) predicate.GroupBuyRound {
	return predicate.GroupBuyRound(sql.NotPredicates(p))
}
