// Code generated by ent, DO NOT EDIT.

package groupbuyentitlement

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the groupbuyentitlement type in the database.
	Label = "group_buy_entitlement"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProductKey holds the string denoting the product_key field in the database.
	FieldProductKey = "product_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldActiveShareCount holds the string denoting the active_share_count field in the database.
	FieldActiveShareCount = "active_share_count"
	// FieldTargetGroupID holds the string denoting the target_group_id field in the database.
	FieldTargetGroupID = "target_group_id"
	// FieldSubscriptionID holds the string denoting the subscription_id field in the database.
	FieldSubscriptionID = "subscription_id"
	// FieldManagedSubscriptionID holds the string denoting the managed_subscription_id field in the database.
	FieldManagedSubscriptionID = "managed_subscription_id"
	// FieldBoundAPIKeyID holds the string denoting the bound_api_key_id field in the database.
	FieldBoundAPIKeyID = "bound_api_key_id"
	// FieldLastActivatedAt holds the string denoting the last_activated_at field in the database.
	FieldLastActivatedAt = "last_activated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldRefreshedAt holds the string denoting the refreshed_at field in the database.
	FieldRefreshedAt = "refreshed_at"
	// FieldDeactivatedAt holds the string denoting the deactivated_at field in the database.
	FieldDeactivatedAt = "deactivated_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeTargetGroup holds the string denoting the target_group edge name in mutations.
	EdgeTargetGroup = "target_group"
	// EdgeSubscription holds the string denoting the subscription edge name in mutations.
	EdgeSubscription = "subscription"
	// EdgeManagedSubscription holds the string denoting the managed_subscription edge name in mutations.
	EdgeManagedSubscription = "managed_subscription"
	// EdgeBoundAPIKey holds the string denoting the bound_api_key edge name in mutations.
	EdgeBoundAPIKey = "bound_api_key"
	// Table holds the table name of the groupbuyentitlement in the database.
	Table = "group_buy_entitlements"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "group_buy_entitlements"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// TargetGroupTable is the table that holds the target_group relation/edge.
	TargetGroupTable = "group_buy_entitlements"
	// TargetGroupInverseTable is the table name for the Group entity.
	// It exists in this package in order to avoid circular dependency with the "group" package.
	TargetGroupInverseTable = "groups"
	// TargetGroupColumn is the table column denoting the target_group relation/edge.
	TargetGroupColumn = "target_group_id"
	// SubscriptionTable is the table that holds the subscription relation/edge.
	SubscriptionTable = "group_buy_entitlements"
	// SubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	SubscriptionInverseTable = "user_subscriptions"
	// SubscriptionColumn is the table column denoting the subscription relation/edge.
	SubscriptionColumn = "subscription_id"
	// ManagedSubscriptionTable is the table that holds the managed_subscription relation/edge.
	ManagedSubscriptionTable = "group_buy_entitlements"
	// ManagedSubscriptionInverseTable is the table name for the UserSubscription entity.
	// It exists in this package in order to avoid circular dependency with the "usersubscription" package.
	ManagedSubscriptionInverseTable = "user_subscriptions"
	// ManagedSubscriptionColumn is the table column denoting the managed_subscription relation/edge.
	ManagedSubscriptionColumn = "managed_subscription_id"
	// BoundAPIKeyTable is the table that holds the bound_api_key relation/edge.
	BoundAPIKeyTable = "group_buy_entitlements"
	// BoundAPIKeyInverseTable is the table name for the APIKey entity.
	// It exists in this package in order to avoid circular dependency with the "apikey" package.
	BoundAPIKeyInverseTable = "api_keys"
	// BoundAPIKeyColumn is the table column denoting the bound_api_key relation/edge.
	BoundAPIKeyColumn = "bound_api_key_id"
)

// Columns holds all SQL columns for groupbuyentitlement fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProductKey,
	FieldStatus,
	FieldActiveShareCount,
	FieldTargetGroupID,
	FieldSubscriptionID,
	FieldManagedSubscriptionID,
	FieldBoundAPIKeyID,
	FieldLastActivatedAt,
	FieldExpiresAt,
	FieldRefreshedAt,
	FieldDeactivatedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultProductKey holds the default value on creation for the "product_key" field.
	DefaultProductKey string
	// ProductKeyValidator is a validator for the "product_key" field. It is called by the builders before save.
	ProductKeyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultActiveShareCount holds the default value on creation for the "active_share_count" field.
	DefaultActiveShareCount int
	// DefaultRefreshedAt holds the default value on creation for the "refreshed_at" field.
	DefaultRefreshedAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the GroupBuyEntitlement queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProductKey orders the results by the product_key field.
func ByProductKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProductKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByActiveShareCount orders the results by the active_share_count field.
func ByActiveShareCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveShareCount, opts...).ToFunc()
}

// ByTargetGroupID orders the results by the target_group_id field.
func ByTargetGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetGroupID, opts...).ToFunc()
}

// BySubscriptionID orders the results by the subscription_id field.
func BySubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionID, opts...).ToFunc()
}

// ByManagedSubscriptionID orders the results by the managed_subscription_id field.
func ByManagedSubscriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManagedSubscriptionID, opts...).ToFunc()
}

// ByBoundAPIKeyID orders the results by the bound_api_key_id field.
func ByBoundAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoundAPIKeyID, opts...).ToFunc()
}

// ByLastActivatedAt orders the results by the last_activated_at field.
func ByLastActivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActivatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByRefreshedAt orders the results by the refreshed_at field.
func ByRefreshedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshedAt, opts...).ToFunc()
}

// ByDeactivatedAt orders the results by the deactivated_at field.
func ByDeactivatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeactivatedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByTargetGroupField orders the results by target_group field.
func ByTargetGroupField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTargetGroupStep(), sql.OrderByField(field, opts...))
	}
}

// BySubscriptionField orders the results by subscription field.
func BySubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByManagedSubscriptionField orders the results by managed_subscription field.
func ByManagedSubscriptionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newManagedSubscriptionStep(), sql.OrderByField(field, opts...))
	}
}

// ByBoundAPIKeyField orders the results by bound_api_key field.
func ByBoundAPIKeyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBoundAPIKeyStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newTargetGroupStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TargetGroupInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TargetGroupTable, TargetGroupColumn),
	)
}
func newSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SubscriptionTable, SubscriptionColumn),
	)
}
func newManagedSubscriptionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ManagedSubscriptionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ManagedSubscriptionTable, ManagedSubscriptionColumn),
	)
}
func newBoundAPIKeyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BoundAPIKeyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, BoundAPIKeyTable, BoundAPIKeyColumn),
	)
}
