// Code generated by ent, DO NOT EDIT.

package caferoom

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the caferoom type in the database.
	Label = "cafe_room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldZoneKey holds the string denoting the zone_key field in the database.
	FieldZoneKey = "zone_key"
	// FieldThemeKey holds the string denoting the theme_key field in the database.
	FieldThemeKey = "theme_key"
	// FieldSceneSlotKey holds the string denoting the scene_slot_key field in the database.
	FieldSceneSlotKey = "scene_slot_key"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFeatured holds the string denoting the featured field in the database.
	FieldFeatured = "featured"
	// FieldSortOrder holds the string denoting the sort_order field in the database.
	FieldSortOrder = "sort_order"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// EdgeAccount holds the string denoting the account edge name in mutations.
	EdgeAccount = "account"
	// EdgeRounds holds the string denoting the rounds edge name in mutations.
	EdgeRounds = "rounds"
	// EdgeAccountBindings holds the string denoting the account_bindings edge name in mutations.
	EdgeAccountBindings = "account_bindings"
	// Table holds the table name of the caferoom in the database.
	Table = "cafe_rooms"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "cafe_rooms"
	// PlanInverseTable is the table name for the GroupBuyPlan entity.
	// It exists in this package in order to avoid circular dependency with the "groupbuyplan" package.
	PlanInverseTable = "group_buy_plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_id"
	// AccountTable is the table that holds the account relation/edge.
	AccountTable = "cafe_rooms"
	// AccountInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountInverseTable = "accounts"
	// AccountColumn is the table column denoting the account relation/edge.
	AccountColumn = "account_id"
	// RoundsTable is the table that holds the rounds relation/edge.
	RoundsTable = "group_buy_rounds"
	// RoundsInverseTable is the table name for the GroupBuyRound entity.
	// It exists in this package in order to avoid circular dependency with the "groupbuyround" package.
	RoundsInverseTable = "group_buy_rounds"
	// RoundsColumn is the table column denoting the rounds relation/edge.
	RoundsColumn = "cafe_room_id"
	// AccountBindingsTable is the table that holds the account_bindings relation/edge.
	AccountBindingsTable = "api_key_account_bindings"
	// AccountBindingsInverseTable is the table name for the APIKeyAccountBinding entity.
	// It exists in this package in order to avoid circular dependency with the "apikeyaccountbinding" package.
	AccountBindingsInverseTable = "api_key_account_bindings"
	// AccountBindingsColumn is the table column denoting the account_bindings relation/edge.
	AccountBindingsColumn = "cafe_room_id"
)

// Columns holds all SQL columns for caferoom fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldCode,
	FieldName,
	FieldPlanID,
	FieldAccountID,
	FieldZoneKey,
	FieldThemeKey,
	FieldSceneSlotKey,
	FieldStatus,
	FieldFeatured,
	FieldSortOrder,
	FieldMetadata,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "cafe_rooms"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"group_cafe_rooms",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultZoneKey holds the default value on creation for the "zone_key" field.
	DefaultZoneKey string
	// ZoneKeyValidator is a validator for the "zone_key" field. It is called by the builders before save.
	ZoneKeyValidator func(string) error
	// DefaultThemeKey holds the default value on creation for the "theme_key" field.
	DefaultThemeKey string
	// ThemeKeyValidator is a validator for the "theme_key" field. It is called by the builders before save.
	ThemeKeyValidator func(string) error
	// DefaultSceneSlotKey holds the default value on creation for the "scene_slot_key" field.
	DefaultSceneSlotKey string
	// SceneSlotKeyValidator is a validator for the "scene_slot_key" field. It is called by the builders before save.
	SceneSlotKeyValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFeatured holds the default value on creation for the "featured" field.
	DefaultFeatured bool
	// DefaultSortOrder holds the default value on creation for the "sort_order" field.
	DefaultSortOrder int
	// DefaultMetadata holds the default value on creation for the "metadata" field.
	DefaultMetadata func() map[string]interface{}
)

// OrderOption defines the ordering options for the CafeRoom queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByCode orders the results by the code field.
func ByCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCode, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByZoneKey orders the results by the zone_key field.
func ByZoneKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldZoneKey, opts...).ToFunc()
}

// ByThemeKey orders the results by the theme_key field.
func ByThemeKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldThemeKey, opts...).ToFunc()
}

// BySceneSlotKey orders the results by the scene_slot_key field.
func BySceneSlotKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSceneSlotKey, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFeatured orders the results by the featured field.
func ByFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeatured, opts...).ToFunc()
}

// BySortOrder orders the results by the sort_order field.
func BySortOrder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSortOrder, opts...).ToFunc()
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}

// ByAccountField orders the results by account field.
func ByAccountField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountStep(), sql.OrderByField(field, opts...))
	}
}

// ByRoundsCount orders the results by rounds count.
func ByRoundsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRoundsStep(), opts...)
	}
}

// ByRounds orders the results by rounds terms.
func ByRounds(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRoundsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountBindingsCount orders the results by account_bindings count.
func ByAccountBindingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountBindingsStep(), opts...)
	}
}

// ByAccountBindings orders the results by account_bindings terms.
func ByAccountBindings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountBindingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
	)
}
func newAccountStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
	)
}
func newRoundsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RoundsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, RoundsTable, RoundsColumn),
	)
}
func newAccountBindingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountBindingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AccountBindingsTable, AccountBindingsColumn),
	)
}
