// Code generated by ent, DO NOT EDIT.

package caferoom

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldDeletedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldCode, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldName, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldPlanID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldAccountID, v))
}

// ZoneKey applies equality check predicate on the "zone_key" field. It's identical to ZoneKeyEQ.
func ZoneKey(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldZoneKey, v))
}

// ThemeKey applies equality check predicate on the "theme_key" field. It's identical to ThemeKeyEQ.
func ThemeKey(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldThemeKey, v))
}

// SceneSlotKey applies equality check predicate on the "scene_slot_key" field. It's identical to SceneSlotKeyEQ.
func SceneSlotKey(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldSceneSlotKey, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldStatus, v))
}

// Featured applies equality check predicate on the "featured" field. It's identical to FeaturedEQ.
func Featured(v bool) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldFeatured, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotNull(FieldDeletedAt))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContainsFold(FieldCode, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContainsFold(FieldName, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldPlanID, vs...))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotNull(FieldAccountID))
}

// ZoneKeyEQ applies the EQ predicate on the "zone_key" field.
func ZoneKeyEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldZoneKey, v))
}

// ZoneKeyNEQ applies the NEQ predicate on the "zone_key" field.
func ZoneKeyNEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldZoneKey, v))
}

// ZoneKeyIn applies the In predicate on the "zone_key" field.
func ZoneKeyIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldZoneKey, vs...))
}

// ZoneKeyNotIn applies the NotIn predicate on the "zone_key" field.
func ZoneKeyNotIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldZoneKey, vs...))
}

// ZoneKeyGT applies the GT predicate on the "zone_key" field.
func ZoneKeyGT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldZoneKey, v))
}

// ZoneKeyGTE applies the GTE predicate on the "zone_key" field.
func ZoneKeyGTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldZoneKey, v))
}

// ZoneKeyLT applies the LT predicate on the "zone_key" field.
func ZoneKeyLT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldZoneKey, v))
}

// ZoneKeyLTE applies the LTE predicate on the "zone_key" field.
func ZoneKeyLTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldZoneKey, v))
}

// ZoneKeyContains applies the Contains predicate on the "zone_key" field.
func ZoneKeyContains(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContains(FieldZoneKey, v))
}

// ZoneKeyHasPrefix applies the HasPrefix predicate on the "zone_key" field.
func ZoneKeyHasPrefix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasPrefix(FieldZoneKey, v))
}

// ZoneKeyHasSuffix applies the HasSuffix predicate on the "zone_key" field.
func ZoneKeyHasSuffix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasSuffix(FieldZoneKey, v))
}

// ZoneKeyEqualFold applies the EqualFold predicate on the "zone_key" field.
func ZoneKeyEqualFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEqualFold(FieldZoneKey, v))
}

// ZoneKeyContainsFold applies the ContainsFold predicate on the "zone_key" field.
func ZoneKeyContainsFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContainsFold(FieldZoneKey, v))
}

// ThemeKeyEQ applies the EQ predicate on the "theme_key" field.
func ThemeKeyEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldThemeKey, v))
}

// ThemeKeyNEQ applies the NEQ predicate on the "theme_key" field.
func ThemeKeyNEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldThemeKey, v))
}

// ThemeKeyIn applies the In predicate on the "theme_key" field.
func ThemeKeyIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldThemeKey, vs...))
}

// ThemeKeyNotIn applies the NotIn predicate on the "theme_key" field.
func ThemeKeyNotIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldThemeKey, vs...))
}

// ThemeKeyGT applies the GT predicate on the "theme_key" field.
func ThemeKeyGT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldThemeKey, v))
}

// ThemeKeyGTE applies the GTE predicate on the "theme_key" field.
func ThemeKeyGTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldThemeKey, v))
}

// ThemeKeyLT applies the LT predicate on the "theme_key" field.
func ThemeKeyLT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldThemeKey, v))
}

// ThemeKeyLTE applies the LTE predicate on the "theme_key" field.
func ThemeKeyLTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldThemeKey, v))
}

// ThemeKeyContains applies the Contains predicate on the "theme_key" field.
func ThemeKeyContains(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContains(FieldThemeKey, v))
}

// ThemeKeyHasPrefix applies the HasPrefix predicate on the "theme_key" field.
func ThemeKeyHasPrefix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasPrefix(FieldThemeKey, v))
}

// ThemeKeyHasSuffix applies the HasSuffix predicate on the "theme_key" field.
func ThemeKeyHasSuffix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasSuffix(FieldThemeKey, v))
}

// ThemeKeyEqualFold applies the EqualFold predicate on the "theme_key" field.
func ThemeKeyEqualFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEqualFold(FieldThemeKey, v))
}

// ThemeKeyContainsFold applies the ContainsFold predicate on the "theme_key" field.
func ThemeKeyContainsFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContainsFold(FieldThemeKey, v))
}

// SceneSlotKeyEQ applies the EQ predicate on the "scene_slot_key" field.
func SceneSlotKeyEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldSceneSlotKey, v))
}

// SceneSlotKeyNEQ applies the NEQ predicate on the "scene_slot_key" field.
func SceneSlotKeyNEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldSceneSlotKey, v))
}

// SceneSlotKeyIn applies the In predicate on the "scene_slot_key" field.
func SceneSlotKeyIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldSceneSlotKey, vs...))
}

// SceneSlotKeyNotIn applies the NotIn predicate on the "scene_slot_key" field.
func SceneSlotKeyNotIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldSceneSlotKey, vs...))
}

// SceneSlotKeyGT applies the GT predicate on the "scene_slot_key" field.
func SceneSlotKeyGT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldSceneSlotKey, v))
}

// SceneSlotKeyGTE applies the GTE predicate on the "scene_slot_key" field.
func SceneSlotKeyGTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldSceneSlotKey, v))
}

// SceneSlotKeyLT applies the LT predicate on the "scene_slot_key" field.
func SceneSlotKeyLT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldSceneSlotKey, v))
}

// SceneSlotKeyLTE applies the LTE predicate on the "scene_slot_key" field.
func SceneSlotKeyLTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldSceneSlotKey, v))
}

// SceneSlotKeyContains applies the Contains predicate on the "scene_slot_key" field.
func SceneSlotKeyContains(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContains(FieldSceneSlotKey, v))
}

// SceneSlotKeyHasPrefix applies the HasPrefix predicate on the "scene_slot_key" field.
func SceneSlotKeyHasPrefix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasPrefix(FieldSceneSlotKey, v))
}

// SceneSlotKeyHasSuffix applies the HasSuffix predicate on the "scene_slot_key" field.
func SceneSlotKeyHasSuffix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasSuffix(FieldSceneSlotKey, v))
}

// SceneSlotKeyEqualFold applies the EqualFold predicate on the "scene_slot_key" field.
func SceneSlotKeyEqualFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEqualFold(FieldSceneSlotKey, v))
}

// SceneSlotKeyContainsFold applies the ContainsFold predicate on the "scene_slot_key" field.
func SceneSlotKeyContainsFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContainsFold(FieldSceneSlotKey, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldContainsFold(FieldStatus, v))
}

// FeaturedEQ applies the EQ predicate on the "featured" field.
func FeaturedEQ(v bool) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldFeatured, v))
}

// FeaturedNEQ applies the NEQ predicate on the "featured" field.
func FeaturedNEQ(v bool) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldFeatured, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.CafeRoom {
	return predicate.CafeRoom(sql.FieldLTE(FieldSortOrder, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.GroupBuyPlan) predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccount applies the HasEdge predicate on the "account" edge.
func HasAccount() predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountTable, AccountColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountWith applies the HasEdge predicate on the "account" edge with a given conditions (other predicates).
func HasAccountWith(preds ...predicate.Account) predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := newAccountStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRounds applies the HasEdge predicate on the "rounds" edge.
func HasRounds() predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, RoundsTable, RoundsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoundsWith applies the HasEdge predicate on the "rounds" edge with a given conditions (other predicates).
func HasRoundsWith(preds ...predicate.GroupBuyRound) predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := newRoundsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountBindings applies the HasEdge predicate on the "account_bindings" edge.
func HasAccountBindings() predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountBindingsTable, AccountBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountBindingsWith applies the HasEdge predicate on the "account_bindings" edge with a given conditions (other predicates).
func HasAccountBindingsWith(preds ...predicate.APIKeyAccountBinding) predicate.CafeRoom {
	return predicate.CafeRoom(func(s *sql.Selector) {
		step := newAccountBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CafeRoom) predicate.CafeRoom {
	return predicate.CafeRoom(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CafeRoom) predicate.CafeRoom {
	return predicate.CafeRoom(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CafeRoom) predicate.CafeRoom {
	return predicate.CafeRoom(sql.NotPredicates(p))
}
