import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const registerView = readFileSync(resolve(process.cwd(), 'src/views/auth/RegisterView.vue'), 'utf8')
const loginView = readFileSync(resolve(process.cwd(), 'src/views/auth/LoginView.vue'), 'utf8')
const homeView = readFileSync(resolve(process.cwd(), 'src/views/HomeView.vue'), 'utf8')
const router = readFileSync(resolve(process.cwd(), 'src/router/index.ts'), 'utf8')
const authAccessPanel = readFileSync(resolve(process.cwd(), 'src/components/auth/AuthAccessPanel.vue'), 'utf8')
const authLayout = readFileSync(resolve(process.cwd(), 'src/components/layout/AuthLayout.vue'), 'utf8')

describe('auth page visual direction', () => {
  it('embeds login and register inside the warm public homepage shell', () => {
    expect(router).toMatch(/path: '\/login'[\s\S]*?import\('@\/views\/HomeView\.vue'\)/)
    expect(router).toContain("props: { authMode: 'login' }")
    expect(router).toMatch(/path: '\/register'[\s\S]*?import\('@\/views\/HomeView\.vue'\)/)
    expect(router).toContain("props: { authMode: 'register' }")
    expect(homeView).toContain("import AuthAccessPanel from '@/components/auth/AuthAccessPanel.vue'")
    expect(homeView).toContain('<AuthAccessPanel')
    expect(homeView).toContain(':initial-mode="authMode"')
    expect(homeView).toContain('route.path === \'/home\' && !!homeContent.value')
    expect(authAccessPanel).toContain("import LoginView from '@/views/auth/LoginView.vue'")
    expect(authAccessPanel).toContain("import RegisterView from '@/views/auth/RegisterView.vue'")
    expect(authAccessPanel).toContain('class="auth-access-panel"')
    expect(authAccessPanel).toContain('class="auth-access-heading"')
    expect(authAccessPanel).toContain('class="auth-access-title"')
    expect(authAccessPanel).toContain('class="auth-access-body"')
    expect(authAccessPanel).toContain('panelTitle')
    expect(authAccessPanel).toContain('auth.accessLoginTitle')
    expect(authAccessPanel).toContain('auth.accessRegisterTitle')
    expect(authAccessPanel).toContain("activeMode === 'register'")
    expect(authAccessPanel).toContain("activeMode === 'login'")
    expect(authAccessPanel).toContain('class="auth-access-terms"')
    expect(authAccessPanel).toContain('login_agreement_documents')
    expect(authAccessPanel).toContain("name: 'LegalDocument'")
    expect(authAccessPanel).toContain('background: #141413')
    expect(authAccessPanel).toContain('min-height: 31rem')
    expect(authAccessPanel).toContain('min-height: 15.75rem')
  })

  it('uses the warm light auth form treatment instead of the old dark glass panel', () => {
    expect(registerView).toContain('embedded ? \'div\' : AuthLayout')
    expect(loginView).toContain('embedded ? \'div\' : AuthLayout')
    expect(registerView).toContain('text-2xl font-bold text-[#141413]')
    expect(loginView).toContain('text-2xl font-bold text-[#141413]')
    expect(loginView).toContain('class="auth-submit-button w-full"')
    expect(registerView).toContain('class="auth-submit-button w-full"')
    expect(loginView).toContain('class="auth-input pl-11"')
    expect(registerView).toContain('class="auth-input pl-11"')
    expect(loginView).toContain(':autofocus="!embedded"')
    expect(registerView).toContain(':autofocus="!embedded"')
    expect(loginView).not.toContain('\n              autofocus\n')
    expect(registerView).not.toContain('\n              autofocus\n')
    expect(loginView).toContain('class="auth-input pl-11 pr-11"')
    expect(registerView).toContain('class="auth-input pl-11 pr-11"')
    expect(registerView).toContain('class="auth-input pl-11 pr-10"')
    expect(registerView).toContain('auth-input-label')
    expect(registerView).toContain('auth-input-hint')
    expect(registerView).not.toContain('class="input pl-11"')
    expect(registerView).not.toContain('class="input pl-11 pr-11"')
    expect(registerView).not.toContain('class="input pl-11 pr-10"')
    expect(registerView).not.toContain('class="btn btn-primary w-full"')
    expect(loginView).toContain('background: #141413')
    expect(registerView).toContain('border-radius: 999px')
    expect(authLayout).toContain('linear-gradient(180deg, #faf9f5 0%, #f5f0e8 54%, #efe9de 100%)')
    expect(authLayout).toContain('border-radius: 22px')
    expect(authLayout).not.toContain('#120b35')
    expect(registerView).not.toContain('text-sm font-medium text-violet-100/74')
    expect(loginView).not.toContain('text-violet-100/72')
  })

  it('places configured OAuth providers before email forms in embedded auth cards', () => {
    expect(loginView).toContain('class="auth-oauth-first space-y-3"')
    expect(registerView).toContain('class="auth-oauth-first space-y-3"')
    expect(loginView.indexOf('class="auth-oauth-first space-y-3"')).toBeLessThan(
      loginView.indexOf('<!-- Email Input -->')
    )
    expect(registerView.indexOf('class="auth-oauth-first space-y-3"')).toBeLessThan(
      registerView.indexOf('<!-- Registration Disabled Message -->')
    )
    expect(loginView).toContain(':github-enabled="githubOAuthEnabled"')
    expect(registerView).toContain(':github-enabled="githubOAuthEnabled"')
    expect(loginView).not.toMatch(/<EmailOAuthButtons[\s\S]*?<\/form>[\s\S]*?<EmailOAuthButtons/)
    expect(registerView).not.toMatch(/<EmailOAuthButtons[\s\S]*?<\/form>[\s\S]*?<EmailOAuthButtons/)
  })

  it('defaults login agreement checkboxes to accepted on login and register pages', () => {
    const expectedDefault = "loginAgreementMode.value === 'checkbox'"

    expect(loginView).toContain(expectedDefault)
    expect(registerView).toContain(expectedDefault)
  })
})
