import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import zhMessages from '../i18n/locales/zh'

const homeView = readFileSync(resolve(process.cwd(), 'src/views/HomeView.vue'), 'utf8')
const publicTopNav = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicTopNav.vue'), 'utf8')
const revealBackdrop = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicRevealBackdrop.vue'), 'utf8')
const publicCss = readFileSync(resolve(process.cwd(), 'src/views/public/public-page.css'), 'utf8')
const adminSettingsView = readFileSync(resolve(process.cwd(), 'src/views/admin/SettingsView.vue'), 'utf8')
const adminSettingsApi = readFileSync(resolve(process.cwd(), 'src/api/admin/settings.ts'), 'utf8')
const mainEntry = readFileSync(resolve(process.cwd(), 'src/main.ts'), 'utf8')
const pixelUi = readFileSync(resolve(process.cwd(), 'src/styles/pixel-ui.css'), 'utf8')

describe('home page visual direction', () => {
  it('uses MiMo-inspired developer workspace hero copy', () => {
    expect(zhMessages.home.heroTitleTop).toBe('AI Coding')
    expect(zhMessages.home.heroTitleBottom).toBe('一站式大模型服务')
    expect(zhMessages.home.heroDescription).toBe('一个兼容 OpenAI 的入口网址，把模型调用、密钥接入和用量记录收进同一个轻量工作流。')
    expect(zhMessages.home.heroProductTitle).toBe('把 AI 接入变成一条清晰路径')
    expect(zhMessages.home.heroGatewayConsole).toBe('API 工作台')
    expect(zhMessages.home.apiEntryLabel).toBe('API 入口')
    expect(zhMessages.home.apiEntryAriaLabel).toBe('兼容 OpenAI 的 API 入口网址')
    expect(zhMessages.home.heroProofGateway).toBe('统一 API 网关')
    expect(zhMessages.home.heroProofBilling).toBe('倍率账单')
    expect(zhMessages.home.features.unifiedGateway).toBe('统一接入')
    expect(zhMessages.home.claimButton).toBe('注册领取试用')
    expect(zhMessages.home.quickStartButton).toBe('快速开始')
    expect(zhMessages.home.goToDashboard).toBe('前往仪表盘')
    expect(zhMessages.home.accountWorkbench.title).toBe('账号工作台')
    expect(zhMessages.home.accountWorkbench.currentBalance).toBe('当前余额')
    expect(zhMessages.home.accountWorkbench.totalTokens).toBe('总 Token')
    expect(zhMessages.home.accountWorkbench.totalRequests).toBe('总请求数')
    expect(zhMessages.home.accountWorkbench.totalCost).toBe('总花费')
    expect(zhMessages.home.accountWorkbench.rechargeBalance).toBe('充值余额')
    expect(zhMessages.home.gatewayExplain.kicker).toBe('什么是统一模型网关')
    expect(zhMessages.home.gatewayExplain.title).toBe('一个入口，连接多种模型与账号池。')
    expect(zhMessages.home.gatewayExplain.description).toContain('兼容 OpenAI 的 API 地址')
    expect(zhMessages.home.gatewayExplain.description).not.toContain('FreeModel')
    expect(zhMessages.home.modelCarousel.kicker).toBe('模型接入范围')
    expect(zhMessages.home.modelCarousel.title).toBe('提供众多顶级优质大模型')
    expect(zhMessages.home.modelCarousel.highlight).toBe('')
    expect(zhMessages.home.modelCarousel.description).toContain('同一个入口和账号池策略')
    expect(homeView).toContain('v-if="isAuthenticated" :to="dashboardPath"')
    expect(homeView).toContain('@click="openAuthPanel"')
  })

  it('keeps custom homepage rendering separate from the default MiMo page', () => {
    expect(homeView).toContain('v-if="shouldRenderCustomHomeContent"')
    expect(homeView).toContain("route.path === '/home' && !!homeContent.value")
    expect(homeView).toContain('v-if="isHomeContentUrl"')
    expect(homeView).toContain('v-else v-html="homeContent"')
    expect(homeView).toContain('v-else class="home-page-root home-mimo-bg')
    expect(homeView).toContain('<main class="home-main-stage relative z-10 overflow-hidden px-4 sm:px-6">')
    expect(homeView).toContain('<PublicRevealBackdrop variant="hero" />')
  })

  it('keeps the MiMo-style hero with an embedded auth panel and Claude cream tokens', () => {
    expect(homeView).toContain('home-mimo-bg')
    expect(homeView).toContain('home-mimo-hero')
    expect(homeView).toContain('home-mimo-title')
    expect(homeView).toContain('<span class="home-mimo-title-line">{{ heroTitleTop }}</span>')
    expect(homeView).toContain('home-mimo-title-line home-mimo-title-line-sweep')
    expect(homeView).toContain(':data-title="heroTitleBottom"')
    expect(homeView).toContain("import AuthAccessPanel from '@/components/auth/AuthAccessPanel.vue'")
    expect(homeView).toContain('<AuthAccessPanel')
    expect(homeView).toContain('v-if="!isAuthenticated"')
    expect(homeView).toContain(':initial-mode="authMode"')
    expect(homeView).toContain('v-else class="home-account-workbench"')
    expect(homeView).not.toContain("t('home.accountWorkbench.title')")
    expect(homeView).not.toContain("t('home.accountWorkbench.description')")
    expect(homeView).not.toContain('home-account-workbench-kicker')
    expect(homeView).toContain("t('home.accountWorkbench.currentBalance')")
    expect(homeView).toContain('home-account-user-chip')
    expect(homeView).toContain('accountWorkbenchUserName')
    expect(homeView).toContain('authStore.user?.username?.trim()')
    expect(homeView).toContain('authStore.user?.email?.trim()')
    expect(homeView).toContain('accountWorkbenchCards')
    expect(homeView).toContain('<router-link to="/purchase" class="home-account-workbench-link">')
    expect(homeView).toContain("t('home.accountWorkbench.rechargeBalance')")
    expect(homeView).not.toContain('<router-link :to="dashboardPath" class="home-account-workbench-link">')
    expect(homeView).toContain('usageAPI.getDashboardStats()')
    expect(homeView).toContain('authStore.user?.balance')
    expect(homeView).toContain('formatHomeCredit(stats?.total_actual_cost ?? 0)')
    expect(homeView).toContain('maximumFractionDigits: 2')
    expect(homeView).toContain('formatHomeNumber(stats?.total_tokens ?? 0)')
    expect(homeView).toContain('formatHomeNumber(stats?.total_requests ?? 0)')
    expect(homeView).toContain("import { usageAPI, type UserDashboardStats } from '@/api/usage'")
    expect(homeView).toContain("import { formatCreditAmount } from '@/utils/credits'")
    expect(homeView).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
    expect(homeView).toContain('grid-template-columns: 1fr')
    expect(homeView).toContain('grid-template-columns: minmax(0, 1fr) minmax(21rem, 28rem)')
    expect(homeView).toContain('text-align: left')
    expect(homeView).not.toContain(':data-title="heroHeadline"')
    expect(homeView).not.toContain('.home-mimo-title::after')
    expect(homeView).toContain('.home-mimo-title-line-sweep::after')
    expect(homeView).toContain('content: attr(data-title)')
    expect(homeView).toContain('@keyframes home-title-light-sweep')
    expect(homeView).toContain('animation: home-title-light-sweep 10s')
    expect(homeView).toContain('background-clip: text')
    expect(homeView).toContain('-webkit-text-fill-color: transparent')
    expect(homeView).toContain('rgba(255, 248, 235, 0.98)')
    expect(homeView).toContain('rgba(255, 255, 255, 0.92)')
    expect(homeView).toContain('drop-shadow(0 0 18px rgba(204, 120, 92, 0.18))')
    expect(homeView).not.toContain('home-mimo-kicker')
    expect(homeView).not.toContain("t('home.heroEyebrow')")
    expect(homeView).toContain('z-index: 1')
    expect(homeView).toContain('heroHeadline')
    expect(homeView).toContain('heroDescriptionText')
    expect(homeView).toContain('heroDescriptionTexts')
    expect(homeView).toContain('defaultHeroDescriptionTexts')
    expect(homeView).toContain('activeHeroDescriptionIndex')
    expect(homeView).toContain('startHeroDescriptionCarousel')
    expect(homeView).toContain('<Transition name="home-subtitle-slide" mode="out-in">')
    expect(homeView).toContain('home-mimo-description-text')
    expect(homeView).not.toContain('aria-live="polite"')
    expect(homeView).toContain("import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'")
    expect(homeView).toContain('window.setInterval(() =>')
    expect(homeView).toContain('}, 3600)')
    expect(homeView).toContain('window.clearInterval(heroDescriptionTimer)')
    expect(homeView).toContain('home-command-pill')
    expect(homeView).toContain('@click="copyApiEntryUrl"')
    expect(homeView).toContain("apiEntryCopied ? 'check' : 'copy'")
    expect(homeView).toContain("import { useClipboard } from '@/composables/useClipboard'")
    expect(homeView).toContain("t('home.apiEntryLabel')")
    expect(homeView).toContain('publicApiEntryUrl')
    expect(homeView).toContain('resolvePublicApiEntryUrl')
    expect(homeView).toContain('appStore.cachedPublicSettings?.api_base_url || appStore.apiBaseUrl')
    expect(homeView).not.toContain('BASE_URL')
    expect(homeView).not.toContain('/v1/chat/completions')
    expect(homeView).toContain('home-mimo-actions')
    expect(homeView).toContain('home-trust-signals')
    expect(homeView).toContain("t('home.trustSignals.compatible')")
    expect(homeView).toContain("import Icon from '@/components/icons/Icon.vue'")
    expect(homeView).toContain('<Icon name="arrowRight" size="sm" class="home-button-icon" aria-hidden="true" />')
    expect(homeView).toContain('.home-button-icon')
    expect(homeView).toContain('transform: translateX(2px)')
    expect(homeView).toContain('border-color: #141413')
    expect(homeView).toContain('background: #141413')
    expect(homeView).toContain('to="/tutorial/getting-started"')
    expect(homeView).toContain("t('home.quickStartButton')")
    expect(homeView).not.toContain('<router-link to="/tutorial" class="home-action-button">')
    expect(homeView).not.toContain('<router-link to="/models" class="home-action-button">')
    expect(homeView).not.toContain('home-mimo-proof')
    expect(homeView).not.toContain('heroProofCards')
    expect(homeView).not.toContain('home-typewriter')
    expect(homeView).not.toContain('home-typewriter-cursor')
    expect(homeView).not.toContain('typedHeroDescription')
    expect(homeView).toContain("from './public/components/PublicRevealBackdrop.vue'")
    expect(homeView).toContain('#faf9f5')
    expect(homeView).toContain('#141413')
    expect(homeView).toContain('#6c6a64')
    expect(homeView).toContain('#cc785c')
    expect(homeView).toContain('#e6dfd8')
    expect(publicCss).toContain('--public-font-sans: Inter, "Noto Sans SC", "Source Han Sans SC"')
    expect(publicCss).toContain('--public-font-mono: "JetBrains Mono"')
    expect(homeView).toContain('font-family: var(--public-font-sans)')
    expect(homeView).toContain('font-weight: 400')
    expect(homeView).toContain('font-family: var(--public-font-mono)')
    expect(homeView).not.toContain('home-saas-bg')
    expect(homeView).not.toContain('home-light-grid')
    expect(homeView).not.toContain('home-command-hero')
    expect(homeView).not.toContain('home-command-preview')
    expect(homeView).not.toContain('home-command-toolbar')
    expect(homeView).not.toContain('home-command-flow')
    expect(homeView).not.toContain('.home-account-workbench::before')
    expect(homeView).not.toContain('gatewayFlow')
    expect(homeView).not.toContain('heroStats')
    expect(homeView).not.toContain('home-product-band')
    expect(homeView).not.toContain('home-market-panel')
    expect(homeView).not.toContain('home-integrate-panel')
    expect(homeView).not.toContain('home-provider-strip')
    expect(homeView).not.toContain('FreeModel')
    expect(homeView).not.toContain('#08241a')
    expect(homeView).not.toContain('#216d51')
    expect(homeView).not.toContain('#14533c')
  })

  it('adds a second-screen gateway explanation without copying the reference brand', () => {
    expect(homeView).toContain('home-gateway-section')
    expect(homeView).toContain("t('home.gatewayExplain.ariaLabel')")
    expect(homeView).toContain("t('home.gatewayExplain.kicker')")
    expect(homeView).toContain("t('home.gatewayExplain.title')")
    expect(homeView).toContain("t('home.gatewayExplain.description')")
    expect(homeView).toContain('home-gateway-visual')
    expect(homeView).toContain('home-gateway-art')
    expect(homeView).toContain('/public/gateway-network-art.webp')
    expect(homeView).toContain('home-gateway-label')
    expect(homeView).toContain('home-gateway-label-models')
    expect(homeView).toContain('home-gateway-label-entry')
    expect(homeView).toContain('home-gateway-label-accounts')
    expect(homeView).toContain('loading="eager"')
    expect(homeView).toContain('gatewayModels')
    expect(homeView).toContain('Claude')
    expect(homeView).toContain('DeepSeek')
    expect(homeView).toContain("gatewayModels.join(' / ')")
    expect(zhMessages.home.gatewayExplain.gatewayName).toBe('API Gateway')
    expect(zhMessages.home.gatewayExplain.accountPoolName).toBe('Account Pool')
    expect(zhMessages.home.gatewayExplain.poolName).toBe('Model Pool')
    expect(homeView).toContain('aspect-ratio: 1536 / 840')
    expect(homeView).toContain('backdrop-filter: blur(16px) saturate(1.08)')
    expect(homeView).toContain('object-fit: cover')
    expect(homeView).toContain('object-position: center')
    expect(homeView).toContain('.home-gateway-visual::after')
    expect(homeView).toContain('aspect-ratio: 1536 / 1024')
    expect(homeView).toContain('min-height: 100svh')
    expect(homeView).toContain('background: #f3f0ea')
    expect(homeView).not.toContain('home-gateway-lines')
    expect(homeView).not.toContain('home-gateway-node-main')
    expect(homeView).not.toContain('home-model-row')
    expect(homeView).not.toContain('与其押注单一厂商')
    expect(homeView).not.toContain('封装成一个 API')
    expect(homeView).not.toContain('FREEMODEL')
    expect(homeView).not.toContain('FreeModel')
  })

  it('adds a half-screen EasyRouter-inspired model icon carousel without copying the brand', () => {
    expect(homeView).toContain('home-model-carousel-section')
    expect(homeView).toContain("t('home.modelCarousel.ariaLabel')")
    expect(homeView).toContain("t('home.modelCarousel.kicker')")
    expect(homeView).toContain("t('home.modelCarousel.title')")
    expect(homeView).not.toContain("t('home.modelCarousel.highlight')")
    expect(homeView).toContain("t('home.modelCarousel.description')")
    expect(homeView).toContain('home-model-carousel-panel')
    expect(homeView).toContain('home-model-carousel-window')
    expect(homeView).toContain('home-model-carousel-track')
    expect(homeView).toContain('home-model-carousel-set')
    expect(homeView).toContain('home-model-carousel-tile')
    expect(homeView).toContain('modelCarouselRows')
    expect(homeView).toContain('ModelCarouselItem')
    expect(homeView).toContain("import ModelIcon from '@/components/common/ModelIcon.vue'")
    expect(homeView).toContain('<ModelIcon :model="item.model" size="32px" />')
    expect(homeView).toContain('claude-sonnet-4-5')
    expect(homeView).toContain('gpt-5.1')
    expect(homeView).toContain('gemini-3-pro-preview')
    expect(homeView).toContain('qwen3-max')
    expect(homeView).toContain('deepseek-v3.2')
    expect(homeView).toContain('mistral-large-latest')
    expect(homeView).toContain('openrouter-auto')
    expect(homeView).toContain('animation: home-model-marquee 34s linear infinite')
    expect(homeView).toContain('animation-direction: reverse')
    expect(homeView).toContain('@keyframes home-model-marquee')
    expect(homeView).toContain('@media (prefers-reduced-motion: reduce)')
    expect(homeView).toContain('linear-gradient(90deg, #e6e1d7')
    expect(homeView).toContain('linear-gradient(270deg, #e6e1d7')
    expect(homeView).toContain('max-width: 62rem')
    expect(homeView).toContain('max-width: 74rem')
    expect(homeView).toContain('min-height: 50svh')
    expect(homeView).toContain('align-items: center')
    expect(homeView).toContain('padding-top: clamp(3rem, 6vh, 4.6rem)')
    expect(homeView).toContain('padding-bottom: clamp(3.4rem, 7vh, 5.2rem)')
    expect(homeView).not.toContain('easyrouter')
    expect(homeView).not.toContain('EasyRouter')
  })

  it('adds bottom FAQ and final start CTA sections inspired by the reference structure', () => {
    expect(homeView).toContain('home-faq-section')
    expect(homeView).toContain("t('home.faq.ariaLabel')")
    expect(homeView).toContain("t('home.faq.kicker')")
    expect(homeView).toContain("t('home.faq.title')")
    expect(homeView).toContain("t('home.faq.description')")
    expect(homeView).toContain('home-faq-tabs')
    expect(homeView).toContain('home-faq-tab')
    expect(homeView).toContain('home-faq-list')
    expect(homeView).toContain('home-faq-item')
    expect(homeView).toContain('home-faq-question-row')
    expect(homeView).toContain('home-faq-answer')
    expect(homeView).toContain('faqTabs')
    expect(homeView).toContain('faqItems')
    expect(homeView).toContain('computed<HomeFaqItem[]>')
    expect(homeView).toContain("import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'")
    expect(homeView).toContain('const activeFaqIndex = ref(0)')
    expect(homeView).toContain(':aria-expanded="activeFaqIndex === index"')
    expect(homeView).toContain('@click="activeFaqIndex = activeFaqIndex === index ? -1 : index"')
    expect(homeView).toContain('home-final-cta-section')
    expect(homeView).toContain('home-final-cta-card')
    expect(homeView).toContain("t('home.finalCta.ariaLabel')")
    expect(homeView).toContain("t('home.finalCta.kicker')")
    expect(homeView).toContain("t('home.finalCta.title')")
    expect(homeView).toContain("t('home.finalCta.description')")
    expect(homeView).toContain('home-final-cta-button')
    expect(homeView).toContain('v-if="isAuthenticated" :to="dashboardPath" class="home-final-cta-button"')
    expect(homeView).toContain('<button v-else type="button" class="home-final-cta-button" @click="openAuthPanel">')
    expect(homeView).toContain('background: #f5f0e8')
    expect(homeView).toContain('border-radius: 28px')
    expect(homeView).toContain('background: #cc785c')
    expect(zhMessages.home.faq.kicker).toBe('FAQ 常见问题')
    expect(zhMessages.home.faq.title).toBe('常见问题解答')
    expect(zhMessages.home.faq.description).toContain('接入、计费、模型和账号池')
    expect(zhMessages.home.faq.tabs.service).toBe('关于服务')
    expect(zhMessages.home.faq.tabs.billing).toBe('价格与计费')
    expect(zhMessages.home.faq.tabs.usage).toBe('接入与使用')
    expect(zhMessages.home.faq.items).toHaveLength(4)
    expect(zhMessages.home.faq.items[0].question).toBe('这是官方平台吗？')
    expect(zhMessages.home.faq.items[1].answer).toContain('Base URL 和 API Key')
    expect(zhMessages.home.faq.items[2].answer).toContain('模型广场')
    expect(zhMessages.home.faq.items[3].answer).toContain('统一入口')
    expect(zhMessages.home.finalCta.title).toBe('开始使用')
    expect(zhMessages.home.finalCta.button).toBe('注册领取试用')
    expect(homeView).not.toContain('Start free now')
    expect(homeView).not.toContain('EasyRouter')
  })

  it('implements the desktop canvas reveal mask and disables it for mobile or reduced motion', () => {
    expect(revealBackdrop).toContain('PublicRevealBackdrop')
    expect(revealBackdrop).toContain('mimo-relief-bg.webp')
    expect(revealBackdrop).toContain('<canvas ref="canvasRef" class="public-reveal-mask"></canvas>')
    expect(revealBackdrop).toContain("window.matchMedia('(hover: hover) and (pointer: fine)')")
    expect(revealBackdrop).toContain("window.matchMedia('(prefers-reduced-motion: reduce)')")
    expect(revealBackdrop).toContain("ctx.globalCompositeOperation = 'destination-out'")
    expect(revealBackdrop).toContain('refillTimer')
    expect(revealBackdrop).toContain('revealFrame')
    expect(revealBackdrop).toContain('pendingPoint')
    expect(revealBackdrop).toContain('targetPoint')
    expect(revealBackdrop).toContain('easedPoint')
    expect(revealBackdrop).toContain('lastTrailPoint')
    expect(revealBackdrop).toContain('trailFrame')
    expect(revealBackdrop).toContain('type RevealRipple')
    expect(revealBackdrop).toContain('const ripples: RevealRipple[] = []')
    expect(revealBackdrop).toContain("return variant.value === 'hero' ? 820 : 340")
    expect(revealBackdrop).toContain("return variant.value === 'hero' ? 220 : 140")
    expect(revealBackdrop).toContain('function easeOutQuad')
    expect(revealBackdrop).toContain('grow: revealGrowDuration()')
    expect(revealBackdrop).toContain("const maxRipples = variant.value === 'hero' ? 52 : 16")
    expect(revealBackdrop).toContain("const spacing = variant.value === 'hero' ? 6 : 5")
    expect(revealBackdrop).toContain('const steps = !lastTrailPoint ? 1 : Math.min(8, Math.max(1, Math.floor(distance / spacing)))')
    expect(revealBackdrop).toContain('function addRipple')
    expect(revealBackdrop).toContain('function renderRipples')
    expect(revealBackdrop).toContain('function startTrailLoop')
    expect(revealBackdrop).toContain('function runTrailFrame')
    expect(revealBackdrop).toContain('easedPoint.x += (targetPoint.x - easedPoint.x) * easing')
    expect(revealBackdrop).toContain('const remaining = 1 - progress')
    expect(revealBackdrop).toContain('const growProgress = Math.min(ripple.age / ripple.grow, 1)')
    expect(revealBackdrop).toContain('const growEase = easeOutQuad(growProgress)')
    expect(revealBackdrop).toContain("const strength = Math.pow(remaining, variant.value === 'hero' ? 0.82 : 1.1) * (0.34 + growEase * 0.66)")
    expect(revealBackdrop).toContain("const shrinkRadius = 0.08 + Math.pow(remaining, variant.value === 'hero' ? 1.35 : 1.95) * 0.92")
    expect(revealBackdrop).toContain('const growRadius = 0.14 + growEase * 0.86')
    expect(revealBackdrop).toContain('const radius = ripple.radius * shrinkRadius * growRadius')
    expect(revealBackdrop).toContain('window.requestAnimationFrame(() =>')
    expect(revealBackdrop).toContain('window.setTimeout(softlyRefillMask')
    expect(revealBackdrop).toContain("const baseAlpha = variant.value === 'hero' ? 0.88 : 1")
    expect(revealBackdrop).toContain('variant.value === \'hero\' ? 218 : 112')
    expect(revealBackdrop).toContain('variant.value === \'hero\' ? 320 : 220')
    expect(revealBackdrop).not.toContain('const totalSteps = variant.value === \'hero\' ? 9 : 12')
    expect(revealBackdrop).not.toContain('drawReveal(point.x, point.y, strength)')
    expect(revealBackdrop).toContain('fillMask()')
    expect(revealBackdrop).toContain('ctx.clearRect(0, 0, canvas.width, canvas.height)')
    expect(revealBackdrop).toContain("window.addEventListener('pointermove', handlePointerMove")
    expect(revealBackdrop).toContain("document.addEventListener('pointerleave', handlePointerLeave)")
    expect(revealBackdrop).toContain('@media (max-width: 768px), (hover: none), (pointer: coarse), (prefers-reduced-motion: reduce)')
    expect(revealBackdrop).toContain('.public-reveal-backdrop.is-hero .public-reveal-image')
    expect(revealBackdrop).toContain('inset: 0')
    expect(revealBackdrop).toContain('height: 100%')
    expect(revealBackdrop).toContain('background-position: center center')
    expect(revealBackdrop).toContain('background-size: cover')
    expect(revealBackdrop).not.toContain('background-size: min(2048px, max(100vw, 90rem)) auto')
    expect(revealBackdrop).not.toContain('height: 18rem')
    expect(revealBackdrop).not.toContain('background-size: 48rem auto')
    expect(revealBackdrop).toContain('.public-reveal-backdrop.is-hero.is-static .public-reveal-image')
    expect(revealBackdrop).toContain('opacity: 0.12')
    expect(revealBackdrop).not.toContain('mask-composite: intersect')
    expect(revealBackdrop).not.toContain('mask-image: linear-gradient(180deg')
    expect(revealBackdrop).not.toContain('linear-gradient(90deg')
    expect(revealBackdrop).toContain('.public-reveal-mask')
    expect(revealBackdrop).toContain('display: none')
    expect(revealBackdrop).toContain('background: #faf9f5')
  })

  it('uses Claude-inspired tokens in shared public CSS', () => {
    expect(publicCss).toContain('--public-bg: #faf9f5')
    expect(publicCss).toContain('--public-bg-soft: #f5f0e8')
    expect(publicCss).toContain('--public-bg-muted: #efe9de')
    expect(publicCss).toContain('--public-text: #141413')
    expect(publicCss).toContain('--public-body: #3d3d3a')
    expect(publicCss).toContain('--public-muted: #6c6a64')
    expect(publicCss).toContain('--public-muted-soft: #8e8b82')
    expect(publicCss).toContain('--public-border-strong: #d8cec2')
    expect(publicCss).toContain('--public-accent: #cc785c')
    expect(publicCss).toContain('--public-accent-strong: #a9583e')
    expect(publicCss).toContain('--public-dark: #181715')
    expect(publicCss).toContain('--public-success: #5db872')
    expect(publicCss).toContain('--public-nav-height: 3.75rem')
    expect(publicCss).toContain('padding-top: var(--public-nav-height)')
    expect(publicCss).toContain('--public-nav-height: 6.4rem')
    expect(publicCss).toContain('--public-font-display: var(--public-font-sans)')
    expect(publicCss).not.toContain('EB Garamond')
    expect(publicCss).not.toContain('Noto Serif SC')
    expect(publicCss).not.toContain('Source Han Serif SC')
    expect(publicCss).not.toContain('--public-bg-soft: #f7faf8')
    expect(publicCss).not.toContain('--public-accent: #216d51')
  })

  it('does not render the old fixed homepage support shortcut', () => {
    expect(homeView).not.toContain('contactInfo')
    expect(homeView).not.toContain('supportHref')
    expect(homeView).not.toContain('home-support-button')
    expect(homeView).not.toContain("['http:', 'https:', 'mailto:', 'tel:']")
    expect(zhMessages.home.contactSupport).toBe('添加客服')
  })

  it('exposes homepage hero copy in system settings', () => {
    expect(adminSettingsView).toContain('v-model="form.home_hero_title_top"')
    expect(adminSettingsView).toContain('v-model="form.home_hero_title_bottom"')
    expect(adminSettingsView).toContain('v-model="form.home_hero_subtitles"')
    expect(adminSettingsView).toContain('home_hero_title_top: form.home_hero_title_top')
    expect(adminSettingsView).toContain('home_hero_subtitles: form.home_hero_subtitles')
    expect(adminSettingsApi).toContain('home_hero_title_top: string;')
    expect(adminSettingsApi).toContain('home_hero_subtitles?: string;')
  })

  it('uses the lightweight MiMo top navigation treatment with Claude accent color', () => {
    expect(homeView).toContain('<PublicTopNav />')
    expect(homeView).toContain("from './public/components/PublicTopNav.vue'")
    expect(publicTopNav).toContain('public-top-shell')
    expect(publicTopNav).toContain('public-top-nav')
    expect(publicTopNav).toContain('public-nav-center')
    expect(publicTopNav).toContain('public-mobile-nav')
    expect(publicTopNav).toContain('public-nav-link')
    expect(publicTopNav).toContain('public-auth-button')
    expect(publicTopNav).not.toContain('public-auth-link')
    expect(publicTopNav).not.toContain('public-nav-button')
    expect(publicTopNav).not.toContain("isAuthenticated ? dashboardPath : '/login'")
    expect(publicTopNav).not.toContain("isAuthenticated ? t('home.dashboard') : t('home.login')")
    expect(publicTopNav).toContain("t('home.navHome')")
    expect(publicTopNav).toContain("t('home.navTutorial')")
    expect(publicTopNav).toContain("t('home.navModels')")
    expect(publicTopNav).toContain("t('home.navContact')")
    expect(publicTopNav).toContain('openSupportPopup')
    expect(publicTopNav).not.toContain('hasSupportButton')
    expect(publicTopNav).not.toContain('hasSupportContent')
    expect(publicTopNav).toContain('navItems = computed<Array<{ to: string; label: string; activePaths: string[] }>>')
    expect(publicTopNav).not.toContain(':name="item.icon"')
    expect(publicTopNav).not.toContain('PixelIconName')
    expect(publicTopNav).not.toContain("from '@/components/icons/PixelIcon.vue'")
    expect(publicTopNav).not.toContain('<PixelIcon')
    expect(publicTopNav).not.toContain('icon:')
    expect(publicTopNav).not.toContain('siteLogo')
    expect(publicTopNav).not.toContain('public-brand-logo')
    expect(publicTopNav).not.toContain('navFeatures')
    expect(publicTopNav).not.toContain('功能特性')
    expect(publicTopNav).not.toContain('#features')
    expect(publicTopNav).toContain("to: '/home'")
    expect(publicTopNav).toContain("to: '/tutorial'")
    expect(publicTopNav).toContain("to: '/models'")
    expect(publicTopNav).toContain('public-locale-switcher')
    expect(publicTopNav).toContain("import { useAppStore, useAuthStore } from '@/stores'")
    expect(publicTopNav).toContain('authStore.isAuthenticated')
    expect(publicTopNav).toContain('showDashboardButton')
    expect(publicTopNav).toContain('v-if="showDashboardButton"')
    expect(publicTopNav).not.toContain('showHomeUserName')
    expect(publicTopNav).not.toContain('homeUserName')
    expect(publicTopNav).not.toContain('public-user-chip')
    expect(publicTopNav).toContain("route.path === '/home' || route.path === '/'")
    expect(publicTopNav).toContain('v-if="!isAuthenticated" to="/login"')
    expect(publicTopNav).toContain("t('home.login')")
    expect(publicTopNav).not.toContain("to=\"/register\"")
    expect(publicTopNav).not.toContain("t('home.claimButton')")
    expect(publicTopNav).toContain("t('home.goToDashboard')")
    expect(publicTopNav).toContain("Icon name=\"arrowRight\"")
    expect(publicTopNav).toContain("Icon name=\"book\"")
    expect(publicTopNav).toContain('background: rgba(250, 249, 245, 0.68)')
    expect(publicTopNav).toContain('position: fixed')
    expect(publicTopNav).toContain('top: 0')
    expect(publicTopNav).toContain('left: 0')
    expect(publicTopNav).toContain('right: 0')
    expect(publicTopNav).toContain('z-index: 80')
    expect(publicTopNav).toContain('backdrop-filter: blur(22px) saturate(1.18)')
    expect(publicTopNav).toContain('-webkit-backdrop-filter: blur(22px) saturate(1.18)')
    expect(publicTopNav).toContain('background: transparent')
    expect(publicTopNav).toContain('0 18px 42px rgba(20, 20, 19, 0.055)')
    expect(publicTopNav).toContain('width: 100%')
    expect(publicTopNav).toContain('<nav class="public-top-nav">')
    expect(publicTopNav).toContain('padding: 0.5rem clamp(1rem, 3.5vw, 3.5rem)')
    expect(publicTopNav).toContain('justify-content: flex-end')
    expect(publicTopNav).toContain('font-family: var(--public-font-sans')
    expect(publicTopNav).toContain('font-weight: 450')
    expect(publicTopNav).not.toContain('toggleTheme')
    expect(publicTopNav).not.toContain('switchToLight')
    expect(publicTopNav).not.toContain('switchToDark')
    expect(publicTopNav).not.toContain('background: #cc785c')
    expect(publicTopNav).not.toContain('background: #a9583e')
    expect(publicTopNav).not.toContain('background: #216d51')
    expect(zhMessages.home.navHome).toBe('首页')
    expect(zhMessages.home.navTutorial).toBe('教程')
    expect(zhMessages.home.navModels).toBe('模型广场')
    expect(zhMessages.home.navContact).toBe('联系客服')
  })

  it('removes the homepage footer model badge strip', () => {
    expect(homeView).not.toContain('home-footer-models')
    expect(homeView).not.toContain('footerModelBadges')
    expect(homeView).not.toContain('home-footer-badge')
    expect(homeView).not.toContain('CHATGPT')
  })

  it('keeps the hero responsive without viewport-scaled font hacks', () => {
    expect(homeView).toContain('home-page-root')
    expect(homeView).toContain('home-main-stage')
    expect(homeView).toContain('home-mimo-hero')
    expect(homeView).toContain('flex: 0 0 auto')
    expect(homeView).toContain('min-height: 100svh')
    expect(homeView).toContain('min-height: min(44rem, calc(82vh - 3.75rem))')
    expect(homeView).toContain('min-height: min(44rem, calc(82svh - 3.75rem))')
    expect(homeView).toContain('min-height: auto')
    expect(homeView).toContain('padding: clamp(3.2rem, 7.2vh, 4.8rem) 0 clamp(3.2rem, 7vh, 4.8rem)')
    expect(homeView).toContain('min-height: 88svh')
    expect(homeView).toContain('min-height: 100svh')
    expect(homeView).toContain('align-items: start')
    expect(homeView).toContain('font-size: 4rem')
    expect(homeView).toContain('font-weight: 760')
    expect(homeView).not.toContain('font-weight: 720')
    expect(homeView).toContain('animation: none')
    expect(homeView).toContain('font-size: 4.45rem')
    expect(homeView).toContain('font-size: 2.55rem')
    expect(homeView).toContain('word-break: keep-all')
    expect(homeView).toContain('letter-spacing: 0')
    expect(homeView).toContain('@media (max-width: 640px)')
    expect(homeView).toContain('@media (min-width: 1536px)')
    expect(homeView).toContain('@media (max-width: 420px)')
    expect(homeView).not.toContain('font-size: clamp(')
    expect(homeView).not.toContain('font-size: calc(')
    expect(homeView).not.toContain('letter-spacing: -')
    expect(homeView).not.toContain('home-feature-strip')
    expect(homeView).not.toContain('home-feature-pill')
    expect(homeView).not.toContain('home-feature-card')
  })

  it('keeps the mobile homepage motion budget low', () => {
    expect(homeView).toContain('@media (max-width: 640px)')
    expect(homeView).toContain('.home-command-pill')
    expect(homeView).not.toContain('.home-mimo-proof')
    expect(homeView).not.toContain('home-typewriter-cursor')
  })

  it('keeps only the requested quick-start link in the primary hero action row', () => {
    expect(homeView).not.toContain('home-secondary-link')
    expect(homeView).toContain('home-action-button')
    expect(homeView).toContain('home-action-button is-secondary')
    expect(homeView).toContain('to="/tutorial/getting-started"')
    expect(homeView).toContain("t('home.quickStartButton')")
    expect(homeView).not.toContain('<router-link to="/tutorial" class="home-action-button">')
    expect(homeView).not.toContain('<router-link to="/models" class="home-action-button">')
    expect(homeView).toContain('home-footer-links')
    expect(homeView).toContain("t('home.docs')")
    expect(homeView).toContain('v-for="doc in footerLegalDocuments"')
    expect(homeView).toContain('toLegalDocumentLink')
    expect(homeView).toContain("name: 'LegalDocument'")
    expect(homeView).toContain('login_agreement_documents')
    expect(homeView).not.toContain('to="/legal/terms"')
    expect(homeView).not.toContain('to="/legal/privacy"')
    expect(homeView).not.toContain('to="/legal/usage-policy"')
  })

  it('keeps mobile auth conversion and FAQ accessibility behavior explicit', () => {
    expect(homeView).toContain("mobileAuthExpanded = ref(route.path === '/login' || route.path === '/register')")
    expect(homeView).toContain("'is-mobile-open': mobileAuthExpanded")
    expect(homeView).toContain('.home-auth-panel:not(.is-mobile-open)')
    expect(homeView).toContain("querySelector<HTMLInputElement>('input:not([type=\"hidden\"]):not(:disabled)')")
    expect(homeView).toContain(':aria-controls="`home-faq-answer-${index}`"')
    expect(homeView).toContain(':id="`home-faq-answer-${index}`"')
    expect(homeView).toContain('home-model-carousel-link')
    expect(homeView).toContain("t('home.modelCarousel.viewAll')")
  })

  it('uses a full-width Xiaomi-style footer strip', () => {
    expect(homeView).toContain('<footer class="home-footer relative z-10">')
    expect(homeView).toContain('width: 100%')
    expect(homeView).toContain('background: #d9d7d2')
    expect(homeView).toContain('padding: clamp(4.2rem, 9vh, 6.2rem)')
    expect(homeView).toContain('width: min(100%, 76rem)')
    expect(homeView).toContain('justify-content: center')
    expect(homeView).toContain('text-decoration: underline')
    expect(homeView).toContain('.home-footer-copy::after')
    expect(homeView).toContain('height: 0.9em')
    expect(homeView).toContain('background: #6c6a64')
    expect(homeView).toContain('.home-footer-links a + a')
    expect(homeView).toContain('border-left: 1px solid #6c6a64')
    expect(homeView).toContain('padding-left: 0.6rem')
    expect(homeView).toContain('white-space: nowrap')
    expect(homeView).toContain('white-space: normal')
    expect(homeView).not.toContain('home-footer relative z-10 mx-auto px-4 pb-8')
  })

  it('keeps pixel icons out of the homepage while using a shared line icon for the CTA arrow', () => {
    expect(mainEntry).toContain("import './styles/pixel-ui.css'")
    expect(homeView).not.toContain('home-feature-pill-dot')
    expect(homeView).not.toContain('<PixelIcon :name="item.icon" size="md" />')
    expect(homeView).not.toContain('<PixelIcon')
    expect(homeView).not.toContain('primaryActionIcon')
    expect(homeView).toContain("import Icon from '@/components/icons/Icon.vue'")
    expect(homeView).toContain('home-button-icon')
    expect(pixelUi).toContain('.pixel-glyph')
    expect(pixelUi).toContain('.pixel-glyph__pixel--1')
    expect(pixelUi).toContain('.pixel-glyph__pixel--2')
    expect(pixelUi).not.toContain('.pixel-icon--direct')
    expect(pixelUi).not.toContain('.pixel-icon-frame')
  })

  it('removes the public billing formula from the homepage', () => {
    expect(homeView).not.toContain('showHomePricingFormula')
    expect(homeView).not.toContain('home-pricing-section')
    expect(homeView).not.toContain('home-formula-panel')
    expect(homeView).not.toContain('home-formula-actions')
    expect(homeView).not.toContain('home-signal-list')
    expect(homeView).not.toContain('home-signal-pill')
    expect(homeView).not.toContain('home.pricing.formula')
    expect(homeView).not.toContain('home.pricing.signals')
    expect(homeView).not.toContain('home-console-grid')
    expect(homeView).not.toContain('home-metric-card-large')
    expect(homeView).not.toContain('gateway.config')
    expect(homeView).not.toContain('home.pricing.rateTitle')
    expect(homeView).not.toContain('home.pricing.equation')
    expect(homeView).not.toContain('home-tools-section')
    expect(homeView).not.toContain('home-bento-grid')
    expect(homeView).not.toContain('home-workflow-row')
    expect(homeView).not.toContain('home.codingTools')
    expect(homeView).not.toContain('Bento Workflow')
    expect(homeView).not.toContain('officialPricingLinks')
    expect(homeView).not.toContain('https://docs.anthropic.com/en/docs/about-claude/pricing')
    expect(homeView).not.toContain('https://openai.com/api/pricing/')
    expect(homeView).not.toContain('https://ai.google.dev/gemini-api/docs/pricing')
  })
})
