import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const leaderboardView = readFileSync(resolve(process.cwd(), 'src/views/user/LeaderboardView.vue'), 'utf8')

describe('leaderboard visual identity', () => {
  it('renders each user identity on one line with a masked-account fallback', () => {
    expect(leaderboardView).toContain('function getLeaderboardDisplayName(item: UserLeaderboardItem): string')
    expect(leaderboardView).toContain("item.display_name?.trim() || item.email_masked?.trim()")
    expect(leaderboardView).toContain('{{ getLeaderboardDisplayName(item) }}')
    expect(leaderboardView).not.toContain('shouldShowAccountHint')
    expect(leaderboardView).not.toContain('{{ item.email_masked }}')
  })

  it('uses a lightweight rolling odometer for total token volume', () => {
    expect(leaderboardView).toContain('leaderboard-token-odometer')
    expect(leaderboardView).toContain('leaderboard-token-summary-inner')
    expect(leaderboardView).toContain('leaderboard-token-summary-main')
    expect(leaderboardView).toContain('data-testid="leaderboard-recent-token-trend"')
    expect(leaderboardView).toContain('recentTokenTrendChartData')
    expect(leaderboardView).toContain('leaderboard.recentTokenTrend.title')
    expect(leaderboardView).toContain('rollingTokenParts')
    expect(leaderboardView).toContain('function digitReelStyle(value: string')
    expect(leaderboardView).toContain('transform: translateY(var(--target-offset))')
    expect(leaderboardView).not.toContain('formatDateRange(')
    expect(leaderboardView).toContain('@media (prefers-reduced-motion: reduce)')
  })

  it('focuses the main ranking on token usage bars', () => {
    expect(leaderboardView).toContain('data-testid="leaderboard-token-ranking"')
    expect(leaderboardView).toContain('leaderboard-token-bar-fill')
    expect(leaderboardView).toContain('leaderboard-token-bar-segment-input')
    expect(leaderboardView).toContain('leaderboard-token-bar-segment-output')
    expect(leaderboardView).toContain('leaderboard-token-bar-segment-cache')
    expect(leaderboardView).toContain('function tokenBarWidth(item: UserLeaderboardItem): string')
    expect(leaderboardView).toContain('function leaderboardTokenSegmentPercent(value: number, total: number): string')
    expect(leaderboardView).toContain('function tokenBarStyle(item: UserLeaderboardItem): Record<string, string>')
    expect(leaderboardView).toContain('--token-bar-width')
    expect(leaderboardView).toContain('--token-input-width')
    expect(leaderboardView).toContain('--token-output-width')
    expect(leaderboardView).toContain('--token-cache-width')
    expect(leaderboardView).toContain('data-testid="leaderboard-rank-title"')
    expect(leaderboardView).toContain('function visibleLeaderboardTitleBadges')
    expect(leaderboardView).toContain('leaderboard-token-ranking-updated')
    expect(leaderboardView).not.toContain('leaderboard-token-ranking-header')
    expect(leaderboardView).not.toContain('leaderboard.tokenRankingTitle')
    expect(leaderboardView).toContain(':title="leaderboardTokenMetricsLabel(item)"')
    expect(leaderboardView).toContain(':aria-label="leaderboardTokenMetricsLabel(item)"')
    expect(leaderboardView).toContain('leaderboard.inputTokensShort')
    expect(leaderboardView).toContain('leaderboard.outputTokensShort')
    expect(leaderboardView).toContain('leaderboard.cacheTokensShort')
    expect(leaderboardView).toContain('leaderboard.cacheRatioShort')
    expect(leaderboardView).toContain('leaderboard.costPerMillionShort')
    expect(leaderboardView).toContain('function formatLeaderboardCostPerMillion(item: UserLeaderboardItem): string')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-cost-efficiency-summary"')
  })

  it('keeps the period switch inside the token ranking panel without model ranking tabs', () => {
    expect(leaderboardView).toContain('v-for="option in periodOptions"')
    expect(leaderboardView).toContain('@click="selectPeriod(option.value)"')
    expect(leaderboardView).toContain("t('leaderboard.periodLabel')")
    expect(leaderboardView).not.toContain('rankingViewOptions')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-model-ranking"')
    expect(leaderboardView).not.toContain("import ModelIcon from '@/components/common/ModelIcon.vue'")
    expect(leaderboardView).not.toContain("t('leaderboard.viewLabel')")
  })

  it('adds the daily champion calendar below the leaderboard grid', () => {
    expect(leaderboardView).toContain('data-testid="leaderboard-daily-champions-calendar"')
    expect(leaderboardView).toContain('leaderboard-calendar-day')
    expect(leaderboardView).toContain('championCalendarMonths')
    expect(leaderboardView).toContain('leaderboard-calendar-months')
    expect(leaderboardView).toContain('leaderboard-calendar-month-panel')
    expect(leaderboardView).not.toContain('championCalendarMonthOffset')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-calendar-prev"')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-calendar-current"')
    expect(leaderboardView).toContain('leaderboard-calendar-weekdays')
    expect(leaderboardView).toContain('function championCalendarTooltip(day: ChampionCalendarDay): string')
    expect(leaderboardView).toContain('function dailyChampionAvatarInitial(champion: UserLeaderboardDailyChampion): string')
    expect(leaderboardView).toContain('data-testid="leaderboard-calendar-tooltip"')
    expect(leaderboardView).toContain('function showChampionTooltip(day: ChampionCalendarDay, event: Event)')
    expect(leaderboardView).toContain('.leaderboard-calendar-tooltip-tokens')
    expect(leaderboardView).toContain('grid-template-columns: repeat(2, minmax(24.4rem, 1fr))')
    expect(leaderboardView).toContain('background:\n    linear-gradient(180deg, rgb(255 255 255 / 0.86), rgb(248 250 252 / 0.7))')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-calendar-card)')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-calendar-month-panel)')
    expect(leaderboardView).not.toContain('leaderboard-calendar-description')
    expect(leaderboardView).not.toContain('leaderboard-calendar-kicker')
    expect(leaderboardView).toContain('leaderboard.calendar.emptyDay')
  })

  it('keeps the ranking panel bound to a scoped-css-safe dark descendant selector', () => {
    expect(leaderboardView).toContain(':global(.dark .leaderboard-token-ranking-card)')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-token-bar-track)')
    expect(leaderboardView).not.toContain(':global(html.dark) .leaderboard-token-ranking-card')
    expect(leaderboardView).not.toContain(':global(.dark) .leaderboard-token-ranking-card')
  })
})
