import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const leaderboardView = readFileSync(resolve(process.cwd(), 'src/views/user/LeaderboardView.vue'), 'utf8')

describe('leaderboard visual identity', () => {
  it('renders each user identity on one line with a masked-account fallback', () => {
    expect(leaderboardView).toContain('function getLeaderboardDisplayName(item: UserLeaderboardItem): string')
    expect(leaderboardView).toContain("item.display_name?.trim() || item.email_masked?.trim()")
    expect(leaderboardView).toContain('{{ getLeaderboardDisplayName(item) }}')
    expect(leaderboardView).not.toContain('shouldShowAccountHint')
    expect(leaderboardView).not.toContain('{{ item.email_masked }}')
  })

  it('uses a lightweight rolling odometer for total token volume', () => {
    expect(leaderboardView).toContain('leaderboard-token-odometer')
    expect(leaderboardView).toContain('leaderboard-token-summary-inner')
    expect(leaderboardView).toContain('leaderboard-token-summary-main')
    expect(leaderboardView).toContain('data-testid="leaderboard-recent-token-trend"')
    expect(leaderboardView).toContain('recentTokenTrendChartData')
    expect(leaderboardView).toContain('leaderboard.recentTokenTrend.title')
    expect(leaderboardView).toContain('rollingTokenParts')
    expect(leaderboardView).toContain('function digitReelStyle(value: string')
    expect(leaderboardView).toContain('transform: translateY(var(--target-offset))')
    expect(leaderboardView).not.toContain('formatDateRange(')
    expect(leaderboardView).toContain('@media (prefers-reduced-motion: reduce)')
  })

  it('focuses the main ranking on token usage bars', () => {
    expect(leaderboardView).toContain('data-testid="leaderboard-token-ranking"')
    expect(leaderboardView).toContain('leaderboard-token-bar-fill')
    expect(leaderboardView).toContain('leaderboard-token-bar-segment-input')
    expect(leaderboardView).toContain('leaderboard-token-bar-segment-output')
    expect(leaderboardView).toContain('leaderboard-token-bar-segment-cache')
    expect(leaderboardView).toContain('leaderboard-token-legend')
    expect(leaderboardView).toContain('leaderboard-token-legend-dot--input')
    expect(leaderboardView).toContain('leaderboard-token-legend-dot--output')
    expect(leaderboardView).toContain('leaderboard-token-legend-dot--cache')
    expect(leaderboardView).toContain('function tokenBarWidth(item: UserLeaderboardItem): string')
    expect(leaderboardView).toContain('function leaderboardTokenSegmentPercent(value: number, total: number): string')
    expect(leaderboardView).toContain('function tokenBarStyle(item: UserLeaderboardItem): Record<string, string>')
    expect(leaderboardView).toContain('function leaderboardRankChangeLabel(item: UserLeaderboardItem): string')
    expect(leaderboardView).toContain('leaderboard-token-rank-name-line')
    expect(leaderboardView).toContain('data-testid="leaderboard-rank-change"')
    expect(leaderboardView).toContain('leaderboard-rank-change--up')
    expect(leaderboardView).toContain('leaderboard-rank-change--down')
    expect(leaderboardView).toContain('leaderboard-rank-change--new')
    expect(leaderboardView).toContain("item.rank_new")
    expect(leaderboardView).toContain("t('leaderboard.rankChangeNew')")
    expect(leaderboardView).toContain('function leaderboardRankComparedLabel')
    expect(leaderboardView).toContain("t('leaderboard.rankChangeTitle.up'")
    expect(leaderboardView).toContain('--token-bar-width')
    expect(leaderboardView).toContain('--token-input-width')
    expect(leaderboardView).toContain('--token-output-width')
    expect(leaderboardView).toContain('--token-cache-width')
    expect(leaderboardView).toContain('data-testid="leaderboard-rank-title"')
    expect(leaderboardView).toContain('function visibleLeaderboardTitleBadges')
    expect(leaderboardView).toContain('leaderboard-token-ranking-updated')
    expect(leaderboardView).toContain('grid-template-columns: minmax(13.25rem, 14.5rem) minmax(14rem, 1fr)')
    expect(leaderboardView).toContain('const tokenBarTooltipHeight = 136')
    expect(leaderboardView).toContain('const tokenBarTooltipGap = 18')
    expect(leaderboardView).toContain('rect.top + window.scrollY - tokenBarTooltipGap - tokenBarTooltipHeight')
    expect(leaderboardView).toContain('gap: 0.42rem')
    expect(leaderboardView).toContain('min-height: 3.65rem')
    expect(leaderboardView).toContain('max-height: 1.45rem')
    expect(leaderboardView).not.toContain('leaderboard-token-ranking-header')
    expect(leaderboardView).not.toContain('leaderboard.tokenRankingTitle')
    expect(leaderboardView).toContain('data-testid="leaderboard-token-tooltip"')
    expect(leaderboardView).toContain('function showTokenBarTooltip(item: UserLeaderboardItem, event: Event)')
    expect(leaderboardView).toContain('function leaderboardTokenTooltipMetrics(item: UserLeaderboardItem): TokenBarTooltipMetric[]')
    expect(leaderboardView).toContain('leaderboard-token-tooltip')
    expect(leaderboardView).toContain('leaderboard-token-tooltip-table')
    expect(leaderboardView).toContain('role="table"')
    expect(leaderboardView).not.toContain(':title="leaderboardTokenMetricsLabel(item)"')
    expect(leaderboardView).toContain(':aria-label="leaderboardTokenMetricsLabel(item)"')
    expect(leaderboardView).toContain('leaderboard.inputTokensShort')
    expect(leaderboardView).toContain('leaderboard.outputTokensShort')
    expect(leaderboardView).toContain('leaderboard.cacheTokensShort')
    expect(leaderboardView).toContain('leaderboard.cacheRatioShort')
    expect(leaderboardView).toContain('leaderboard.costPerMillionShort')
    expect(leaderboardView).toContain('function formatLeaderboardCostPerMillion(item: UserLeaderboardItem): string')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-cost-efficiency-summary"')
  })

  it('keeps the period switch inside the token ranking panel without model ranking tabs', () => {
    expect(leaderboardView).toContain('v-for="option in periodOptions"')
    expect(leaderboardView).toContain('@click="selectPeriod(option.value)"')
    expect(leaderboardView).toContain("t('leaderboard.periodLabel')")
    expect(leaderboardView).not.toContain('rankingViewOptions')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-model-ranking"')
    expect(leaderboardView).not.toContain("import ModelIcon from '@/components/common/ModelIcon.vue'")
    expect(leaderboardView).not.toContain("t('leaderboard.viewLabel')")
  })

  it('uses a concise record card instead of the old personal info stack', () => {
    expect(leaderboardView).toContain('data-testid="leaderboard-my-record"')
    expect(leaderboardView).toContain('leaderboard-record-card')
    expect(leaderboardView).toContain('myRecordHeadline')
    expect(leaderboardView).toContain('myRecordProgress')
    expect(leaderboardView).toContain('leaderboard-record-kicker')
    expect(leaderboardView).toContain('leaderboard-record-headline')
    expect(leaderboardView).toContain('leaderboard-record-progress')
    expect(leaderboardView).toContain('font-size: clamp(0.98rem, 1.5vw, 1.12rem)')
    expect(leaderboardView).toContain("t('leaderboard.record.deity')")
    expect(leaderboardView).toContain('function buildRecordProgress')
    expect(leaderboardView).toContain('function findLeaderboardEntryByRank')
    expect(leaderboardView).toContain('function formatRecordMillionTokens')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-my-token"')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-my-badge-icon"')
    expect(leaderboardView).not.toContain('leaderboard-side-profile')
  })

  it('keeps the Thursday promo as a compact right-side banner', () => {
    expect(leaderboardView).toContain("import crazyThursdayBannerUrl from '@/assets/leaderboard/crazy-thursday-v50.png'")
    expect(leaderboardView).toContain('data-testid="leaderboard-thursday-banner"')
    expect(leaderboardView).toContain('leaderboard-thursday-banner-copy')
    expect(leaderboardView).toContain('疯狂星期四')
    expect(leaderboardView).toContain('V你50')
    expect(leaderboardView).toContain('height: 5.75rem')
    expect(leaderboardView).toContain('object-fit: cover')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-thursday-banner)')
  })

  it('shows last week top 10 token usage and reward-mode panels instead of old rank reward cards', () => {
    expect(leaderboardView).toContain('function formatRewardAmount(value: number): string')
    expect(leaderboardView).toContain('data-testid="leaderboard-weekly-top10"')
    expect(leaderboardView).toContain('leaderboard-weekly-winner-tokens')
    expect(leaderboardView).toContain('leaderboard-weekly-winner-meta')
    expect(leaderboardView).toContain('leaderboardRewardMode === \'red_packet\'')
    expect(leaderboardView).toContain('data-testid="leaderboard-red-packet-reward"')
    expect(leaderboardView).toContain('leaderboardRewardMode === \'lottery\'')
    expect(leaderboardView).toContain('data-testid="leaderboard-lottery-reward"')
    expect(leaderboardView).toContain('redPacketRangeText')
    expect(leaderboardView).toContain('lotteryDrawTimeText')
    expect(leaderboardView).not.toContain('amountText')
    expect(leaderboardView).not.toContain('leaderboard-reward-tier-label')
    expect(leaderboardView).not.toContain('leaderboard-reward-tier-value')
    expect(leaderboardView).not.toContain("{{ t('leaderboard.dailyReward.rewardAmountHidden') }}")
  })

  it('keeps weekly reward header compact with a short status pill', () => {
    expect(leaderboardView).toContain('dailyRewardStatusText')
    expect(leaderboardView).toContain('data-testid="leaderboard-daily-reward-status"')
    expect(leaderboardView).toContain(':title="dailyRewardReasonText"')
    expect(leaderboardView).toContain("t('leaderboard.dailyReward.statusThresholdNotMet')")
    expect(leaderboardView).toContain("t('leaderboard.dailyReward.lastWeekRank')")
    expect(leaderboardView).toContain('weeklyRushProgressText')
    expect(leaderboardView).toContain("t('leaderboard.dailyReward.weeklyRushProgress')")
    expect(leaderboardView).toContain('loadWeekLeaderboardSummary')
    expect(leaderboardView).toContain('justify-content: space-between')
    expect(leaderboardView).toContain('max-width: 7.8rem')
    expect(leaderboardView).not.toContain('dailyRewardGoalProgressText')
    expect(leaderboardView).not.toContain("t('leaderboard.myRank')")
  })

  it('adds the daily champion calendar below the leaderboard grid', () => {
    expect(leaderboardView).toContain('data-testid="leaderboard-daily-champions-calendar"')
    expect(leaderboardView).toContain('leaderboard-calendar-day')
    expect(leaderboardView).toContain('leaderboard-calendar-meta')
    expect(leaderboardView).toContain('championCalendarMonths')
    expect(leaderboardView).toContain('championCalendarRangeLabel')
    expect(leaderboardView).toContain('leaderboard-calendar-months')
    expect(leaderboardView).toContain('leaderboard-calendar-month-panel')
    expect(leaderboardView).not.toContain('championCalendarMonthOffset')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-calendar-prev"')
    expect(leaderboardView).not.toContain('data-testid="leaderboard-calendar-current"')
    expect(leaderboardView).not.toContain('showPreviousChampionCalendarMonth')
    expect(leaderboardView).not.toContain('showCurrentChampionCalendarMonth')
    expect(leaderboardView).not.toContain('leaderboard-calendar-weekdays')
    expect(leaderboardView).toContain('function championCalendarTooltip(day: ChampionCalendarDay): string')
    expect(leaderboardView).toContain('function dailyChampionAvatarInitial(champion: UserLeaderboardDailyChampion): string')
    expect(leaderboardView).toContain('data-testid="leaderboard-calendar-tooltip"')
    expect(leaderboardView).toContain('function showChampionTooltip(day: ChampionCalendarDay, event: Event)')
    expect(leaderboardView).toContain('.leaderboard-calendar-tooltip-tokens')
    expect(leaderboardView).toContain('columnCount: Math.min(16, Math.max(1, visibleDays))')
    expect(leaderboardView).toContain('grid-template-columns: minmax(var(--calendar-month-min-width), 1fr)')
    expect(leaderboardView).toContain('--calendar-day-size: 4.08rem')
    expect(leaderboardView).toContain('--calendar-day-label-height: 1rem')
    expect(leaderboardView).toContain('--calendar-day-token-height: 0.9rem')
    expect(leaderboardView).toContain('--calendar-month-min-width')
    expect(leaderboardView).toContain('grid-template-columns: repeat(var(--calendar-day-columns), var(--calendar-day-size))')
    expect(leaderboardView).toContain('leaderboard-calendar-avatar-frame')
    expect(leaderboardView).toContain('grid-template-rows: var(--calendar-day-label-height) var(--calendar-day-size) var(--calendar-day-token-height)')
    expect(leaderboardView).toContain('function dailyChampionTokenMLabel(champion: UserLeaderboardDailyChampion): string')
    expect(leaderboardView).toContain('.leaderboard-calendar-token-label')
    expect(leaderboardView).toContain('Math.min(daysInMonth, Math.max(1, anchor.getDate()))')
    expect(leaderboardView).toContain('linear-gradient(180deg, rgb(255 253 248 / 0.92), rgb(250 247 239 / 0.62))')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-calendar-card)')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-calendar-month-panel)')
    expect(leaderboardView).not.toContain('leaderboard-calendar-description')
    expect(leaderboardView).not.toContain('leaderboard-calendar-kicker')
    expect(leaderboardView).toContain('leaderboard.calendar.emptyDay')
  })

  it('keeps the ranking panel bound to a scoped-css-safe dark descendant selector', () => {
    expect(leaderboardView).toContain(':global(.dark .leaderboard-token-ranking-card)')
    expect(leaderboardView).toContain(':global(.dark .leaderboard-token-bar-track)')
    expect(leaderboardView).not.toContain(':global(html.dark) .leaderboard-token-ranking-card')
    expect(leaderboardView).not.toContain(':global(.dark) .leaderboard-token-ranking-card')
  })

  it('uses a short session cache so reopening the leaderboard can render before refresh completes', () => {
    expect(leaderboardView).toContain('const leaderboardSessionCacheTTL = 5 * 60 * 1000')
    expect(leaderboardView).toContain('window.sessionStorage.getItem(leaderboardSessionCacheKey(value))')
    expect(leaderboardView).toContain('loading.value = !cached')
    expect(leaderboardView).toContain('const refreshingLeaderboard = ref(false)')
    expect(leaderboardView).toContain('refreshingLeaderboard.value = !!cached')
    expect(leaderboardView).toContain('data-testid="leaderboard-refreshing"')
    expect(leaderboardView).toContain('leaderboard-token-ranking-refreshing')
    expect(leaderboardView).toContain("t('leaderboard.refreshing')")
    expect(leaderboardView).toContain('writeLeaderboardSessionCache(period.value, response)')
    expect(leaderboardView).toContain('error.value = !leaderboard.value')
    expect(leaderboardView).not.toContain('window.localStorage.getItem(leaderboardSessionCacheKey(value))')
  })
})
