import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const router = readFileSync(resolve(process.cwd(), 'src/router/index.ts'), 'utf8')
const tutorialView = readFileSync(resolve(process.cwd(), 'src/views/public/TutorialView.vue'), 'utf8')
const tutorialFallback = readFileSync(resolve(process.cwd(), 'src/views/public/tutorialFallback.ts'), 'utf8')
const tutorialMarkdown = readFileSync(resolve(process.cwd(), 'src/utils/tutorialMarkdown.ts'), 'utf8')
const tutorialAdminView = readFileSync(resolve(process.cwd(), 'src/views/admin/TutorialPagesView.vue'), 'utf8')
const tutorialsApi = readFileSync(resolve(process.cwd(), 'src/api/tutorials.ts'), 'utf8')
const adminTutorialsApi = readFileSync(resolve(process.cwd(), 'src/api/admin/tutorials.ts'), 'utf8')
const sidebar = readFileSync(resolve(process.cwd(), 'src/components/layout/AppSidebar.vue'), 'utf8')
const modelPlazaView = readFileSync(resolve(process.cwd(), 'src/views/public/ModelPlazaView.vue'), 'utf8')
const legalDocumentView = readFileSync(resolve(process.cwd(), 'src/views/public/LegalDocumentView.vue'), 'utf8')
const publicBackdrop = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicMatrixBackdrop.vue'), 'utf8')
const matrixRain = readFileSync(resolve(process.cwd(), 'src/views/public/components/matrixRain.ts'), 'utf8')
const publicTopNav = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicTopNav.vue'), 'utf8')
const publicCss = readFileSync(resolve(process.cwd(), 'src/views/public/public-page.css'), 'utf8')
const sourceSiteBrandPattern = /LMUAI|lmuai|lmu\.ai|TiMi|TIMICC|timicc/i

describe('public tutorial CMS and model plaza pages', () => {
  it('registers tutorial list/detail publicly and protects model plaza behind login', () => {
    expect(router).toContain("path: '/tutorial'")
    expect(router).toContain("name: 'Tutorial'")
    expect(router).toContain("path: '/tutorial/:slug'")
    expect(router).toContain("name: 'TutorialPage'")
    expect(router).toContain("path: '/models'")
    expect(router).toContain("name: 'ModelPlaza'")
    expect(router).toMatch(/path: '\/models'[\s\S]*?requiresAuth: true/)
    expect(router).toContain("'/tutorial'")
    expect(router).not.toContain("'/tutorial', '/models'")
    expect(router).not.toMatch(/BACKEND_MODE_ALLOWED_PATHS[\s\S]*?'\/models'/)
  })

  it('loads published tutorial CMS content with built-in fallback and legacy hash redirects', () => {
    expect(tutorialView).toContain('tutorialsAPI.list()')
    expect(tutorialView).toContain('tutorialsAPI.getBySlug(slug)')
    expect(tutorialView).toContain('tutorialFallbackPages')
    expect(tutorialView).toContain('setFallbackPages')
    expect(tutorialView).toContain('sourceNotice')
    expect(tutorialView).toContain('教程 CMS 暂不可用')
    expect(tutorialView).toContain('后台暂无已发布教程')
    expect(tutorialView).toContain('<template v-else>')
    expect(tutorialView).toContain('legacyHashRedirects')
    expect(tutorialView).toContain("claude: 'claude-code'")
    expect(tutorialView).toContain("ccswitch: 'cc-switch'")
    expect(tutorialView).toContain("router.replace({ path: `/tutorial/${target}` })")
    expect(tutorialView).toContain('isIndexRoute')
    expect(tutorialView).toContain('tutorial-directory-grid')
    expect(tutorialView).toContain('选择一篇教程开始')
    expect(tutorialView.indexOf('a.sort_order !== b.sort_order')).toBeLessThan(
      tutorialView.indexOf('a.category !== b.category')
    )
    expect(tutorialView).toContain('v-html="renderedHtml"')
    expect(tutorialView).toContain('renderTutorialMarkdown(page.content_md)')
    expect(tutorialView).toContain('aria-label="接入教程目录"')
    expect(tutorialView).toContain('aria-label="当前文章目录"')
    expect(tutorialView).toContain('IntersectionObserver')
    expect(tutorialView).toContain('scrollIntoView')
    expect(tutorialView).toContain('class="tutorial-sidebar"')
    expect(tutorialView).toContain('class="tutorial-main-column"')
    expect(tutorialView).toContain('class="tutorial-toc"')
    expect(tutorialView).toContain('copy-command-button')
    expect(tutorialView).toContain('navigator.clipboard')
    expect(tutorialView).toContain('<PublicTopNav />')
    expect(tutorialView).toContain('<PublicMatrixBackdrop />')
    expect(tutorialsApi).toContain("apiClient.get<{ items: TutorialPageSummary[] }>('/tutorials')")
    expect(tutorialsApi).toContain("`/tutorials/${encodeURIComponent(slug)}`")
  })

  it('keeps default tutorial seeds local to Luoye wording and shortcode-ready', () => {
    for (const slug of [
      'getting-started',
      'codex',
      'claude-code',
      'cc-switch',
      'cockpit-tools',
      'minepilotqa',
      'openclaw',
      'hermes-agent',
      'faq'
    ]) {
      expect(tutorialFallback).toContain(`slug: '${slug}'`)
    }
    expect(tutorialFallback).toContain('落叶网络控制台')
    expect(tutorialFallback).toContain('https://ai.3zapi.top/v1')
    expect(tutorialFallback).toContain('Codex App：不把 Git、Node.js 作为启动前置条件')
    expect(tutorialFallback).toContain('Codex CLI：需要 Node.js/npm')
    expect(tutorialFallback).toContain('Claude Code：npm 安装路径需要 Node.js 18+')
    expect(tutorialFallback).not.toContain('1. 安装 Git 和 Node.js。')
    expect(tutorialFallback).not.toContain('Node.js v18 或更高版本。')
    expect(tutorialFallback).toContain('[[command')
    expect(tutorialFallback).toContain('[[screenshot')
    expect(tutorialFallback).toContain('[[callout')
    expect(tutorialFallback).toContain('[[link-button')
    expect(tutorialFallback).toContain('/tutorial/minepilotqa/provider-list.png')
    expect(tutorialFallback).not.toMatch(sourceSiteBrandPattern)
    expect(tutorialView).not.toMatch(sourceSiteBrandPattern)
  })

  it('sanitizes Markdown and renders the minimal tutorial shortcode set', () => {
    expect(tutorialMarkdown).toContain("import DOMPurify from 'dompurify'")
    expect(tutorialMarkdown).toContain('DOMPurify.sanitize')
    expect(tutorialMarkdown).toContain('marked.parse')
    expect(tutorialMarkdown).toContain('renderShortcodes')
    expect(tutorialMarkdown).toContain('tutorial-command-block command-block')
    expect(tutorialMarkdown).toContain('data-copy-code')
    expect(tutorialMarkdown).toContain('tutorial-callout tutorial-callout-')
    expect(tutorialMarkdown).toContain('tutorial-screenshot-card')
    expect(tutorialMarkdown).toContain('guide-action-link')
    expect(tutorialMarkdown).toContain('generateHeadingId')
  })

  it('adds an admin tutorial editor that is independent from custom menu pages', () => {
    expect(router).toContain("path: '/admin/tutorials'")
    expect(router).toContain("name: 'AdminTutorialPages'")
    expect(router).toContain("import('@/views/admin/TutorialPagesView.vue')")
    expect(sidebar).toContain("{ path: '/admin/tutorials', label: t('nav.tutorials'), icon: ContentIcon }")
    expect(tutorialAdminView).toContain('adminAPI.tutorials.list')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.getById')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.create')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.update')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.updateStatus')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.delete')
    expect(tutorialAdminView).toContain('Markdown + 短代码')
    expect(tutorialAdminView).toContain('预览')
    expect(tutorialAdminView).toContain('renderTutorialMarkdown(form.content_md).html')
    expect(tutorialAdminView).toContain('[[command]]、[[screenshot]]、[[callout]]、[[link-button]]')
    expect(tutorialAdminView).toContain('showStatusDialog')
    expect(tutorialAdminView).toContain('requestStatusChange(row)')
    expect(tutorialAdminView).toContain('rowBusyId')
    expect(tutorialAdminView).toContain('showDiscardDialog')
    expect(tutorialAdminView).toContain('isFormDirty')
    expect(tutorialAdminView).toContain('requestCloseEdit')
    expect(tutorialAdminView).toContain('tutorial-load-error')
    expect(tutorialAdminView).toContain('row.status === \'published\'')
    expect(adminTutorialsApi).toContain("apiClient.get<BasePaginationResponse<TutorialPageSummary>>('/admin/tutorials'")
    expect(adminTutorialsApi).toContain("`/admin/tutorials/${id}/status`")
    expect(adminTutorialsApi).toContain('deleteTutorial')
    expect(tutorialAdminView).not.toContain('custom_menu_items')
  })

  it('adds a public model plaza with searchable pricing cards', () => {
    expect(modelPlazaView).toContain('模型广场')
    expect(modelPlazaView).toContain('浏览可用的 AI 模型及其定价')
    expect(modelPlazaView).toContain('model-filter-panel')
    expect(modelPlazaView).toContain('model-card-grid')
    expect(modelPlazaView).toContain('显示倍率价格')
    expect(modelPlazaView).toContain('Prompt Caching')
    expect(modelPlazaView).toContain('userChannelsAPI.getAvailable')
    expect(modelPlazaView).toContain('userGroupsAPI.getUserGroupRates')
    expect(modelPlazaView).toContain('fallbackChannels')
    expect(modelPlazaView).toContain('formatModelPrice')
    expect(modelPlazaView).toContain('selectedRateGroup')
    expect(modelPlazaView).toContain('formatPricePerMillion')
    expect(modelPlazaView).not.toMatch(sourceSiteBrandPattern)
  })

  it('shares the public matrix visual treatment on public content pages', () => {
    expect(tutorialView).toContain('PublicMatrixBackdrop')
    expect(modelPlazaView).toContain('PublicMatrixBackdrop')
    expect(legalDocumentView).toContain('PublicMatrixBackdrop')
    expect(modelPlazaView).toContain("from './components/PublicMatrixBackdrop.vue'")
    expect(publicBackdrop).toContain('public-matrix-rain')
    expect(publicBackdrop).toContain('const matrixColumnCount = 42')
    expect(publicBackdrop).toContain('useMatrixRain(matrixColumnCount, 620)')
    expect(matrixRain).toContain('refreshMatrixColumns')
    expect(matrixRain).toContain('randomMatrixText')
    expect(matrixRain).toContain('prefers-reduced-motion: reduce')
    expect(publicCss).toContain('.public-page-shell')
    expect(modelPlazaView).toContain('linear-gradient(180deg, #050914 0%, #08110f 48%, #03060a 100%)')
    expect(modelPlazaView).not.toContain('linear-gradient(135deg, #e8f4f3 0%, #eef2f2 48%, #dfe9ea 100%)')
  })

  it('uses one shared public top navigation across public pages and highlights tutorial detail routes', () => {
    expect(tutorialView).toContain("from './components/PublicTopNav.vue'")
    expect(modelPlazaView).toContain("from './components/PublicTopNav.vue'")
    expect(legalDocumentView).toContain("from './components/PublicTopNav.vue'")
    expect(publicTopNav).toContain('public-top-shell')
    expect(publicTopNav).toContain('public-nav-center')
    expect(publicTopNav).toContain('public-mobile-nav')
    expect(publicTopNav).toContain('public-nav-button')
    expect(publicTopNav).toContain('position: sticky')
    expect(publicTopNav).toContain('authStore.isAuthenticated')
    expect(publicTopNav).toContain("isAuthenticated ? dashboardPath : '/login'")
    expect(publicTopNav).toContain('isNavItemActive(item)')
    expect(publicTopNav).toContain("route.path.startsWith(`${path}/`)")
    expect(publicTopNav).toContain("to: '/tutorial'")
    expect(publicTopNav).toContain("to: '/models'")
    expect(publicTopNav).not.toContain('navFeatures')
    expect(publicTopNav).not.toContain('功能特性')
    expect(publicTopNav).not.toContain('#features')
    expect(publicCss).not.toContain('.public-page-header')
    expect(modelPlazaView).not.toContain('model-plaza-topbar')
  })

  it('opens login agreement documents by configured id or document title', () => {
    expect(router).toContain("path: '/legal/:documentId'")
    expect(router).toContain("name: 'LegalDocument'")
    expect(legalDocumentView).toContain('login_agreement_documents')
    expect(legalDocumentView).toContain('(doc.id || doc.title) === id')
    expect(legalDocumentView).toContain('class="legal-document-page public-page-shell')
    expect(legalDocumentView).toContain('appStore.fetchPublicSettings()')
    expect(legalDocumentView).toContain('documentBodyMarkdown')
    expect(legalDocumentView).toContain("replace(/^#{1,6}\\s+/, '').trim()")
    expect(legalDocumentView).not.toContain('mc-pixel-grid')
    expect(legalDocumentView).not.toContain("from '@/api/auth'")
  })
})
