import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const router = readFileSync(resolve(process.cwd(), 'src/router/index.ts'), 'utf8')
const tutorialView = readFileSync(resolve(process.cwd(), 'src/views/public/TutorialView.vue'), 'utf8')
const modelPlazaView = readFileSync(resolve(process.cwd(), 'src/views/public/ModelPlazaView.vue'), 'utf8')
const legalDocumentView = readFileSync(resolve(process.cwd(), 'src/views/public/LegalDocumentView.vue'), 'utf8')
const publicBackdrop = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicMatrixBackdrop.vue'), 'utf8')
const matrixRain = readFileSync(resolve(process.cwd(), 'src/views/public/components/matrixRain.ts'), 'utf8')
const publicTopNav = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicTopNav.vue'), 'utf8')
const publicCss = readFileSync(resolve(process.cwd(), 'src/views/public/public-page.css'), 'utf8')
const sourceSiteBrandPattern = new RegExp(['Ti', 'Mi|TIM', 'ICC|tim', 'icc'].join(''), 'i')

describe('public tutorial and model plaza pages', () => {
  it('registers tutorial and model plaza as public routes', () => {
    expect(router).toContain("path: '/tutorial'")
    expect(router).toContain("name: 'Tutorial'")
    expect(router).toContain("path: '/models'")
    expect(router).toContain("name: 'ModelPlaza'")
    expect(router).toContain("'/tutorial'")
    expect(router).toContain("'/models'")
  })

  it('uses original Luoye Network tutorial content instead of copied source-site branding', () => {
    expect(tutorialView).toContain('AI 接入教程')
    expect(tutorialView).toContain('新手最快路线')
    expect(tutorialView).toContain('只想先把 Codex 跑起来，看这 4 步')
    expect(tutorialView).toContain('CC Switch、Cockpit Tools 和其他工具都可以先跳过')
    expect(tutorialView).toContain('class="beginner-path"')
    expect(tutorialView).toContain('class="beginner-step"')
    expect(tutorialView).toContain("title: '最快路线'")
    expect(tutorialView).toContain("id: 'quick-start', step: '01'")
    expect(tutorialView).toContain("title: '使用 Codex', desc: '创建 codex 密钥")
    expect(tutorialView).toContain("title: 'CC Switch', desc: '可选账号管理'")
    expect(tutorialView).toContain("title: 'Cockpit Tools', desc: '可选网页面板'")
    expect(tutorialView).toContain('先装基础工具')
    expect(tutorialView).toContain('Linux 和 macOS 环境配置')
    expect(tutorialView).toContain('Windows 安装 Git / Node.js')
    expect(tutorialView).toContain('Windows 选择 64 位安装包')
    expect(tutorialView).toContain('Git-2.53.0-64-bit.exe')
    expect(tutorialView).toContain('node-v24.13.1-x64.msi')
    expect(tutorialView).toContain('Git 2.53.0 64 位官方')
    expect(tutorialView).toContain('Node.js 24.13.1 x64 官方')
    expect(tutorialView).toContain('Linux Shell 配置')
    expect(tutorialView).toContain('macOS Shell 配置')
    expect(tutorialView).toContain('CC Switch 账号管理')
    expect(tutorialView).toContain('推荐从落叶网络控制台一键导入 Provider')
    expect(tutorialView).toContain('ccswitch://')
    expect(tutorialView).toContain('Deep Link')
    expect(tutorialView).toContain('Provider 管理')
    expect(tutorialView).toContain('MCP 服务器管理')
    expect(tutorialView).toContain('Prompts 管理')
    expect(tutorialView).toContain('多平台支持')
    expect(tutorialView).toContain('导入 CC Switch')
    expect(tutorialView).toContain('brew tap farion1231/ccswitch')
    expect(tutorialView).toContain('brew install --cask cc-switch')
    expect(tutorialView).toContain('paru -S cc-switch-bin')
    expect(tutorialView).toContain('http://localhost:17666')
    expect(tutorialView).toContain('github.com/farion1231/cc-switch/releases')
    expect(tutorialView).toContain('Cockpit Tools 账号管理')
    expect(tutorialView).toContain('github.com/jlcodes99/cockpit-tools')
    expect(tutorialView).toContain('releases/tag/v0.23.2')
    expect(tutorialView).toContain("cockpitBaseUrl: 'https://ai.3zapi.top'")
    expect(tutorialView).toContain('APIKEY')
    expect(tutorialView).toContain('恢复 Codex 会话')
    expect(tutorialView).toContain('修复可见性')
    expect(tutorialView).toContain('Codex 配置')
    expect(tutorialView).toContain('Codex App 配置教程')
    expect(tutorialView).toContain('先创建 Codex 类型 API 密钥')
    expect(tutorialView).toContain('guide-grid guide-grid--single')
    expect(tutorialView).toContain('按 Codex 段的 1-8 步写 config.toml 和 auth.json')
    expect(tutorialView).toContain('密钥类型选择 <code>codex</code>')
    expect(tutorialView).toContain('安装 Codex App')
    expect(tutorialView).toContain('Microsoft Store')
    expect(tutorialView).toContain('winget install --id OpenAI.Codex -e')
    expect(tutorialView).toContain('https://chatgpt.com/codex')
    expect(tutorialView).toContain('打开 Codex 配置文件')
    expect(tutorialView).toContain('config.toml')
    expect(tutorialView).toContain('C:\\Users\\用户名\\.codex\\config.toml')
    expect(tutorialView).toContain('auth.json')
    expect(tutorialView).toContain('C:\\Users\\用户名\\.codex\\auth.json')
    expect(tutorialView).toContain('输入你的key')
    expect(tutorialView).toContain('model_provider = "luoye"')
    expect(tutorialView).toContain('model = "gpt-5.5"')
    expect(tutorialView).toContain('base_url = "https://ai.3zapi.top/v1"')
    expect(tutorialView).toContain('wire_api = "responses"')
    expect(tutorialView).toContain('"OPENAI_API_KEY": "输入你的key"')
    expect(tutorialView).toContain("title: 'Codex', desc: 'App / 插件配置'")
    expect(tutorialView).toContain('VSCode 集成 Codex')
    expect(tutorialView).toContain("Codex - OpenAI's coding agent")
    expect(tutorialView).toContain('CLI 用户可选安装')
    expect(tutorialView).toContain('.guide-grid--single')
    expect(tutorialView).toContain('.beginner-path-grid')
    expect(tutorialView).toContain('grid-template-columns: repeat(10, minmax(8.5rem, 1fr))')
    expect(tutorialView).toContain('Claude Code 配置')
    expect(tutorialView).toContain('OpenClaw 接入')
    expect(tutorialView).toContain('Hermes-Agent 接入')
    expect(tutorialView).toContain('docs.easyrouter.io/zh/docs/apps/openclaw')
    expect(tutorialView).toContain('docs.easyrouter.io/zh/docs/apps/hermes-agent')
    expect(tutorialView).toContain('openclaw.json')
    expect(tutorialView).toContain('models.providers')
    expect(tutorialView).toContain('openai-completions')
    expect(tutorialView).toContain('agents.defaults.model.primary')
    expect(tutorialView).toContain('luoye/gpt-5.3-codex')
    expect(tutorialView).toContain('LUOYE_API_KEY')
    expect(tutorialView).toContain('openclaw onboard')
    expect(tutorialView).toContain('openclaw dashboard')
    expect(tutorialView).toContain('curl -fsSL https://raw.githubusercontent.com/terryso/hermes-agent/main/install.sh | bash')
    expect(tutorialView).toContain('hermes model')
    expect(tutorialView).toContain('Custom Endpoint')
    expect(tutorialView).toContain('gpt-5.3-codex')
    expect(tutorialView.indexOf('Codex 配置')).toBeLessThan(
      tutorialView.indexOf('Claude Code 配置')
    )
    expect(tutorialView.indexOf('Claude Code 配置')).toBeLessThan(
      tutorialView.indexOf('OpenClaw 接入')
    )
    expect(tutorialView.indexOf('OpenClaw 接入')).toBeLessThan(
      tutorialView.indexOf('Hermes-Agent 接入')
    )
    expect(tutorialView).toContain('npm install -g @openai/codex --registry=https://registry.npmmirror.com')
    expect(tutorialView).toContain('登录落叶网络控制台')
    expect(tutorialView).toContain('API 密钥')
    expect(tutorialView).toContain('新建密钥')
    expect(tutorialView).toContain('复制生成的 Token')
    expect(tutorialView).toContain('Base URL')
    expect(tutorialView).toContain(':to="apiKeysLink"')
    expect(tutorialView).toContain('打开 API 密钥页面')
    expect(tutorialView).toContain('登录后打开 API 密钥页面')
    expect(tutorialView).toContain("query: { redirect: '/keys' }")
    expect(tutorialView).toContain('authStore.isAuthenticated')
    expect(tutorialView).toContain('guide-action-link')
    expect(tutorialView).not.toContain('codex config set token')
    expect(tutorialView).not.toContain('codex config set base_url "https://ai.3zapi.top"')
    expect(tutorialView).toContain('export CODEX_BASE_URL="https://ai.3zapi.top"')
    expect(tutorialView).toContain('export ANTHROPIC_BASE_URL="https://ai.3zapi.top"')
    expect(tutorialView).toContain('$env:ANTHROPIC_BASE_URL="https://ai.3zapi.top"')
    expect(tutorialView).not.toContain('你的接口地址')
    expect(tutorialView).toContain('CODEX_BASE_URL')
    expect(tutorialView).toContain('npm install -g @anthropic-ai/claude-code')
    expect(tutorialView).toContain('ANTHROPIC_AUTH_TOKEN')
    expect(tutorialView).toContain('ANTHROPIC_BASE_URL')
    expect(tutorialView).toContain('兜底配置文件')
    expect(tutorialView).toContain('复制')
    expect(tutorialView).toContain('copyCommand')
    expect(tutorialView).toContain('navigator.clipboard')
    expect(tutorialView).toContain('<PublicTopNav />')
    expect(tutorialView).not.toMatch(sourceSiteBrandPattern)
  })

  it('keeps the tutorial index sticky and synchronized with the reader position', () => {
    expect(tutorialView).toContain('aria-label="接入教程目录"')
    expect(tutorialView).toContain('aria-label="接入路线图"')
    expect(tutorialView).toContain('routeSteps')
    expect(tutorialView).toContain("title: '准备工作'")
    expect(tutorialView).toContain("title: 'Linux / macOS'")
    expect(tutorialView).toContain("title: 'CC Switch'")
    expect(tutorialView).toContain("title: 'Cockpit Tools'")
    expect(tutorialView).toContain("title: 'Codex'")
    expect(tutorialView).toContain("title: 'Claude'")
    expect(tutorialView).toContain("title: 'OpenClaw'")
    expect(tutorialView).toContain("title: 'Hermes'")
    expect(tutorialView).toContain("title: '常见问题'")
    expect(tutorialView).toContain('activeSection')
    expect(tutorialView).toContain('IntersectionObserver')
    expect(tutorialView).toContain("rootMargin: '-26% 0px -56% 0px'")
    expect(tutorialView).toContain(":class=\"{ 'is-active': activeSection === item.id }\"")
    expect(tutorialView).toContain(":aria-current=\"activeSection === item.id ? 'true' : undefined\"")
    expect(tutorialView).toContain('scrollIntoView')
    expect(tutorialView).toContain("inline: 'center'")
    expect(tutorialView).toContain('class="tutorial-sidebar"')
    expect(tutorialView).not.toContain('class="tutorial-toc"')
    expect(tutorialView).not.toContain('docAnchors')
    expect(tutorialView).not.toContain('activeTocAnchor')
    expect(tutorialView).not.toContain('tocObserver')
    expect(tutorialView).toContain('doc-pills')
    expect(tutorialView).toContain('接入 Agent 工具')
    expect(tutorialView).toContain('教程目录')
    expect(tutorialView).toContain('.tutorial-reader')
    expect(tutorialView).toContain('class="tutorial-main-column"')
    expect(tutorialView).toContain('max-width: min(128rem, calc(100vw - 1rem))')
    expect(tutorialView).toContain('grid-template-columns: minmax(13rem, 16rem) minmax(0, 72rem)')
    expect(tutorialView).toContain('position: sticky')
    expect(tutorialView).toContain('--tutorial-index-sticky-top: 4.15rem')
    expect(tutorialView).toContain('top: var(--tutorial-index-sticky-top)')
    expect(tutorialView).toContain('grid-template-columns: repeat(10, minmax(8.5rem, 1fr))')
    expect(tutorialView).toContain('scroll-margin-top: calc(var(--tutorial-index-sticky-top) + 1rem)')
    expect(tutorialView).toContain('.command-block code')
    expect(tutorialView).toContain('color: #f8fafc')
  })

  it('adds a public model plaza with searchable pricing cards', () => {
    expect(modelPlazaView).toContain('模型广场')
    expect(modelPlazaView).toContain('浏览可用的 AI 模型及其定价')
    expect(modelPlazaView).toContain('model-filter-panel')
    expect(modelPlazaView).toContain('model-card-grid')
    expect(modelPlazaView).toContain('显示倍率价格')
    expect(modelPlazaView).toContain('Prompt Caching')
    expect(modelPlazaView).toContain('userChannelsAPI.getAvailable')
    expect(modelPlazaView).toContain('userGroupsAPI.getUserGroupRates')
    expect(modelPlazaView).toContain('fallbackChannels')
    expect(modelPlazaView).toContain('formatModelPrice')
    expect(modelPlazaView).toContain('channels.value = list')
    expect(modelPlazaView).toContain('userGroupsAPI.getAvailable()')
    expect(modelPlazaView).toContain('channels.value.length > 0 ? channels.value : fallbackChannels')
    expect(modelPlazaView).toContain('selectedRateGroup')
    expect(modelPlazaView).toContain("selectedGroupKey() !== 'all'")
    expect(modelPlazaView).toContain('isRatePriceActive')
    expect(modelPlazaView).toContain('倍率分组')
    expect(modelPlazaView).toContain('不使用倍率')
    expect(modelPlazaView).toContain('先选择倍率分组')
    expect(modelPlazaView).toContain('formatBaseModelPrice')
    expect(modelPlazaView).toContain('formatPricePerMillion')
    expect(modelPlazaView).not.toMatch(sourceSiteBrandPattern)
  })

  it('shares the public matrix visual treatment on public content pages', () => {
    expect(tutorialView).toContain('PublicMatrixBackdrop')
    expect(modelPlazaView).toContain('PublicMatrixBackdrop')
    expect(legalDocumentView).toContain('PublicMatrixBackdrop')
    expect(modelPlazaView).toContain("from './components/PublicMatrixBackdrop.vue'")
    expect(publicBackdrop).toContain('public-matrix-rain')
    expect(publicBackdrop).toContain('const matrixColumnCount = 42')
    expect(publicBackdrop).toContain('useMatrixRain(matrixColumnCount, 620)')
    expect(publicBackdrop).toContain('opacity: column.opacity')
    expect(publicBackdrop).toContain('fontSize: column.fontSize')
    expect(publicBackdrop).toContain('lineHeight: column.lineHeight')
    expect(matrixRain).toContain('refreshMatrixColumns')
    expect(matrixRain).toContain('randomMatrixText')
    expect(matrixRain).toContain('prefers-reduced-motion: reduce')
    expect(publicBackdrop).toContain('linear-gradient(\n    to bottom')
    expect(publicBackdrop).toContain('transparent 0%')
    expect(publicBackdrop).toContain('rgba(0, 0, 0, 0.96) 100%')
    expect(publicCss).toContain('.public-page-shell')
    expect(modelPlazaView).toContain('linear-gradient(180deg, #050914 0%, #08110f 48%, #03060a 100%)')
    expect(modelPlazaView).not.toContain('linear-gradient(135deg, #e8f4f3 0%, #eef2f2 48%, #dfe9ea 100%)')
  })

  it('uses one shared public top navigation across public pages', () => {
    expect(tutorialView).toContain("from './components/PublicTopNav.vue'")
    expect(modelPlazaView).toContain("from './components/PublicTopNav.vue'")
    expect(legalDocumentView).toContain("from './components/PublicTopNav.vue'")
    expect(modelPlazaView).toContain('<PublicTopNav />')
    expect(legalDocumentView).toContain('<PublicTopNav />')
    expect(publicTopNav).toContain('public-top-shell')
    expect(publicTopNav).toContain('public-top-nav')
    expect(publicTopNav).toContain('public-nav-center')
    expect(publicTopNav).toContain('public-mobile-nav')
    expect(publicTopNav).toContain('public-nav-button')
    expect(publicTopNav).toContain('position: sticky')
    expect(publicTopNav).toContain('top: 0')
    expect(publicTopNav).toContain('authStore.isAuthenticated')
    expect(publicTopNav).toContain("isAuthenticated ? dashboardPath : '/login'")
    expect(publicTopNav).toContain("to: '/tutorial'")
    expect(publicTopNav).toContain("to: '/models'")
    expect(publicTopNav).toContain("t('home.navHome')")
    expect(publicTopNav).not.toContain('navFeatures')
    expect(publicTopNav).not.toContain('功能特性')
    expect(publicTopNav).not.toContain('#features')
    expect(publicCss).not.toContain('.public-page-header')
    expect(modelPlazaView).not.toContain('model-plaza-topbar')
  })

  it('opens login agreement documents by configured id or document title', () => {
    expect(router).toContain("path: '/legal/:documentId'")
    expect(router).toContain("name: 'LegalDocument'")
    expect(legalDocumentView).toContain('login_agreement_documents')
    expect(legalDocumentView).toContain('(doc.id || doc.title) === id')
    expect(legalDocumentView).toContain('class="legal-document-page public-page-shell')
    expect(legalDocumentView).toContain('appStore.fetchPublicSettings()')
    expect(legalDocumentView).toContain('documentBodyMarkdown')
    expect(legalDocumentView).toContain("replace(/^#{1,6}\\s+/, '').trim()")
    expect(legalDocumentView).not.toContain('mc-pixel-grid')
    expect(legalDocumentView).not.toContain("from '@/api/auth'")
  })
})
