import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const router = readFileSync(resolve(process.cwd(), 'src/router/index.ts'), 'utf8')
const homeView = readFileSync(resolve(process.cwd(), 'src/views/HomeView.vue'), 'utf8')
const tutorialView = readFileSync(resolve(process.cwd(), 'src/views/public/TutorialView.vue'), 'utf8')
const modelPlazaView = readFileSync(resolve(process.cwd(), 'src/views/public/ModelPlazaView.vue'), 'utf8')
const publicTopNav = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicTopNav.vue'), 'utf8')
const publicBackdrop = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicRevealBackdrop.vue'), 'utf8')
const publicCss = readFileSync(resolve(process.cwd(), 'src/views/public/public-page.css'), 'utf8')
const viteConfig = readFileSync(resolve(process.cwd(), 'vite.config.ts'), 'utf8')

describe('public page smoke contracts', () => {
  it('keeps public entry routes and gates model plaza by published policy', () => {
    expect(router).toContain("path: '/home'")
    expect(router).toContain("path: '/tutorial'")
    expect(router).toContain("path: '/tutorial/:slug'")
    expect(router).toContain("path: '/models'")
    expect(router).toContain("name: 'Home'")
    expect(router).toContain("name: 'Tutorial'")
    expect(router).toContain("name: 'ModelPlaza'")
    expect(router).toContain("window.history.scrollRestoration = 'manual'")
    expect(router).toMatch(/path: '\/models'[\s\S]*?requiresAuth: false/)
    expect(router).toContain("to.name === 'ModelPlaza'")
    expect(router).toContain('!appStore.publicSettingsLoaded || modelPlaza?.model_plaza_enabled !== true')
    expect(router).toContain('appStore.backendModeEnabled && (!authStore.isAuthenticated || !authStore.isAdmin)')
    expect(router).toContain('model_plaza_require_auth === true')
    const backendModeAllowedPaths = router.match(/const BACKEND_MODE_ALLOWED_PATHS = \[([^\]]*)\]/)?.[1] ?? ''
    expect(backendModeAllowedPaths).not.toContain("'/models'")
  })

  it('keeps the setup page on the SPA route while proxying setup APIs in dev', () => {
    expect(router).toMatch(/path: '\/setup'[\s\S]*?import\('@\/views\/setup\/SetupWizardView\.vue'\)/)
    expect(viteConfig).toContain("'/setup/'")
    expect(viteConfig).not.toContain("'/setup': {")
  })

  it('routes chat image entry to the Luoye Creative launch workspace', () => {
    expect(router).toContain("path: '/chat-images'")
    expect(router).toContain("alias: '/studio-bridge/launch'")
    expect(router).toContain("path: '/studio-bridge/session-probe'")
    expect(router).toContain("name: 'StudioBridgeSessionProbe'")
    expect(router).toContain("import('@/views/user/StudioBridgeSessionProbeView.vue')")
    expect(router).toMatch(/BACKEND_MODE_ALLOWED_PATHS[\s\S]*?'\/studio-bridge\/session-probe'/)
    expect(router).toContain("name: 'ChatImageStudio'")
    expect(router).toContain("import('@/views/user/LuoyeAILaunchView.vue')")
    expect(router).not.toContain("path: '/canvas'")
    expect(router).not.toContain("name: 'CanvasStudio'")
    expect(router).toContain("path: '/image-manager'")
    expect(router).toContain("name: 'ImageManager'")
    expect(router).toContain("import('@/views/user/ImageManagerView.vue')")
    expect(router).toContain("path: '/chat-images/native'")
    expect(router).toContain("name: 'ChatImageStudioNative'")
    expect(router).toContain("import('@/views/user/ChatImageStudioView.vue')")
  })

  it('uses one shared navigation and light public surface across public pages', () => {
    expect(homeView).toContain('<PublicTopNav />')
    expect(tutorialView).toContain('<PublicTopNav />')
    expect(modelPlazaView).toContain('<PublicTopNav />')
    expect(tutorialView).toContain('<PublicRevealBackdrop variant="page" />')
    expect(modelPlazaView).toContain('<PublicRevealBackdrop variant="page" />')
    expect(publicTopNav).toContain('public-top-shell')
    expect(publicTopNav).not.toContain('public-nav-button')
    expect(publicTopNav).toContain('public-nav-link')
    expect(publicTopNav).toContain('<nav class="public-top-nav">')
    expect(publicTopNav).toContain('justify-content: flex-end')
    expect(publicTopNav).toContain('position: fixed')
    expect(publicTopNav).toContain('backdrop-filter: blur(22px) saturate(1.18)')
    expect(publicTopNav).toContain("to: '/home'")
    expect(publicTopNav).toContain("to: '/tutorial'")
    expect(publicTopNav).toContain("to: '/models'")
    expect(publicTopNav).toContain("t('home.navContact')")
    expect(publicTopNav).toContain('openSupportPopup')
    expect(publicTopNav).not.toContain('hasSupportButton')
    expect(publicTopNav).not.toContain('hasSupportContent')
    expect(publicTopNav).not.toContain('public-nav-button')
    expect(publicTopNav).toContain("import { useAppStore, useAuthStore } from '@/stores'")
    expect(publicTopNav).toContain('authStore.isAuthenticated')
    expect(publicTopNav).toContain('showDashboardButton')
    expect(publicTopNav).toContain("route.path === '/home' || route.path === '/'")
    expect(publicTopNav).toContain('public-auth-button')
    expect(publicTopNav).not.toContain('public-auth-link')
    expect(publicTopNav).toContain('v-if="!isAuthenticated" to="/login"')
    expect(publicTopNav).toContain("t('home.login')")
    expect(publicTopNav).not.toContain("t('auth.signIn')")
    expect(publicTopNav).not.toContain("to=\"/register\"")
    expect(publicTopNav).not.toContain("t('home.claimButton')")
    expect(publicTopNav).toContain("t('home.goToDashboard')")
    expect(publicTopNav).toContain('v-if="showDashboardButton"')
    expect(publicTopNav).not.toContain('showHomeUserName')
    expect(publicTopNav).not.toContain('homeUserName')
    expect(publicTopNav).not.toContain('public-user-chip')
    expect(publicTopNav).toContain("Icon name=\"arrowRight\"")
    expect(publicTopNav).toContain("Icon name=\"book\"")
    expect(publicTopNav).not.toContain("from '@/components/icons/PixelIcon.vue'")
    expect(publicTopNav).not.toContain('<PixelIcon')
    expect(publicTopNav).not.toContain('pixel-glyph')
    expect(publicTopNav).not.toContain('isAuthenticated ? dashboardPath : \'/login\'')
    expect(publicTopNav).not.toContain('navFeatures')
    expect(publicTopNav).not.toContain('toggleTheme')
    expect(publicBackdrop).toContain('public-reveal-backdrop')
    expect(publicBackdrop).toContain('public-reveal-mask')
    expect(publicBackdrop).toContain('mimo-relief-bg.webp')
    expect(publicBackdrop).toContain("ctx.globalCompositeOperation = 'destination-out'")
    expect(publicBackdrop).toContain("window.matchMedia('(hover: hover) and (pointer: fine)')")
    expect(publicBackdrop).not.toContain('useMatrixRain')
    expect(publicCss).toContain('--public-surface')
    expect(publicCss).toContain('--public-border')
    expect(publicCss).toContain('--public-nav-height: 3.75rem')
    expect(publicCss).toContain('padding-top: var(--public-nav-height)')
    expect(publicCss).toContain('--public-bg: #faf9f5')
    expect(publicCss).toContain('--public-bg-soft: #f5f0e8')
    expect(publicCss).toContain('--public-text: #141413')
    expect(publicCss).toContain('--public-accent: #cc785c')
  })

  it('keeps the homepage primary actions and tutorial reader structure stable', () => {
    expect(homeView).toContain('home-action-button')
    expect(homeView).toContain('home-mimo-hero')
    expect(homeView).toContain('home-mimo-title')
    expect(homeView).toContain('home-command-pill')
    expect(homeView).toContain('home-mimo-actions')
    expect(homeView).toContain('to="/tutorial/getting-started"')
    expect(homeView).toContain('home-mimo-title-line-sweep')
    expect(homeView).toContain(':data-title="heroTitleBottom"')
    expect(homeView).toContain('heroDescriptionText')
    expect(homeView).not.toContain('home-mimo-proof')
    expect(homeView).not.toContain('home-typewriter')
    expect(homeView).not.toContain('<PixelIcon')
    expect(homeView).not.toContain('home-product-panel')
    expect(homeView).not.toContain('home-command-preview')
    expect(homeView).not.toContain('home-product-band')
    expect(homeView).not.toContain('home-support-button')
    expect(homeView).not.toContain('home-footer-models')
    expect(homeView).not.toContain('footerModelBadges')
    expect(tutorialView).toContain('class="tutorial-sidebar"')
    expect(tutorialView).toContain('class="tutorial-main-column"')
    expect(tutorialView).toContain('class="tutorial-toc"')
    expect(tutorialView).toContain('tutorial-directory-grid')
    expect(tutorialView).toContain('IntersectionObserver')
    expect(tutorialView).toContain('tutorialFallbackPages')
    expect(tutorialView).toContain('renderTutorialMarkdown(page.content_md, { skipTitle: page.title })')
  })

  it('keeps model plaza discovery controls mounted on the public surface', () => {
    expect(modelPlazaView).toContain('model-toolbar')
    expect(modelPlazaView).toContain('model-card-grid')
    expect(modelPlazaView).toContain('model-market-card')
    expect(modelPlazaView).toContain('model-search-box')
    expect(modelPlazaView).toContain('v-model="searchQuery"')
    expect(modelPlazaView).toContain('model-category-tabs')
    expect(modelPlazaView).toContain('modelMarketAPI.getCatalog')
    expect(modelPlazaView).toContain('groupRateOptions(group)')
    expect(modelPlazaView).toContain('displayOurPrice(group, row.our_price)')
    expect(modelPlazaView).toContain('账号分组')
    expect(modelPlazaView).toContain('模型名称')
    expect(modelPlazaView).toContain('规格')
    expect(modelPlazaView).toContain('我们的价格')
    expect(modelPlazaView).toContain('官方价格')
    expect(modelPlazaView).toContain('节省')
    expect(modelPlazaView).toContain('showOfficialPriceColumn(group)')
    expect(modelPlazaView).toContain('showSavingColumn(group)')
    expect(modelPlazaView).not.toContain('selectedRateGroup"')
    expect(modelPlazaView).not.toContain('userChannelsAPI.getAvailable')
    expect(modelPlazaView).not.toMatch(/APIMart|apimart/i)
  })
})
