import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const router = readFileSync(resolve(process.cwd(), 'src/router/index.ts'), 'utf8')
const tutorialView = readFileSync(resolve(process.cwd(), 'src/views/public/TutorialView.vue'), 'utf8')
const tutorialFallback = readFileSync(resolve(process.cwd(), 'src/views/public/tutorialFallback.ts'), 'utf8')
const tutorialMarkdown = readFileSync(resolve(process.cwd(), 'src/utils/tutorialMarkdown.ts'), 'utf8')
const tutorialAdminView = readFileSync(resolve(process.cwd(), 'src/views/admin/TutorialPagesView.vue'), 'utf8')
const modelMarketAdminView = readFileSync(resolve(process.cwd(), 'src/views/admin/ModelMarketView.vue'), 'utf8')
const tutorialsApi = readFileSync(resolve(process.cwd(), 'src/api/tutorials.ts'), 'utf8')
const adminTutorialsApi = readFileSync(resolve(process.cwd(), 'src/api/admin/tutorials.ts'), 'utf8')
const modelMarketApi = readFileSync(resolve(process.cwd(), 'src/api/modelMarket.ts'), 'utf8')
const adminModelMarketApi = readFileSync(resolve(process.cwd(), 'src/api/admin/modelMarket.ts'), 'utf8')
const adminApiIndex = readFileSync(resolve(process.cwd(), 'src/api/admin/index.ts'), 'utf8')
const sidebar = readFileSync(resolve(process.cwd(), 'src/components/layout/AppSidebar.vue'), 'utf8')
const modelPlazaView = readFileSync(resolve(process.cwd(), 'src/views/public/ModelPlazaView.vue'), 'utf8')
const legalDocumentView = readFileSync(resolve(process.cwd(), 'src/views/public/LegalDocumentView.vue'), 'utf8')
const publicBackdrop = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicMatrixBackdrop.vue'), 'utf8')
const matrixRain = readFileSync(resolve(process.cwd(), 'src/views/public/components/matrixRain.ts'), 'utf8')
const publicTopNav = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicTopNav.vue'), 'utf8')
const publicCss = readFileSync(resolve(process.cwd(), 'src/views/public/public-page.css'), 'utf8')
const sourceSiteBrandPattern = /LMUAI|lmuai|lmu\.ai|TiMi|TIMICC|timicc/i

describe('public tutorial CMS and model plaza pages', () => {
  it('registers tutorial list/detail and model plaza publicly', () => {
    expect(router).toContain("path: '/tutorial'")
    expect(router).toContain("name: 'Tutorial'")
    expect(router).toContain("path: '/tutorial/:slug'")
    expect(router).toContain("name: 'TutorialPage'")
    expect(router).toContain("path: '/models'")
    expect(router).toContain("name: 'ModelPlaza'")
    expect(router).toMatch(/path: '\/models'[\s\S]*?requiresAuth: false/)
    expect(router).toContain("'/tutorial'")
    expect(router).toContain("'/tutorial', '/models'")
    expect(router).toMatch(/BACKEND_MODE_ALLOWED_PATHS[\s\S]*?'\/models'/)
  })

  it('loads published tutorial CMS content with built-in fallback and legacy hash redirects', () => {
    expect(tutorialView).toContain('tutorialsAPI.list()')
    expect(tutorialView).toContain('tutorialsAPI.getBySlug(slug)')
    expect(tutorialView).toContain('tutorialFallbackPages')
    expect(tutorialView).toContain('setFallbackPages')
    expect(tutorialView).toContain('sourceNotice')
    expect(tutorialView).toContain('教程 CMS 暂不可用')
    expect(tutorialView).toContain('后台暂无已发布教程')
    expect(tutorialView).toContain('<template v-else>')
    expect(tutorialView).toContain('legacyHashRedirects')
    expect(tutorialView).toContain("claude: 'claude-code'")
    expect(tutorialView).toContain("ccswitch: 'cc-switch'")
    expect(tutorialView).toContain("router.replace({ path: `/tutorial/${target}`, hash: '' })")
    expect(tutorialView).toContain('resolveLegacyHashTarget()')
    expect(tutorialView).not.toContain('overflow-hidden text-white')
    expect(tutorialView).toContain('isIndexRoute')
    expect(tutorialView).toContain('tutorial-directory-grid')
    expect(tutorialView).toContain('选择一篇教程开始')
    expect(tutorialView.indexOf('a.sort_order !== b.sort_order')).toBeLessThan(
      tutorialView.indexOf('a.category !== b.category')
    )
    expect(tutorialView).toContain('v-html="renderedHtml"')
    expect(tutorialView).toContain('renderTutorialMarkdown(page.content_md, { skipTitle: page.title })')
    expect(tutorialView).toContain('item.level >= 2 && item.level <= 3')
    expect(tutorialView).toContain("querySelectorAll<HTMLElement>('h2[id], h3[id]')")
    expect(tutorialView).toContain('aria-label="接入教程目录"')
    expect(tutorialView).toContain('aria-label="当前文章目录"')
    expect(tutorialView).toContain('IntersectionObserver')
    expect(tutorialView).toContain('scrollIntoView')
    expect(tutorialView).toContain('class="tutorial-sidebar"')
    expect(tutorialView).toContain('class="tutorial-main-column"')
    expect(tutorialView).toContain('class="tutorial-toc"')
    expect(tutorialView).toContain('class="tutorial-tab-link"')
    expect(tutorialView).toContain('top: var(--tutorial-sticky-top, 5rem)')
    expect(tutorialView).toContain('width: min(100%, 104rem)')
    expect(tutorialView).toContain('grid-template-columns: 18rem minmax(0, 1fr)')
    expect(tutorialView).toContain('grid-template-columns: minmax(0, 1fr) 12rem')
    expect(tutorialView).toContain('.tutorial-content :deep(a)')
    expect(tutorialView).toContain('.tutorial-content :deep(.guide-action-link)')
    expect(tutorialView).toContain('text-decoration-line: underline')
    expect(tutorialView).toContain('text-underline-offset: 0.18em')
    expect(tutorialView).toContain('copy-command-button')
    expect(tutorialView).toContain('navigator.clipboard')
    expect(tutorialView).toContain('imagePreview')
    expect(tutorialView).toContain('tutorial-image-lightbox')
    expect(tutorialView).toContain('closeImagePreview')
    expect(tutorialView).toContain('cursor: zoom-in')
    expect(tutorialView).toContain('width: min(100%, 48rem)')
    expect(tutorialView).toContain('<PublicTopNav />')
    expect(tutorialView).toContain('<PublicMatrixBackdrop />')
    expect(tutorialsApi).toContain("apiClient.get<{ items: TutorialPageSummary[] }>('/tutorials')")
    expect(tutorialsApi).toContain("`/tutorials/${encodeURIComponent(slug)}`")
  })

  it('keeps default tutorial seeds local to Luoye wording and shortcode-ready', () => {
    for (const slug of [
      'getting-started',
      'codex',
      'claude-code',
      'cc-switch',
      'cockpit-tools',
      'recover-codex-session',
      'minepilotqa',
      'openclaw',
      'hermes-agent',
      'faq'
    ]) {
      expect(tutorialFallback).toContain(`slug: '${slug}'`)
    }
    expect(tutorialFallback).toContain('落叶网络控制台')
    expect(tutorialFallback).toContain('https://ai.3zapi.top/v1')
    expect(tutorialFallback).toContain('按下面 4 步完成第一次接入')
    expect(tutorialFallback).toContain('1. 安装或打开 Codex App。')
    expect(tutorialFallback).toContain('## 安装 Codex App')
    expect(tutorialFallback).toContain('## Linux / macOS 安装 Codex CLI')
    expect(tutorialFallback).toContain('https://github.com/openai/codex/releases')
    expect(tutorialFallback).toContain('Linux 常见架构是 x86_64 或 arm64')
    expect(tutorialFallback).toContain('## 下一步：Codex 配置')
    expect(tutorialFallback).toContain('## 第一步：找到 Codex 配置文件夹')
    expect(tutorialFallback).toContain('不是项目目录，也不是浏览器下载目录')
    expect(tutorialFallback).toContain('mkdir $env:USERPROFILE\\.codex -Force')
    expect(tutorialFallback).toContain('nano ~/.codex/config.toml')
    expect(tutorialFallback).toContain('注意不要变成 config.toml.txt')
    expect(tutorialFallback).toContain('nano ~/.codex/auth.json')
    expect(tutorialFallback).toContain('## 启动验证')
    expect(tutorialFallback).toContain('wire_api = "responses"')
    expect(tutorialFallback).toContain('替换成你的 codex 类型 API Key')
    expect(tutorialFallback).toContain('OpenAI 兼容地址必须写 \\`https://ai.3zapi.top/v1\\`')
    expect(tutorialFallback).toContain('npm 安装路径需要 Node.js 18+')
    expect(tutorialFallback).toContain('查看恢复历史会话')
    expect(tutorialFallback).toContain('# 恢复历史会话')
    expect(tutorialFallback).toContain('## 操作步骤')
    expect(tutorialFallback).toContain('点击左侧 Codex 图标')
    expect(tutorialFallback).toContain('点击顶部的会话管理')
    expect(tutorialFallback).toContain('点击修复可见性')
    expect(tutorialFallback).toContain('回到 Codex App，刷新或重新打开会话列表')
    expect(tutorialFallback).toContain('/tutorial/cockpit-tools/codex-sidebar.png')
    expect(tutorialFallback).toContain('/tutorial/cockpit-tools/session-visibility.png')
    expect(tutorialView).toContain("'recover-codex-session': 'recover-codex-session'")
    expect(tutorialView).toContain('justify-content: space-between')
    expect(tutorialView).toContain('text-overflow: ellipsis')
    expect(tutorialFallback).not.toContain('按需验证开发工具')
    expect(tutorialFallback).not.toContain('第一次接入先按新手最快路线走，只需要准备账号')
    expect(tutorialFallback).not.toContain('Git 和 Node.js 不属于 Codex App 的启动前置条件')
    expect(tutorialFallback).not.toContain('1. 安装 Git 和 Node.js。')
    expect(tutorialFallback).not.toContain('Node.js v18 或更高版本。')
    expect(tutorialFallback).toContain('[[command')
    expect(tutorialFallback).toContain('[[screenshot')
    expect(tutorialFallback).toContain('[[callout')
    expect(tutorialFallback).toContain('[[link-button')
    expect(tutorialFallback).toContain('/tutorial/minepilotqa/provider-list.png')
    expect(tutorialFallback).not.toMatch(sourceSiteBrandPattern)
    expect(tutorialView).not.toMatch(sourceSiteBrandPattern)
  })

  it('sanitizes Markdown and renders the minimal tutorial shortcode set', () => {
    expect(tutorialMarkdown).toContain("import DOMPurify from 'dompurify'")
    expect(tutorialMarkdown).toContain('DOMPurify.sanitize')
    expect(tutorialMarkdown).toContain('marked.parse')
    expect(tutorialMarkdown).toContain('renderShortcodes')
    expect(tutorialMarkdown).toContain('TUTORIAL_SHORTCODE_')
    expect(tutorialMarkdown).toContain('preserveBlock')
    expect(tutorialMarkdown).toContain('skipTitle?: string')
    expect(tutorialMarkdown).toContain('text === skipTitle')
    expect(tutorialMarkdown).toContain('tutorial-command-block command-block')
    expect(tutorialMarkdown).toContain('data-copy-code')
    expect(tutorialMarkdown).toContain('tutorial-callout tutorial-callout-')
    expect(tutorialMarkdown).toContain('tutorial-screenshot-card')
    expect(tutorialMarkdown).toContain('guide-action-link')
    expect(tutorialMarkdown).toContain('generateHeadingId')
  })

  it('adds an admin tutorial editor that is independent from custom menu pages', () => {
    expect(router).toContain("path: '/admin/tutorials'")
    expect(router).toContain("name: 'AdminTutorialPages'")
    expect(router).toContain("import('@/views/admin/TutorialPagesView.vue')")
    expect(sidebar).toContain("{ path: '/admin/tutorials', label: t('nav.tutorials'), icon: ContentIcon }")
    expect(tutorialAdminView).toContain('adminAPI.tutorials.list')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.getById')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.create')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.update')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.updateStatus')
    expect(tutorialAdminView).toContain('adminAPI.tutorials.delete')
    expect(tutorialAdminView).toContain('Markdown + 短代码')
    expect(tutorialAdminView).toContain('预览')
    expect(tutorialAdminView).toContain('renderTutorialMarkdown(form.content_md).html')
    expect(tutorialAdminView).toContain('[[command]]、[[screenshot]]、[[callout]]、[[link-button]]')
    expect(tutorialAdminView).toContain('showStatusDialog')
    expect(tutorialAdminView).toContain('requestStatusChange(row)')
    expect(tutorialAdminView).toContain('rowBusyId')
    expect(tutorialAdminView).toContain('showDiscardDialog')
    expect(tutorialAdminView).toContain('isFormDirty')
    expect(tutorialAdminView).toContain('requestCloseEdit')
    expect(tutorialAdminView).toContain('tutorial-load-error')
    expect(tutorialAdminView).toContain('row.status === \'published\'')
    expect(adminTutorialsApi).toContain("apiClient.get<BasePaginationResponse<TutorialPageSummary>>('/admin/tutorials'")
    expect(adminTutorialsApi).toContain("`/admin/tutorials/${id}/status`")
    expect(adminTutorialsApi).toContain('deleteTutorial')
    expect(tutorialAdminView).not.toContain('custom_menu_items')
  })

  it('adds a public model plaza with searchable pricing tables', () => {
    expect(modelPlazaView).toContain('Pricing Center')
    expect(modelPlazaView).toContain('模型定价')
    expect(modelPlazaView).toContain('公开展示推理、图像和视频模型价格')
    expect(modelPlazaView).toContain('model-toolbar')
    expect(modelPlazaView).toContain('model-search-box')
    expect(modelPlazaView).toContain('v-model="searchQuery"')
    expect(modelPlazaView).toContain('model-category-tabs')
    expect(modelPlazaView).not.toContain('model-stat-grid')
    expect(modelPlazaView).not.toContain('模型总数')
    expect(modelPlazaView).toContain('model-card-grid')
    expect(modelPlazaView).toContain('model-market-card')
    expect(modelPlazaView).toContain('model-pricing-table')
    expect(modelPlazaView).toContain('modelMarketAPI.getCatalog')
    expect(modelPlazaView).toContain("from '@/api/modelMarket'")
    expect(modelPlazaView).toContain('enabledGroups')
    expect(modelPlazaView).toContain('visibleGroups')
    expect(modelPlazaView).toContain('enabledRows(group)')
    expect(modelPlazaView).toContain('groupRateOptions(group)')
    expect(modelPlazaView).toContain('selectedRateGroupIds')
    expect(modelPlazaView).toContain('selectedRateMultiplier(group)')
    expect(modelPlazaView).toContain('groupPriceMultiplier(group) * selectedRateMultiplier(group)')
    expect(modelPlazaView).toContain('group.price_multiplier ?? 1')
    expect(modelPlazaView).toContain('displayOurPrice(group, row.our_price)')
    expect(modelPlazaView).toContain("import { CREDIT_SYMBOL } from '@/utils/credits'")
    expect(modelPlazaView).toContain('price.replace(/[¥￥$]/g, CREDIT_SYMBOL)')
    expect(modelPlazaView).toContain('multiplyPriceText')
    expect(modelPlazaView).toContain('effective_rate_multiplier')
    expect(modelPlazaView).toContain('账号分组')
    expect(modelPlazaView).toContain('hasScrollableRows(group)')
    expect(modelPlazaView).toContain("'is-scrollable': hasScrollableRows(group)")
    expect(modelPlazaView).toContain('model-table-shell')
    expect(modelPlazaView).toContain('.model-table-wrap.is-scrollable')
    expect(modelPlazaView).toContain('max-height: 34rem')
    expect(modelPlazaView).toContain('overflow-y: scroll')
    expect(modelPlazaView).toContain('scrollbar-width: none')
    expect(modelPlazaView).toContain('-ms-overflow-style: none')
    expect(modelPlazaView).toContain('width: 0')
    expect(modelPlazaView).toContain('@scroll="updateScrollIndicator(group.id, $event)"')
    expect(modelPlazaView).toContain('@pointerdown="handleScrollbarRailPointerDown(group.id, $event)"')
    expect(modelPlazaView).toContain('@pointerdown.stop="handleScrollbarThumbPointerDown(group.id, $event)"')
    expect(modelPlazaView).toContain('model-scrollbar-rail')
    expect(modelPlazaView).toContain('model-scrollbar-thumb')
    expect(modelPlazaView).toContain('scrollThumbStyle(group.id)')
    expect(modelPlazaView).toContain('pointer-events: auto')
    expect(modelPlazaView).toContain('cursor: grab')
    expect(modelPlazaView).toContain('refreshScrollIndicators')
    expect(modelPlazaView).toContain('position: sticky')
    expect(modelPlazaView).toContain("group.category === 'chat'")
    expect(modelPlazaView).toContain('模型名称')
    expect(modelPlazaView).toContain('输入')
    expect(modelPlazaView).toContain('输出')
    expect(modelPlazaView).toContain('规格')
    expect(modelPlazaView).toContain('我们的价格')
    expect(modelPlazaView).toContain('官方价格')
    expect(modelPlazaView).toContain('节省')
    expect(modelPlazaView).toContain('showOfficialPriceColumn(group)')
    expect(modelPlazaView).toContain('showSavingColumn(group)')
    expect(modelPlazaView).toContain('group.hide_official_price')
    expect(modelPlazaView).toContain('group.hide_saving')
    expect(modelPlazaView).toContain('enabledRows(group).some((row) => !!row.official_price)')
    expect(modelPlazaView).toContain('enabledRows(group).some((row) => !!row.saving)')
    expect(modelPlazaView).toContain('实际扣费以控制台使用记录为准')
    expect(modelPlazaView).not.toContain('userChannelsAPI.getAvailable')
    expect(modelPlazaView).not.toContain('userGroupsAPI.getUserGroupRates')
    expect(modelPlazaView).not.toContain('fallbackChannels')
    expect(modelPlazaView).not.toContain('selectedRateGroup"')
    expect(modelPlazaView).not.toContain('显示倍率价格')
    expect(modelPlazaView).not.toContain('reference_pricing')
    expect(modelMarketApi).toContain("apiClient.get<ModelMarketCatalog>('/model-market/catalog'")
    expect(modelPlazaView).not.toMatch(sourceSiteBrandPattern)
    expect(modelPlazaView).not.toMatch(/APIMart|apimart/i)
  })

  it('adds an admin model market editor backed by JSON catalog APIs', () => {
    expect(router).toContain("path: '/admin/model-market'")
    expect(router).toContain("name: 'AdminModelMarket'")
    expect(router).toContain("import('@/views/admin/ModelMarketView.vue')")
    expect(sidebar).toContain("{ path: '/admin/model-market', label: t('nav.modelMarket'), icon: PriceTagIcon }")
    expect(modelMarketAdminView).toContain('adminAPI.modelMarket.getCatalog')
    expect(modelMarketAdminView).toContain('adminAPI.modelMarket.updateCatalog')
    expect(modelMarketAdminView).toContain('adminAPI.modelMarket.resetCatalog')
    expect(modelMarketAdminView).toContain('JSON 导入 / 导出')
    expect(modelMarketAdminView).toContain('JSON 工具')
    expect(modelMarketAdminView).toContain('应用 JSON')
    expect(modelMarketAdminView).toContain('model-market-json-panel')
    expect(modelMarketAdminView).toContain('模型名称')
    expect(modelMarketAdminView).toContain('规格')
    expect(modelMarketAdminView).toContain('我们的价格')
    expect(modelMarketAdminView).toContain('官方价格')
    expect(modelMarketAdminView).toContain('隐藏官方价格列')
    expect(modelMarketAdminView).toContain('隐藏节省列')
    expect(modelMarketAdminView).toContain('价格倍率')
    expect(modelMarketAdminView).toContain('v-model.number="selectedGroup.price_multiplier"')
    expect(modelMarketAdminView).toContain('normalizePriceMultiplier(group.price_multiplier)')
    expect(modelMarketAdminView).toContain('支持的账号分组')
    expect(modelMarketAdminView).toContain('adminAPI.groups.getAll')
    expect(modelMarketAdminView).toContain('toggleSupportedGroup')
    expect(modelMarketAdminView).toContain('formatRateLabel')
    expect(modelMarketAdminView).toContain('showOfficialPriceEditor')
    expect(modelMarketAdminView).toContain('showSavingEditor')
    expect(modelMarketAdminView).toContain('model-market-group-list')
    expect(modelMarketAdminView).toContain('model-market-group-drag-handle')
    expect(modelMarketAdminView).toContain('handleGroupsReordered')
    expect(modelMarketAdminView).toContain('moveGroup(index, -1)')
    expect(modelMarketAdminView).toContain('normalizeGroupOrder')
    expect(modelMarketAdminView).toContain('model-market-row-table-wrap')
    expect(modelMarketAdminView).toContain('overflow-y: auto')
    expect(modelMarketAdminView).toContain('overflow: auto')
    expect(modelMarketAdminView).toContain('position: sticky')
    expect(adminModelMarketApi).toContain("apiClient.get<ModelMarketCatalog>('/admin/model-market/catalog')")
    expect(adminModelMarketApi).toContain("apiClient.put<ModelMarketCatalog>('/admin/model-market/catalog', catalog)")
    expect(adminModelMarketApi).toContain("apiClient.post<ModelMarketCatalog>('/admin/model-market/catalog/reset')")
    expect(adminApiIndex).toContain('modelMarket: modelMarketAdminAPI')
    expect(modelMarketAdminView).not.toMatch(/APIMart|apimart/i)
    expect(modelMarketApi).toContain('price_multiplier?: number')
  })

  it('shares the public matrix visual treatment on public content pages', () => {
    expect(tutorialView).toContain('PublicMatrixBackdrop')
    expect(modelPlazaView).toContain('PublicMatrixBackdrop')
    expect(legalDocumentView).toContain('PublicMatrixBackdrop')
    expect(modelPlazaView).toContain("from './components/PublicMatrixBackdrop.vue'")
    expect(publicBackdrop).toContain('public-matrix-rain')
    expect(publicBackdrop).toContain('const matrixColumnCount = 42')
    expect(publicBackdrop).toContain('useMatrixRain(matrixColumnCount, 620)')
    expect(matrixRain).toContain('refreshMatrixColumns')
    expect(matrixRain).toContain('randomMatrixText')
    expect(matrixRain).toContain('prefers-reduced-motion: reduce')
    expect(publicCss).toContain('.public-page-shell')
    expect(modelPlazaView).toContain('linear-gradient(180deg, #050914 0%, #08110f 48%, #03060a 100%)')
    expect(modelPlazaView).not.toContain('linear-gradient(135deg, #e8f4f3 0%, #eef2f2 48%, #dfe9ea 100%)')
  })

  it('uses one shared public top navigation across public pages and highlights tutorial detail routes', () => {
    expect(tutorialView).toContain("from './components/PublicTopNav.vue'")
    expect(modelPlazaView).toContain("from './components/PublicTopNav.vue'")
    expect(legalDocumentView).toContain("from './components/PublicTopNav.vue'")
    expect(publicTopNav).toContain('public-top-shell')
    expect(publicTopNav).toContain('public-nav-center')
    expect(publicTopNav).toContain('public-mobile-nav')
    expect(publicTopNav).toContain('public-nav-button')
    expect(publicTopNav).toContain('<nav class="public-top-nav">')
    expect(publicTopNav).toContain('padding: 0.45rem clamp(1rem, 3vw, 3rem)')
    expect(publicTopNav).toContain('justify-content: flex-end')
    expect(publicTopNav).toContain('position: sticky')
    expect(publicTopNav).toContain('authStore.isAuthenticated')
    expect(publicTopNav).toContain("isAuthenticated ? dashboardPath : '/login'")
    expect(publicTopNav).toContain('isNavItemActive(item)')
    expect(publicTopNav).toContain("route.path.startsWith(`${path}/`)")
    expect(publicTopNav).toContain("to: '/tutorial'")
    expect(publicTopNav).toContain("to: '/models'")
    expect(publicTopNav).toContain("t('home.navContact')")
    expect(publicTopNav).toContain('openSupportPopup')
    expect(publicTopNav).not.toContain('navFeatures')
    expect(publicTopNav).not.toContain('功能特性')
    expect(publicTopNav).not.toContain('#features')
    expect(publicTopNav).not.toContain('toggleTheme')
    expect(publicTopNav).not.toContain('switchToLight')
    expect(publicTopNav).not.toContain('switchToDark')
    expect(publicCss).not.toContain('.public-page-header')
    expect(modelPlazaView).not.toContain('model-plaza-topbar')
  })

  it('opens login agreement documents by configured id or document title', () => {
    expect(router).toContain("path: '/legal/:documentId'")
    expect(router).toContain("name: 'LegalDocument'")
    expect(legalDocumentView).toContain('login_agreement_documents')
    expect(legalDocumentView).toContain('(doc.id || doc.title) === id')
    expect(legalDocumentView).toContain('class="legal-document-page public-page-shell')
    expect(legalDocumentView).toContain('appStore.fetchPublicSettings()')
    expect(legalDocumentView).toContain('documentBodyMarkdown')
    expect(legalDocumentView).toContain("replace(/^#{1,6}\\s+/, '').trim()")
    expect(legalDocumentView).not.toContain('mc-pixel-grid')
    expect(legalDocumentView).not.toContain("from '@/api/auth'")
  })
})
