import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const router = readFileSync(resolve(process.cwd(), 'src/router/index.ts'), 'utf8')
const homeView = readFileSync(resolve(process.cwd(), 'src/views/HomeView.vue'), 'utf8')
const tutorialView = readFileSync(resolve(process.cwd(), 'src/views/public/TutorialView.vue'), 'utf8')
const modelPlazaView = readFileSync(resolve(process.cwd(), 'src/views/public/ModelPlazaView.vue'), 'utf8')
const publicTopNav = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicTopNav.vue'), 'utf8')
const publicBackdrop = readFileSync(resolve(process.cwd(), 'src/views/public/components/PublicMatrixBackdrop.vue'), 'utf8')
const publicCss = readFileSync(resolve(process.cwd(), 'src/views/public/public-page.css'), 'utf8')

describe('public page smoke contracts', () => {
  it('keeps public entry routes and opens model plaza without login', () => {
    expect(router).toContain("path: '/home'")
    expect(router).toContain("path: '/tutorial'")
    expect(router).toContain("path: '/tutorial/:slug'")
    expect(router).toContain("path: '/models'")
    expect(router).toContain("name: 'Home'")
    expect(router).toContain("name: 'Tutorial'")
    expect(router).toContain("name: 'ModelPlaza'")
    expect(router).toMatch(/path: '\/models'[\s\S]*?requiresAuth: false/)
    expect(router).toContain("'/tutorial', '/models'")
    expect(router).toMatch(/BACKEND_MODE_ALLOWED_PATHS[\s\S]*?'\/models'/)
  })

  it('routes chat image entry to the Luoye Creative launch workspace', () => {
    expect(router).toContain("path: '/chat-images'")
    expect(router).toContain("alias: '/studio-bridge/launch'")
    expect(router).toContain("name: 'ChatImageStudio'")
    expect(router).toContain("import('@/views/user/LuoyeAILaunchView.vue')")
    expect(router).not.toContain("path: '/canvas'")
    expect(router).not.toContain("name: 'CanvasStudio'")
    expect(router).toContain("path: '/image-manager'")
    expect(router).toContain("name: 'ImageManager'")
    expect(router).toContain("import('@/views/user/ImageManagerView.vue')")
    expect(router).toContain("path: '/chat-images/native'")
    expect(router).toContain("name: 'ChatImageStudioNative'")
    expect(router).toContain("import('@/views/user/ChatImageStudioView.vue')")
  })

  it('uses one shared navigation and matrix surface across public pages', () => {
    expect(homeView).toContain('<PublicTopNav />')
    expect(tutorialView).toContain('<PublicTopNav />')
    expect(modelPlazaView).toContain('<PublicTopNav />')
    expect(tutorialView).toContain('<PublicMatrixBackdrop />')
    expect(modelPlazaView).toContain('<PublicMatrixBackdrop />')
    expect(publicTopNav).toContain('public-top-shell')
    expect(publicTopNav).toContain('public-nav-button')
    expect(publicTopNav).toContain('<nav class="public-top-nav">')
    expect(publicTopNav).toContain('justify-content: flex-end')
    expect(publicTopNav).toContain("to: '/home'")
    expect(publicTopNav).toContain("to: '/tutorial'")
    expect(publicTopNav).toContain("to: '/models'")
    expect(publicTopNav).toContain("t('home.navContact')")
    expect(publicTopNav).toContain('openSupportPopup')
    expect(publicTopNav).toContain('isAuthenticated ? dashboardPath : \'/login\'')
    expect(publicTopNav).not.toContain('navFeatures')
    expect(publicTopNav).not.toContain('toggleTheme')
    expect(publicBackdrop).toContain('public-matrix-rain')
    expect(publicCss).toContain('--public-surface')
    expect(publicCss).toContain('--public-border')
  })

  it('keeps the homepage primary actions and tutorial reader structure stable', () => {
    expect(homeView).toContain('home-claim-button')
    expect(homeView).not.toContain('home-support-button')
    expect(homeView).not.toContain('home-footer-models')
    expect(homeView).not.toContain('footerModelBadges')
    expect(tutorialView).toContain('class="tutorial-sidebar"')
    expect(tutorialView).toContain('class="tutorial-main-column"')
    expect(tutorialView).toContain('class="tutorial-toc"')
    expect(tutorialView).toContain('tutorial-directory-grid')
    expect(tutorialView).toContain('IntersectionObserver')
    expect(tutorialView).toContain('tutorialFallbackPages')
    expect(tutorialView).toContain('renderTutorialMarkdown(page.content_md, { skipTitle: page.title })')
  })

  it('keeps model plaza discovery controls mounted on the public surface', () => {
    expect(modelPlazaView).toContain('model-toolbar')
    expect(modelPlazaView).toContain('model-card-grid')
    expect(modelPlazaView).toContain('model-market-card')
    expect(modelPlazaView).toContain('model-search-box')
    expect(modelPlazaView).toContain('v-model="searchQuery"')
    expect(modelPlazaView).toContain('model-category-tabs')
    expect(modelPlazaView).toContain('modelMarketAPI.getCatalog')
    expect(modelPlazaView).toContain('groupRateOptions(group)')
    expect(modelPlazaView).toContain('displayOurPrice(group, row.our_price)')
    expect(modelPlazaView).toContain('账号分组')
    expect(modelPlazaView).toContain('模型名称')
    expect(modelPlazaView).toContain('规格')
    expect(modelPlazaView).toContain('我们的价格')
    expect(modelPlazaView).toContain('官方价格')
    expect(modelPlazaView).toContain('节省')
    expect(modelPlazaView).toContain('showOfficialPriceColumn(group)')
    expect(modelPlazaView).toContain('showSavingColumn(group)')
    expect(modelPlazaView).not.toContain('selectedRateGroup"')
    expect(modelPlazaView).not.toContain('userChannelsAPI.getAvailable')
    expect(modelPlazaView).not.toMatch(/APIMart|apimart/i)
  })
})
