// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/caferoom"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyplan"
)

// CafeRoom is the model entity for the CafeRoom schema.
type CafeRoom struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID int64 `json:"plan_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// ZoneKey holds the value of the "zone_key" field.
	ZoneKey string `json:"zone_key,omitempty"`
	// ThemeKey holds the value of the "theme_key" field.
	ThemeKey string `json:"theme_key,omitempty"`
	// SceneSlotKey holds the value of the "scene_slot_key" field.
	SceneSlotKey string `json:"scene_slot_key,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Featured holds the value of the "featured" field.
	Featured bool `json:"featured,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CafeRoomQuery when eager-loading is set.
	Edges            CafeRoomEdges `json:"edges"`
	group_cafe_rooms *int64
	selectValues     sql.SelectValues
}

// CafeRoomEdges holds the relations/edges for other nodes in the graph.
type CafeRoomEdges struct {
	// Plan holds the value of the plan edge.
	Plan *GroupBuyPlan `json:"plan,omitempty"`
	// Account holds the value of the account edge.
	Account *Account `json:"account,omitempty"`
	// Rounds holds the value of the rounds edge.
	Rounds []*GroupBuyRound `json:"rounds,omitempty"`
	// AccountBindings holds the value of the account_bindings edge.
	AccountBindings []*APIKeyAccountBinding `json:"account_bindings,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CafeRoomEdges) PlanOrErr() (*GroupBuyPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: groupbuyplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// AccountOrErr returns the Account value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e CafeRoomEdges) AccountOrErr() (*Account, error) {
	if e.Account != nil {
		return e.Account, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "account"}
}

// RoundsOrErr returns the Rounds value or an error if the edge
// was not loaded in eager-loading.
func (e CafeRoomEdges) RoundsOrErr() ([]*GroupBuyRound, error) {
	if e.loadedTypes[2] {
		return e.Rounds, nil
	}
	return nil, &NotLoadedError{edge: "rounds"}
}

// AccountBindingsOrErr returns the AccountBindings value or an error if the edge
// was not loaded in eager-loading.
func (e CafeRoomEdges) AccountBindingsOrErr() ([]*APIKeyAccountBinding, error) {
	if e.loadedTypes[3] {
		return e.AccountBindings, nil
	}
	return nil, &NotLoadedError{edge: "account_bindings"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CafeRoom) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case caferoom.FieldMetadata:
			values[i] = new([]byte)
		case caferoom.FieldFeatured:
			values[i] = new(sql.NullBool)
		case caferoom.FieldID, caferoom.FieldPlanID, caferoom.FieldAccountID, caferoom.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case caferoom.FieldCode, caferoom.FieldName, caferoom.FieldZoneKey, caferoom.FieldThemeKey, caferoom.FieldSceneSlotKey, caferoom.FieldStatus:
			values[i] = new(sql.NullString)
		case caferoom.FieldCreatedAt, caferoom.FieldUpdatedAt, caferoom.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case caferoom.ForeignKeys[0]: // group_cafe_rooms
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CafeRoom fields.
func (_m *CafeRoom) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case caferoom.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case caferoom.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case caferoom.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case caferoom.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case caferoom.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case caferoom.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case caferoom.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case caferoom.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case caferoom.FieldZoneKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field zone_key", values[i])
			} else if value.Valid {
				_m.ZoneKey = value.String
			}
		case caferoom.FieldThemeKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field theme_key", values[i])
			} else if value.Valid {
				_m.ThemeKey = value.String
			}
		case caferoom.FieldSceneSlotKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scene_slot_key", values[i])
			} else if value.Valid {
				_m.SceneSlotKey = value.String
			}
		case caferoom.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case caferoom.FieldFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field featured", values[i])
			} else if value.Valid {
				_m.Featured = value.Bool
			}
		case caferoom.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case caferoom.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case caferoom.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field group_cafe_rooms", value)
			} else if value.Valid {
				_m.group_cafe_rooms = new(int64)
				*_m.group_cafe_rooms = int64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CafeRoom.
// This includes values selected through modifiers, order, etc.
func (_m *CafeRoom) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the CafeRoom entity.
func (_m *CafeRoom) QueryPlan() *GroupBuyPlanQuery {
	return NewCafeRoomClient(_m.config).QueryPlan(_m)
}

// QueryAccount queries the "account" edge of the CafeRoom entity.
func (_m *CafeRoom) QueryAccount() *AccountQuery {
	return NewCafeRoomClient(_m.config).QueryAccount(_m)
}

// QueryRounds queries the "rounds" edge of the CafeRoom entity.
func (_m *CafeRoom) QueryRounds() *GroupBuyRoundQuery {
	return NewCafeRoomClient(_m.config).QueryRounds(_m)
}

// QueryAccountBindings queries the "account_bindings" edge of the CafeRoom entity.
func (_m *CafeRoom) QueryAccountBindings() *APIKeyAccountBindingQuery {
	return NewCafeRoomClient(_m.config).QueryAccountBindings(_m)
}

// Update returns a builder for updating this CafeRoom.
// Note that you need to call CafeRoom.Unwrap() before calling this method if this CafeRoom
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CafeRoom) Update() *CafeRoomUpdateOne {
	return NewCafeRoomClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CafeRoom entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CafeRoom) Unwrap() *CafeRoom {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CafeRoom is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CafeRoom) String() string {
	var builder strings.Builder
	builder.WriteString("CafeRoom(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("zone_key=")
	builder.WriteString(_m.ZoneKey)
	builder.WriteString(", ")
	builder.WriteString("theme_key=")
	builder.WriteString(_m.ThemeKey)
	builder.WriteString(", ")
	builder.WriteString("scene_slot_key=")
	builder.WriteString(_m.SceneSlotKey)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("featured=")
	builder.WriteString(fmt.Sprintf("%v", _m.Featured))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// CafeRooms is a parsable slice of CafeRoom.
type CafeRooms []*CafeRoom
