// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyentitlement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// GroupBuyEntitlementQuery is the builder for querying GroupBuyEntitlement entities.
type GroupBuyEntitlementQuery struct {
	config
	ctx                     *QueryContext
	order                   []groupbuyentitlement.OrderOption
	inters                  []Interceptor
	predicates              []predicate.GroupBuyEntitlement
	withUser                *UserQuery
	withTargetGroup         *GroupQuery
	withSubscription        *UserSubscriptionQuery
	withManagedSubscription *UserSubscriptionQuery
	withBoundAPIKey         *APIKeyQuery
	modifiers               []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupBuyEntitlementQuery builder.
func (_q *GroupBuyEntitlementQuery) Where(ps ...predicate.GroupBuyEntitlement) *GroupBuyEntitlementQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GroupBuyEntitlementQuery) Limit(limit int) *GroupBuyEntitlementQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GroupBuyEntitlementQuery) Offset(offset int) *GroupBuyEntitlementQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GroupBuyEntitlementQuery) Unique(unique bool) *GroupBuyEntitlementQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GroupBuyEntitlementQuery) Order(o ...groupbuyentitlement.OrderOption) *GroupBuyEntitlementQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *GroupBuyEntitlementQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyentitlement.Table, groupbuyentitlement.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyentitlement.UserTable, groupbuyentitlement.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTargetGroup chains the current query on the "target_group" edge.
func (_q *GroupBuyEntitlementQuery) QueryTargetGroup() *GroupQuery {
	query := (&GroupClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyentitlement.Table, groupbuyentitlement.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyentitlement.TargetGroupTable, groupbuyentitlement.TargetGroupColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscription chains the current query on the "subscription" edge.
func (_q *GroupBuyEntitlementQuery) QuerySubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyentitlement.Table, groupbuyentitlement.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyentitlement.SubscriptionTable, groupbuyentitlement.SubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryManagedSubscription chains the current query on the "managed_subscription" edge.
func (_q *GroupBuyEntitlementQuery) QueryManagedSubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyentitlement.Table, groupbuyentitlement.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyentitlement.ManagedSubscriptionTable, groupbuyentitlement.ManagedSubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBoundAPIKey chains the current query on the "bound_api_key" edge.
func (_q *GroupBuyEntitlementQuery) QueryBoundAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyentitlement.Table, groupbuyentitlement.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyentitlement.BoundAPIKeyTable, groupbuyentitlement.BoundAPIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupBuyEntitlement entity from the query.
// Returns a *NotFoundError when no GroupBuyEntitlement was found.
func (_q *GroupBuyEntitlementQuery) First(ctx context.Context) (*GroupBuyEntitlement, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupbuyentitlement.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) FirstX(ctx context.Context) *GroupBuyEntitlement {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupBuyEntitlement ID from the query.
// Returns a *NotFoundError when no GroupBuyEntitlement ID was found.
func (_q *GroupBuyEntitlementQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupbuyentitlement.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupBuyEntitlement entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupBuyEntitlement entity is found.
// Returns a *NotFoundError when no GroupBuyEntitlement entities are found.
func (_q *GroupBuyEntitlementQuery) Only(ctx context.Context) (*GroupBuyEntitlement, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupbuyentitlement.Label}
	default:
		return nil, &NotSingularError{groupbuyentitlement.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) OnlyX(ctx context.Context) *GroupBuyEntitlement {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupBuyEntitlement ID in the query.
// Returns a *NotSingularError when more than one GroupBuyEntitlement ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GroupBuyEntitlementQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupbuyentitlement.Label}
	default:
		err = &NotSingularError{groupbuyentitlement.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupBuyEntitlements.
func (_q *GroupBuyEntitlementQuery) All(ctx context.Context) ([]*GroupBuyEntitlement, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GroupBuyEntitlement, *GroupBuyEntitlementQuery]()
	return withInterceptors[[]*GroupBuyEntitlement](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) AllX(ctx context.Context) []*GroupBuyEntitlement {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupBuyEntitlement IDs.
func (_q *GroupBuyEntitlementQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(groupbuyentitlement.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GroupBuyEntitlementQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GroupBuyEntitlementQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GroupBuyEntitlementQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GroupBuyEntitlementQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupBuyEntitlementQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GroupBuyEntitlementQuery) Clone() *GroupBuyEntitlementQuery {
	if _q == nil {
		return nil
	}
	return &GroupBuyEntitlementQuery{
		config:                  _q.config,
		ctx:                     _q.ctx.Clone(),
		order:                   append([]groupbuyentitlement.OrderOption{}, _q.order...),
		inters:                  append([]Interceptor{}, _q.inters...),
		predicates:              append([]predicate.GroupBuyEntitlement{}, _q.predicates...),
		withUser:                _q.withUser.Clone(),
		withTargetGroup:         _q.withTargetGroup.Clone(),
		withSubscription:        _q.withSubscription.Clone(),
		withManagedSubscription: _q.withManagedSubscription.Clone(),
		withBoundAPIKey:         _q.withBoundAPIKey.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuyEntitlementQuery) WithUser(opts ...func(*UserQuery)) *GroupBuyEntitlementQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithTargetGroup tells the query-builder to eager-load the nodes that are connected to
// the "target_group" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuyEntitlementQuery) WithTargetGroup(opts ...func(*GroupQuery)) *GroupBuyEntitlementQuery {
	query := (&GroupClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withTargetGroup = query
	return _q
}

// WithSubscription tells the query-builder to eager-load the nodes that are connected to
// the "subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuyEntitlementQuery) WithSubscription(opts ...func(*UserSubscriptionQuery)) *GroupBuyEntitlementQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscription = query
	return _q
}

// WithManagedSubscription tells the query-builder to eager-load the nodes that are connected to
// the "managed_subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuyEntitlementQuery) WithManagedSubscription(opts ...func(*UserSubscriptionQuery)) *GroupBuyEntitlementQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withManagedSubscription = query
	return _q
}

// WithBoundAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "bound_api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuyEntitlementQuery) WithBoundAPIKey(opts ...func(*APIKeyQuery)) *GroupBuyEntitlementQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBoundAPIKey = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupBuyEntitlement.Query().
//		GroupBy(groupbuyentitlement.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GroupBuyEntitlementQuery) GroupBy(field string, fields ...string) *GroupBuyEntitlementGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroupBuyEntitlementGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = groupbuyentitlement.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.GroupBuyEntitlement.Query().
//		Select(groupbuyentitlement.FieldUserID).
//		Scan(ctx, &v)
func (_q *GroupBuyEntitlementQuery) Select(fields ...string) *GroupBuyEntitlementSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GroupBuyEntitlementSelect{GroupBuyEntitlementQuery: _q}
	sbuild.label = groupbuyentitlement.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroupBuyEntitlementSelect configured with the given aggregations.
func (_q *GroupBuyEntitlementQuery) Aggregate(fns ...AggregateFunc) *GroupBuyEntitlementSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GroupBuyEntitlementQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !groupbuyentitlement.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GroupBuyEntitlementQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupBuyEntitlement, error) {
	var (
		nodes       = []*GroupBuyEntitlement{}
		_spec       = _q.querySpec()
		loadedTypes = [5]bool{
			_q.withUser != nil,
			_q.withTargetGroup != nil,
			_q.withSubscription != nil,
			_q.withManagedSubscription != nil,
			_q.withBoundAPIKey != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupBuyEntitlement).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupBuyEntitlement{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *GroupBuyEntitlement, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withTargetGroup; query != nil {
		if err := _q.loadTargetGroup(ctx, query, nodes, nil,
			func(n *GroupBuyEntitlement, e *Group) { n.Edges.TargetGroup = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubscription; query != nil {
		if err := _q.loadSubscription(ctx, query, nodes, nil,
			func(n *GroupBuyEntitlement, e *UserSubscription) { n.Edges.Subscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withManagedSubscription; query != nil {
		if err := _q.loadManagedSubscription(ctx, query, nodes, nil,
			func(n *GroupBuyEntitlement, e *UserSubscription) { n.Edges.ManagedSubscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBoundAPIKey; query != nil {
		if err := _q.loadBoundAPIKey(ctx, query, nodes, nil,
			func(n *GroupBuyEntitlement, e *APIKey) { n.Edges.BoundAPIKey = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GroupBuyEntitlementQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*GroupBuyEntitlement, init func(*GroupBuyEntitlement), assign func(*GroupBuyEntitlement, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuyEntitlement)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuyEntitlementQuery) loadTargetGroup(ctx context.Context, query *GroupQuery, nodes []*GroupBuyEntitlement, init func(*GroupBuyEntitlement), assign func(*GroupBuyEntitlement, *Group)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuyEntitlement)
	for i := range nodes {
		if nodes[i].TargetGroupID == nil {
			continue
		}
		fk := *nodes[i].TargetGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "target_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuyEntitlementQuery) loadSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*GroupBuyEntitlement, init func(*GroupBuyEntitlement), assign func(*GroupBuyEntitlement, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuyEntitlement)
	for i := range nodes {
		if nodes[i].SubscriptionID == nil {
			continue
		}
		fk := *nodes[i].SubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuyEntitlementQuery) loadManagedSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*GroupBuyEntitlement, init func(*GroupBuyEntitlement), assign func(*GroupBuyEntitlement, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuyEntitlement)
	for i := range nodes {
		if nodes[i].ManagedSubscriptionID == nil {
			continue
		}
		fk := *nodes[i].ManagedSubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "managed_subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuyEntitlementQuery) loadBoundAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*GroupBuyEntitlement, init func(*GroupBuyEntitlement), assign func(*GroupBuyEntitlement, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuyEntitlement)
	for i := range nodes {
		if nodes[i].BoundAPIKeyID == nil {
			continue
		}
		fk := *nodes[i].BoundAPIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bound_api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *GroupBuyEntitlementQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GroupBuyEntitlementQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(groupbuyentitlement.Table, groupbuyentitlement.Columns, sqlgraph.NewFieldSpec(groupbuyentitlement.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupbuyentitlement.FieldID)
		for i := range fields {
			if fields[i] != groupbuyentitlement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(groupbuyentitlement.FieldUserID)
		}
		if _q.withTargetGroup != nil {
			_spec.Node.AddColumnOnce(groupbuyentitlement.FieldTargetGroupID)
		}
		if _q.withSubscription != nil {
			_spec.Node.AddColumnOnce(groupbuyentitlement.FieldSubscriptionID)
		}
		if _q.withManagedSubscription != nil {
			_spec.Node.AddColumnOnce(groupbuyentitlement.FieldManagedSubscriptionID)
		}
		if _q.withBoundAPIKey != nil {
			_spec.Node.AddColumnOnce(groupbuyentitlement.FieldBoundAPIKeyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GroupBuyEntitlementQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(groupbuyentitlement.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = groupbuyentitlement.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *GroupBuyEntitlementQuery) ForUpdate(opts ...sql.LockOption) *GroupBuyEntitlementQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *GroupBuyEntitlementQuery) ForShare(opts ...sql.LockOption) *GroupBuyEntitlementQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// GroupBuyEntitlementGroupBy is the group-by builder for GroupBuyEntitlement entities.
type GroupBuyEntitlementGroupBy struct {
	selector
	build *GroupBuyEntitlementQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GroupBuyEntitlementGroupBy) Aggregate(fns ...AggregateFunc) *GroupBuyEntitlementGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GroupBuyEntitlementGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupBuyEntitlementQuery, *GroupBuyEntitlementGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GroupBuyEntitlementGroupBy) sqlScan(ctx context.Context, root *GroupBuyEntitlementQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroupBuyEntitlementSelect is the builder for selecting fields of GroupBuyEntitlement entities.
type GroupBuyEntitlementSelect struct {
	*GroupBuyEntitlementQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GroupBuyEntitlementSelect) Aggregate(fns ...AggregateFunc) *GroupBuyEntitlementSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GroupBuyEntitlementSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupBuyEntitlementQuery, *GroupBuyEntitlementSelect](ctx, _s.GroupBuyEntitlementQuery, _s, _s.inters, v)
}

func (_s *GroupBuyEntitlementSelect) sqlScan(ctx context.Context, root *GroupBuyEntitlementQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
