// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyplan"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyround"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyseat"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// GroupBuySeat is the model entity for the GroupBuySeat schema.
type GroupBuySeat struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// RoundID holds the value of the "round_id" field.
	RoundID int64 `json:"round_id,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID int64 `json:"plan_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID *int64 `json:"order_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// ShareCount holds the value of the "share_count" field.
	ShareCount int `json:"share_count,omitempty"`
	// PolicySnapshot holds the value of the "policy_snapshot" field.
	PolicySnapshot domain.GroupBuyPolicySnapshot `json:"policy_snapshot,omitempty"`
	// SubscriptionID holds the value of the "subscription_id" field.
	SubscriptionID *int64 `json:"subscription_id,omitempty"`
	// BoundAPIKeyID holds the value of the "bound_api_key_id" field.
	BoundAPIKeyID *int64 `json:"bound_api_key_id,omitempty"`
	// LockedUntil holds the value of the "locked_until" field.
	LockedUntil *time.Time `json:"locked_until,omitempty"`
	// PaidAt holds the value of the "paid_at" field.
	PaidAt *time.Time `json:"paid_at,omitempty"`
	// ActivatedAt holds the value of the "activated_at" field.
	ActivatedAt *time.Time `json:"activated_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// BoundAt holds the value of the "bound_at" field.
	BoundAt *time.Time `json:"bound_at,omitempty"`
	// RefundProcessedAt holds the value of the "refund_processed_at" field.
	RefundProcessedAt *time.Time `json:"refund_processed_at,omitempty"`
	// RefundNote holds the value of the "refund_note" field.
	RefundNote *string `json:"refund_note,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupBuySeatQuery when eager-loading is set.
	Edges        GroupBuySeatEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupBuySeatEdges holds the relations/edges for other nodes in the graph.
type GroupBuySeatEdges struct {
	// Round holds the value of the round edge.
	Round *GroupBuyRound `json:"round,omitempty"`
	// Plan holds the value of the plan edge.
	Plan *GroupBuyPlan `json:"plan,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Order holds the value of the order edge.
	Order *PaymentOrder `json:"order,omitempty"`
	// Subscription holds the value of the subscription edge.
	Subscription *UserSubscription `json:"subscription,omitempty"`
	// BoundAPIKey holds the value of the bound_api_key edge.
	BoundAPIKey *APIKey `json:"bound_api_key,omitempty"`
	// Refunds holds the value of the refunds edge.
	Refunds []*GroupBuyRefund `json:"refunds,omitempty"`
	// Events holds the value of the events edge.
	Events []*GroupBuyEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [8]bool
}

// RoundOrErr returns the Round value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupBuySeatEdges) RoundOrErr() (*GroupBuyRound, error) {
	if e.Round != nil {
		return e.Round, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: groupbuyround.Label}
	}
	return nil, &NotLoadedError{edge: "round"}
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupBuySeatEdges) PlanOrErr() (*GroupBuyPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: groupbuyplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupBuySeatEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupBuySeatEdges) OrderOrErr() (*PaymentOrder, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: paymentorder.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// SubscriptionOrErr returns the Subscription value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupBuySeatEdges) SubscriptionOrErr() (*UserSubscription, error) {
	if e.Subscription != nil {
		return e.Subscription, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: usersubscription.Label}
	}
	return nil, &NotLoadedError{edge: "subscription"}
}

// BoundAPIKeyOrErr returns the BoundAPIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupBuySeatEdges) BoundAPIKeyOrErr() (*APIKey, error) {
	if e.BoundAPIKey != nil {
		return e.BoundAPIKey, nil
	} else if e.loadedTypes[5] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "bound_api_key"}
}

// RefundsOrErr returns the Refunds value or an error if the edge
// was not loaded in eager-loading.
func (e GroupBuySeatEdges) RefundsOrErr() ([]*GroupBuyRefund, error) {
	if e.loadedTypes[6] {
		return e.Refunds, nil
	}
	return nil, &NotLoadedError{edge: "refunds"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e GroupBuySeatEdges) EventsOrErr() ([]*GroupBuyEvent, error) {
	if e.loadedTypes[7] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupBuySeat) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupbuyseat.FieldPolicySnapshot:
			values[i] = new([]byte)
		case groupbuyseat.FieldID, groupbuyseat.FieldRoundID, groupbuyseat.FieldPlanID, groupbuyseat.FieldUserID, groupbuyseat.FieldOrderID, groupbuyseat.FieldShareCount, groupbuyseat.FieldSubscriptionID, groupbuyseat.FieldBoundAPIKeyID:
			values[i] = new(sql.NullInt64)
		case groupbuyseat.FieldStatus, groupbuyseat.FieldRefundNote:
			values[i] = new(sql.NullString)
		case groupbuyseat.FieldLockedUntil, groupbuyseat.FieldPaidAt, groupbuyseat.FieldActivatedAt, groupbuyseat.FieldExpiresAt, groupbuyseat.FieldBoundAt, groupbuyseat.FieldRefundProcessedAt, groupbuyseat.FieldCreatedAt, groupbuyseat.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupBuySeat fields.
func (_m *GroupBuySeat) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupbuyseat.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case groupbuyseat.FieldRoundID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round_id", values[i])
			} else if value.Valid {
				_m.RoundID = value.Int64
			}
		case groupbuyseat.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case groupbuyseat.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case groupbuyseat.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(int64)
				*_m.OrderID = value.Int64
			}
		case groupbuyseat.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case groupbuyseat.FieldShareCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_count", values[i])
			} else if value.Valid {
				_m.ShareCount = int(value.Int64)
			}
		case groupbuyseat.FieldPolicySnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field policy_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.PolicySnapshot); err != nil {
					return fmt.Errorf("unmarshal field policy_snapshot: %w", err)
				}
			}
		case groupbuyseat.FieldSubscriptionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_id", values[i])
			} else if value.Valid {
				_m.SubscriptionID = new(int64)
				*_m.SubscriptionID = value.Int64
			}
		case groupbuyseat.FieldBoundAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field bound_api_key_id", values[i])
			} else if value.Valid {
				_m.BoundAPIKeyID = new(int64)
				*_m.BoundAPIKeyID = value.Int64
			}
		case groupbuyseat.FieldLockedUntil:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_until", values[i])
			} else if value.Valid {
				_m.LockedUntil = new(time.Time)
				*_m.LockedUntil = value.Time
			}
		case groupbuyseat.FieldPaidAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field paid_at", values[i])
			} else if value.Valid {
				_m.PaidAt = new(time.Time)
				*_m.PaidAt = value.Time
			}
		case groupbuyseat.FieldActivatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field activated_at", values[i])
			} else if value.Valid {
				_m.ActivatedAt = new(time.Time)
				*_m.ActivatedAt = value.Time
			}
		case groupbuyseat.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case groupbuyseat.FieldBoundAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field bound_at", values[i])
			} else if value.Valid {
				_m.BoundAt = new(time.Time)
				*_m.BoundAt = value.Time
			}
		case groupbuyseat.FieldRefundProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refund_processed_at", values[i])
			} else if value.Valid {
				_m.RefundProcessedAt = new(time.Time)
				*_m.RefundProcessedAt = value.Time
			}
		case groupbuyseat.FieldRefundNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_note", values[i])
			} else if value.Valid {
				_m.RefundNote = new(string)
				*_m.RefundNote = value.String
			}
		case groupbuyseat.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case groupbuyseat.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupBuySeat.
// This includes values selected through modifiers, order, etc.
func (_m *GroupBuySeat) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRound queries the "round" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryRound() *GroupBuyRoundQuery {
	return NewGroupBuySeatClient(_m.config).QueryRound(_m)
}

// QueryPlan queries the "plan" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryPlan() *GroupBuyPlanQuery {
	return NewGroupBuySeatClient(_m.config).QueryPlan(_m)
}

// QueryUser queries the "user" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryUser() *UserQuery {
	return NewGroupBuySeatClient(_m.config).QueryUser(_m)
}

// QueryOrder queries the "order" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryOrder() *PaymentOrderQuery {
	return NewGroupBuySeatClient(_m.config).QueryOrder(_m)
}

// QuerySubscription queries the "subscription" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QuerySubscription() *UserSubscriptionQuery {
	return NewGroupBuySeatClient(_m.config).QuerySubscription(_m)
}

// QueryBoundAPIKey queries the "bound_api_key" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryBoundAPIKey() *APIKeyQuery {
	return NewGroupBuySeatClient(_m.config).QueryBoundAPIKey(_m)
}

// QueryRefunds queries the "refunds" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryRefunds() *GroupBuyRefundQuery {
	return NewGroupBuySeatClient(_m.config).QueryRefunds(_m)
}

// QueryEvents queries the "events" edge of the GroupBuySeat entity.
func (_m *GroupBuySeat) QueryEvents() *GroupBuyEventQuery {
	return NewGroupBuySeatClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this GroupBuySeat.
// Note that you need to call GroupBuySeat.Unwrap() before calling this method if this GroupBuySeat
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupBuySeat) Update() *GroupBuySeatUpdateOne {
	return NewGroupBuySeatClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupBuySeat entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupBuySeat) Unwrap() *GroupBuySeat {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupBuySeat is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupBuySeat) String() string {
	var builder strings.Builder
	builder.WriteString("GroupBuySeat(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("round_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RoundID))
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("share_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShareCount))
	builder.WriteString(", ")
	builder.WriteString("policy_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicySnapshot))
	builder.WriteString(", ")
	if v := _m.SubscriptionID; v != nil {
		builder.WriteString("subscription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.BoundAPIKeyID; v != nil {
		builder.WriteString("bound_api_key_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LockedUntil; v != nil {
		builder.WriteString("locked_until=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PaidAt; v != nil {
		builder.WriteString("paid_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ActivatedAt; v != nil {
		builder.WriteString("activated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.BoundAt; v != nil {
		builder.WriteString("bound_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundProcessedAt; v != nil {
		builder.WriteString("refund_processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.RefundNote; v != nil {
		builder.WriteString("refund_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// GroupBuySeats is a parsable slice of GroupBuySeat.
type GroupBuySeats []*GroupBuySeat
