// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyseat"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// GroupBuySeatDelete is the builder for deleting a GroupBuySeat entity.
type GroupBuySeatDelete struct {
	config
	hooks    []Hook
	mutation *GroupBuySeatMutation
}

// Where appends a list predicates to the GroupBuySeatDelete builder.
func (_d *GroupBuySeatDelete) Where(ps ...predicate.GroupBuySeat) *GroupBuySeatDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *GroupBuySeatDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupBuySeatDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *GroupBuySeatDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(groupbuyseat.Table, sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// GroupBuySeatDeleteOne is the builder for deleting a single GroupBuySeat entity.
type GroupBuySeatDeleteOne struct {
	_d *GroupBuySeatDelete
}

// Where appends a list predicates to the GroupBuySeatDelete builder.
func (_d *GroupBuySeatDeleteOne) Where(ps ...predicate.GroupBuySeat) *GroupBuySeatDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *GroupBuySeatDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{groupbuyseat.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *GroupBuySeatDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
