// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyevent"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyplan"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyround"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyseat"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/usersubscription"
)

// GroupBuySeatQuery is the builder for querying GroupBuySeat entities.
type GroupBuySeatQuery struct {
	config
	ctx              *QueryContext
	order            []groupbuyseat.OrderOption
	inters           []Interceptor
	predicates       []predicate.GroupBuySeat
	withRound        *GroupBuyRoundQuery
	withPlan         *GroupBuyPlanQuery
	withUser         *UserQuery
	withOrder        *PaymentOrderQuery
	withSubscription *UserSubscriptionQuery
	withBoundAPIKey  *APIKeyQuery
	withEvents       *GroupBuyEventQuery
	modifiers        []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GroupBuySeatQuery builder.
func (_q *GroupBuySeatQuery) Where(ps ...predicate.GroupBuySeat) *GroupBuySeatQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *GroupBuySeatQuery) Limit(limit int) *GroupBuySeatQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *GroupBuySeatQuery) Offset(offset int) *GroupBuySeatQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *GroupBuySeatQuery) Unique(unique bool) *GroupBuySeatQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *GroupBuySeatQuery) Order(o ...groupbuyseat.OrderOption) *GroupBuySeatQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryRound chains the current query on the "round" edge.
func (_q *GroupBuySeatQuery) QueryRound() *GroupBuyRoundQuery {
	query := (&GroupBuyRoundClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(groupbuyround.Table, groupbuyround.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyseat.RoundTable, groupbuyseat.RoundColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlan chains the current query on the "plan" edge.
func (_q *GroupBuySeatQuery) QueryPlan() *GroupBuyPlanQuery {
	query := (&GroupBuyPlanClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(groupbuyplan.Table, groupbuyplan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyseat.PlanTable, groupbuyseat.PlanColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (_q *GroupBuySeatQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyseat.UserTable, groupbuyseat.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrder chains the current query on the "order" edge.
func (_q *GroupBuySeatQuery) QueryOrder() *PaymentOrderQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(paymentorder.Table, paymentorder.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, groupbuyseat.OrderTable, groupbuyseat.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubscription chains the current query on the "subscription" edge.
func (_q *GroupBuySeatQuery) QuerySubscription() *UserSubscriptionQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(usersubscription.Table, usersubscription.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyseat.SubscriptionTable, groupbuyseat.SubscriptionColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryBoundAPIKey chains the current query on the "bound_api_key" edge.
func (_q *GroupBuySeatQuery) QueryBoundAPIKey() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, groupbuyseat.BoundAPIKeyTable, groupbuyseat.BoundAPIKeyColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEvents chains the current query on the "events" edge.
func (_q *GroupBuySeatQuery) QueryEvents() *GroupBuyEventQuery {
	query := (&GroupBuyEventClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(groupbuyseat.Table, groupbuyseat.FieldID, selector),
			sqlgraph.To(groupbuyevent.Table, groupbuyevent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, groupbuyseat.EventsTable, groupbuyseat.EventsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GroupBuySeat entity from the query.
// Returns a *NotFoundError when no GroupBuySeat was found.
func (_q *GroupBuySeatQuery) First(ctx context.Context) (*GroupBuySeat, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{groupbuyseat.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *GroupBuySeatQuery) FirstX(ctx context.Context) *GroupBuySeat {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GroupBuySeat ID from the query.
// Returns a *NotFoundError when no GroupBuySeat ID was found.
func (_q *GroupBuySeatQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{groupbuyseat.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *GroupBuySeatQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GroupBuySeat entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GroupBuySeat entity is found.
// Returns a *NotFoundError when no GroupBuySeat entities are found.
func (_q *GroupBuySeatQuery) Only(ctx context.Context) (*GroupBuySeat, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{groupbuyseat.Label}
	default:
		return nil, &NotSingularError{groupbuyseat.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *GroupBuySeatQuery) OnlyX(ctx context.Context) *GroupBuySeat {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GroupBuySeat ID in the query.
// Returns a *NotSingularError when more than one GroupBuySeat ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *GroupBuySeatQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{groupbuyseat.Label}
	default:
		err = &NotSingularError{groupbuyseat.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *GroupBuySeatQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GroupBuySeats.
func (_q *GroupBuySeatQuery) All(ctx context.Context) ([]*GroupBuySeat, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GroupBuySeat, *GroupBuySeatQuery]()
	return withInterceptors[[]*GroupBuySeat](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *GroupBuySeatQuery) AllX(ctx context.Context) []*GroupBuySeat {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GroupBuySeat IDs.
func (_q *GroupBuySeatQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(groupbuyseat.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *GroupBuySeatQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *GroupBuySeatQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*GroupBuySeatQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *GroupBuySeatQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *GroupBuySeatQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *GroupBuySeatQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GroupBuySeatQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *GroupBuySeatQuery) Clone() *GroupBuySeatQuery {
	if _q == nil {
		return nil
	}
	return &GroupBuySeatQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]groupbuyseat.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.GroupBuySeat{}, _q.predicates...),
		withRound:        _q.withRound.Clone(),
		withPlan:         _q.withPlan.Clone(),
		withUser:         _q.withUser.Clone(),
		withOrder:        _q.withOrder.Clone(),
		withSubscription: _q.withSubscription.Clone(),
		withBoundAPIKey:  _q.withBoundAPIKey.Clone(),
		withEvents:       _q.withEvents.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithRound tells the query-builder to eager-load the nodes that are connected to
// the "round" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithRound(opts ...func(*GroupBuyRoundQuery)) *GroupBuySeatQuery {
	query := (&GroupBuyRoundClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRound = query
	return _q
}

// WithPlan tells the query-builder to eager-load the nodes that are connected to
// the "plan" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithPlan(opts ...func(*GroupBuyPlanQuery)) *GroupBuySeatQuery {
	query := (&GroupBuyPlanClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlan = query
	return _q
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithUser(opts ...func(*UserQuery)) *GroupBuySeatQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithOrder(opts ...func(*PaymentOrderQuery)) *GroupBuySeatQuery {
	query := (&PaymentOrderClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withOrder = query
	return _q
}

// WithSubscription tells the query-builder to eager-load the nodes that are connected to
// the "subscription" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithSubscription(opts ...func(*UserSubscriptionQuery)) *GroupBuySeatQuery {
	query := (&UserSubscriptionClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSubscription = query
	return _q
}

// WithBoundAPIKey tells the query-builder to eager-load the nodes that are connected to
// the "bound_api_key" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithBoundAPIKey(opts ...func(*APIKeyQuery)) *GroupBuySeatQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withBoundAPIKey = query
	return _q
}

// WithEvents tells the query-builder to eager-load the nodes that are connected to
// the "events" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *GroupBuySeatQuery) WithEvents(opts ...func(*GroupBuyEventQuery)) *GroupBuySeatQuery {
	query := (&GroupBuyEventClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEvents = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoundID int64 `json:"round_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GroupBuySeat.Query().
//		GroupBy(groupbuyseat.FieldRoundID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *GroupBuySeatQuery) GroupBy(field string, fields ...string) *GroupBuySeatGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GroupBuySeatGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = groupbuyseat.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoundID int64 `json:"round_id,omitempty"`
//	}
//
//	client.GroupBuySeat.Query().
//		Select(groupbuyseat.FieldRoundID).
//		Scan(ctx, &v)
func (_q *GroupBuySeatQuery) Select(fields ...string) *GroupBuySeatSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &GroupBuySeatSelect{GroupBuySeatQuery: _q}
	sbuild.label = groupbuyseat.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GroupBuySeatSelect configured with the given aggregations.
func (_q *GroupBuySeatQuery) Aggregate(fns ...AggregateFunc) *GroupBuySeatSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *GroupBuySeatQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !groupbuyseat.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *GroupBuySeatQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GroupBuySeat, error) {
	var (
		nodes       = []*GroupBuySeat{}
		_spec       = _q.querySpec()
		loadedTypes = [7]bool{
			_q.withRound != nil,
			_q.withPlan != nil,
			_q.withUser != nil,
			_q.withOrder != nil,
			_q.withSubscription != nil,
			_q.withBoundAPIKey != nil,
			_q.withEvents != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GroupBuySeat).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GroupBuySeat{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withRound; query != nil {
		if err := _q.loadRound(ctx, query, nodes, nil,
			func(n *GroupBuySeat, e *GroupBuyRound) { n.Edges.Round = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlan; query != nil {
		if err := _q.loadPlan(ctx, query, nodes, nil,
			func(n *GroupBuySeat, e *GroupBuyPlan) { n.Edges.Plan = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *GroupBuySeat, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withOrder; query != nil {
		if err := _q.loadOrder(ctx, query, nodes, nil,
			func(n *GroupBuySeat, e *PaymentOrder) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withSubscription; query != nil {
		if err := _q.loadSubscription(ctx, query, nodes, nil,
			func(n *GroupBuySeat, e *UserSubscription) { n.Edges.Subscription = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withBoundAPIKey; query != nil {
		if err := _q.loadBoundAPIKey(ctx, query, nodes, nil,
			func(n *GroupBuySeat, e *APIKey) { n.Edges.BoundAPIKey = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEvents; query != nil {
		if err := _q.loadEvents(ctx, query, nodes,
			func(n *GroupBuySeat) { n.Edges.Events = []*GroupBuyEvent{} },
			func(n *GroupBuySeat, e *GroupBuyEvent) { n.Edges.Events = append(n.Edges.Events, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *GroupBuySeatQuery) loadRound(ctx context.Context, query *GroupBuyRoundQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *GroupBuyRound)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuySeat)
	for i := range nodes {
		fk := nodes[i].RoundID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(groupbuyround.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "round_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuySeatQuery) loadPlan(ctx context.Context, query *GroupBuyPlanQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *GroupBuyPlan)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuySeat)
	for i := range nodes {
		fk := nodes[i].PlanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(groupbuyplan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "plan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuySeatQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *User)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuySeat)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuySeatQuery) loadOrder(ctx context.Context, query *PaymentOrderQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *PaymentOrder)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuySeat)
	for i := range nodes {
		if nodes[i].OrderID == nil {
			continue
		}
		fk := *nodes[i].OrderID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(paymentorder.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuySeatQuery) loadSubscription(ctx context.Context, query *UserSubscriptionQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *UserSubscription)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuySeat)
	for i := range nodes {
		if nodes[i].SubscriptionID == nil {
			continue
		}
		fk := *nodes[i].SubscriptionID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(usersubscription.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "subscription_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuySeatQuery) loadBoundAPIKey(ctx context.Context, query *APIKeyQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *APIKey)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*GroupBuySeat)
	for i := range nodes {
		if nodes[i].BoundAPIKeyID == nil {
			continue
		}
		fk := *nodes[i].BoundAPIKeyID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(apikey.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "bound_api_key_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *GroupBuySeatQuery) loadEvents(ctx context.Context, query *GroupBuyEventQuery, nodes []*GroupBuySeat, init func(*GroupBuySeat), assign func(*GroupBuySeat, *GroupBuyEvent)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*GroupBuySeat)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(groupbuyevent.FieldSeatID)
	}
	query.Where(predicate.GroupBuyEvent(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(groupbuyseat.EventsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SeatID
		if fk == nil {
			return fmt.Errorf(`foreign-key "seat_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "seat_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *GroupBuySeatQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *GroupBuySeatQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(groupbuyseat.Table, groupbuyseat.Columns, sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupbuyseat.FieldID)
		for i := range fields {
			if fields[i] != groupbuyseat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withRound != nil {
			_spec.Node.AddColumnOnce(groupbuyseat.FieldRoundID)
		}
		if _q.withPlan != nil {
			_spec.Node.AddColumnOnce(groupbuyseat.FieldPlanID)
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(groupbuyseat.FieldUserID)
		}
		if _q.withOrder != nil {
			_spec.Node.AddColumnOnce(groupbuyseat.FieldOrderID)
		}
		if _q.withSubscription != nil {
			_spec.Node.AddColumnOnce(groupbuyseat.FieldSubscriptionID)
		}
		if _q.withBoundAPIKey != nil {
			_spec.Node.AddColumnOnce(groupbuyseat.FieldBoundAPIKeyID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *GroupBuySeatQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(groupbuyseat.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = groupbuyseat.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *GroupBuySeatQuery) ForUpdate(opts ...sql.LockOption) *GroupBuySeatQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *GroupBuySeatQuery) ForShare(opts ...sql.LockOption) *GroupBuySeatQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// GroupBuySeatGroupBy is the group-by builder for GroupBuySeat entities.
type GroupBuySeatGroupBy struct {
	selector
	build *GroupBuySeatQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *GroupBuySeatGroupBy) Aggregate(fns ...AggregateFunc) *GroupBuySeatGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *GroupBuySeatGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupBuySeatQuery, *GroupBuySeatGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *GroupBuySeatGroupBy) sqlScan(ctx context.Context, root *GroupBuySeatQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GroupBuySeatSelect is the builder for selecting fields of GroupBuySeat entities.
type GroupBuySeatSelect struct {
	*GroupBuySeatQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *GroupBuySeatSelect) Aggregate(fns ...AggregateFunc) *GroupBuySeatSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *GroupBuySeatSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GroupBuySeatQuery, *GroupBuySeatSelect](ctx, _s.GroupBuySeatQuery, _s, _s.inters, v)
}

func (_s *GroupBuySeatSelect) sqlScan(ctx context.Context, root *GroupBuySeatQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
