// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyevent"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyplan"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyround"
	"github.com/Wei-Shaw/sub2api/ent/groupbuyseat"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// GroupBuyPlanUpdate is the builder for updating GroupBuyPlan entities.
type GroupBuyPlanUpdate struct {
	config
	hooks    []Hook
	mutation *GroupBuyPlanMutation
}

// Where appends a list predicates to the GroupBuyPlanUpdate builder.
func (_u *GroupBuyPlanUpdate) Where(ps ...predicate.GroupBuyPlan) *GroupBuyPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupBuyPlanUpdate) SetUpdatedAt(v time.Time) *GroupBuyPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *GroupBuyPlanUpdate) SetTitle(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableTitle(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupBuyPlanUpdate) SetDescription(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableDescription(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupBuyPlanUpdate) ClearDescription() *GroupBuyPlanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetProductKey sets the "product_key" field.
func (_u *GroupBuyPlanUpdate) SetProductKey(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetProductKey(v)
	return _u
}

// SetNillableProductKey sets the "product_key" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableProductKey(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetProductKey(*v)
	}
	return _u
}

// SetTotalShares sets the "total_shares" field.
func (_u *GroupBuyPlanUpdate) SetTotalShares(v int) *GroupBuyPlanUpdate {
	_u.mutation.ResetTotalShares()
	_u.mutation.SetTotalShares(v)
	return _u
}

// SetNillableTotalShares sets the "total_shares" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableTotalShares(v *int) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetTotalShares(*v)
	}
	return _u
}

// AddTotalShares adds value to the "total_shares" field.
func (_u *GroupBuyPlanUpdate) AddTotalShares(v int) *GroupBuyPlanUpdate {
	_u.mutation.AddTotalShares(v)
	return _u
}

// SetSeatCount sets the "seat_count" field.
func (_u *GroupBuyPlanUpdate) SetSeatCount(v int) *GroupBuyPlanUpdate {
	_u.mutation.ResetSeatCount()
	_u.mutation.SetSeatCount(v)
	return _u
}

// SetNillableSeatCount sets the "seat_count" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableSeatCount(v *int) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetSeatCount(*v)
	}
	return _u
}

// AddSeatCount adds value to the "seat_count" field.
func (_u *GroupBuyPlanUpdate) AddSeatCount(v int) *GroupBuyPlanUpdate {
	_u.mutation.AddSeatCount(v)
	return _u
}

// SetPricePerShare sets the "price_per_share" field.
func (_u *GroupBuyPlanUpdate) SetPricePerShare(v float64) *GroupBuyPlanUpdate {
	_u.mutation.ResetPricePerShare()
	_u.mutation.SetPricePerShare(v)
	return _u
}

// SetNillablePricePerShare sets the "price_per_share" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillablePricePerShare(v *float64) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetPricePerShare(*v)
	}
	return _u
}

// AddPricePerShare adds value to the "price_per_share" field.
func (_u *GroupBuyPlanUpdate) AddPricePerShare(v float64) *GroupBuyPlanUpdate {
	_u.mutation.AddPricePerShare(v)
	return _u
}

// SetPricePerSeat sets the "price_per_seat" field.
func (_u *GroupBuyPlanUpdate) SetPricePerSeat(v float64) *GroupBuyPlanUpdate {
	_u.mutation.ResetPricePerSeat()
	_u.mutation.SetPricePerSeat(v)
	return _u
}

// SetNillablePricePerSeat sets the "price_per_seat" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillablePricePerSeat(v *float64) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetPricePerSeat(*v)
	}
	return _u
}

// AddPricePerSeat adds value to the "price_per_seat" field.
func (_u *GroupBuyPlanUpdate) AddPricePerSeat(v float64) *GroupBuyPlanUpdate {
	_u.mutation.AddPricePerSeat(v)
	return _u
}

// SetPriceLabel sets the "price_label" field.
func (_u *GroupBuyPlanUpdate) SetPriceLabel(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetPriceLabel(v)
	return _u
}

// SetNillablePriceLabel sets the "price_label" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillablePriceLabel(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetPriceLabel(*v)
	}
	return _u
}

// SetQuotaPerShareLabel sets the "quota_per_share_label" field.
func (_u *GroupBuyPlanUpdate) SetQuotaPerShareLabel(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetQuotaPerShareLabel(v)
	return _u
}

// SetNillableQuotaPerShareLabel sets the "quota_per_share_label" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableQuotaPerShareLabel(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetQuotaPerShareLabel(*v)
	}
	return _u
}

// SetQuotaLabel sets the "quota_label" field.
func (_u *GroupBuyPlanUpdate) SetQuotaLabel(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetQuotaLabel(v)
	return _u
}

// SetNillableQuotaLabel sets the "quota_label" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableQuotaLabel(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetQuotaLabel(*v)
	}
	return _u
}

// SetMaxSharesPerUser sets the "max_shares_per_user" field.
func (_u *GroupBuyPlanUpdate) SetMaxSharesPerUser(v int) *GroupBuyPlanUpdate {
	_u.mutation.ResetMaxSharesPerUser()
	_u.mutation.SetMaxSharesPerUser(v)
	return _u
}

// SetNillableMaxSharesPerUser sets the "max_shares_per_user" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableMaxSharesPerUser(v *int) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetMaxSharesPerUser(*v)
	}
	return _u
}

// AddMaxSharesPerUser adds value to the "max_shares_per_user" field.
func (_u *GroupBuyPlanUpdate) AddMaxSharesPerUser(v int) *GroupBuyPlanUpdate {
	_u.mutation.AddMaxSharesPerUser(v)
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *GroupBuyPlanUpdate) SetTargetGroupID(v int64) *GroupBuyPlanUpdate {
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableTargetGroupID(v *int64) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// SetTierGroupIds sets the "tier_group_ids" field.
func (_u *GroupBuyPlanUpdate) SetTierGroupIds(v map[string]int64) *GroupBuyPlanUpdate {
	_u.mutation.SetTierGroupIds(v)
	return _u
}

// ClearTierGroupIds clears the value of the "tier_group_ids" field.
func (_u *GroupBuyPlanUpdate) ClearTierGroupIds() *GroupBuyPlanUpdate {
	_u.mutation.ClearTierGroupIds()
	return _u
}

// SetTierRules sets the "tier_rules" field.
func (_u *GroupBuyPlanUpdate) SetTierRules(v []domain.GroupBuyTierRule) *GroupBuyPlanUpdate {
	_u.mutation.SetTierRules(v)
	return _u
}

// AppendTierRules appends value to the "tier_rules" field.
func (_u *GroupBuyPlanUpdate) AppendTierRules(v []domain.GroupBuyTierRule) *GroupBuyPlanUpdate {
	_u.mutation.AppendTierRules(v)
	return _u
}

// ClearTierRules clears the value of the "tier_rules" field.
func (_u *GroupBuyPlanUpdate) ClearTierRules() *GroupBuyPlanUpdate {
	_u.mutation.ClearTierRules()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *GroupBuyPlanUpdate) SetValidityDays(v int) *GroupBuyPlanUpdate {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableValidityDays(v *int) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *GroupBuyPlanUpdate) AddValidityDays(v int) *GroupBuyPlanUpdate {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetTimeoutMinutes sets the "timeout_minutes" field.
func (_u *GroupBuyPlanUpdate) SetTimeoutMinutes(v int) *GroupBuyPlanUpdate {
	_u.mutation.ResetTimeoutMinutes()
	_u.mutation.SetTimeoutMinutes(v)
	return _u
}

// SetNillableTimeoutMinutes sets the "timeout_minutes" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableTimeoutMinutes(v *int) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetTimeoutMinutes(*v)
	}
	return _u
}

// AddTimeoutMinutes adds value to the "timeout_minutes" field.
func (_u *GroupBuyPlanUpdate) AddTimeoutMinutes(v int) *GroupBuyPlanUpdate {
	_u.mutation.AddTimeoutMinutes(v)
	return _u
}

// SetLaunchMode sets the "launch_mode" field.
func (_u *GroupBuyPlanUpdate) SetLaunchMode(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetLaunchMode(v)
	return _u
}

// SetNillableLaunchMode sets the "launch_mode" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableLaunchMode(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetLaunchMode(*v)
	}
	return _u
}

// SetRefundMode sets the "refund_mode" field.
func (_u *GroupBuyPlanUpdate) SetRefundMode(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetRefundMode(v)
	return _u
}

// SetNillableRefundMode sets the "refund_mode" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableRefundMode(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetRefundMode(*v)
	}
	return _u
}

// SetAgreementText sets the "agreement_text" field.
func (_u *GroupBuyPlanUpdate) SetAgreementText(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetAgreementText(v)
	return _u
}

// SetNillableAgreementText sets the "agreement_text" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableAgreementText(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetAgreementText(*v)
	}
	return _u
}

// ClearAgreementText clears the value of the "agreement_text" field.
func (_u *GroupBuyPlanUpdate) ClearAgreementText() *GroupBuyPlanUpdate {
	_u.mutation.ClearAgreementText()
	return _u
}

// SetStatus sets the "status" field.
func (_u *GroupBuyPlanUpdate) SetStatus(v string) *GroupBuyPlanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableStatus(v *string) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *GroupBuyPlanUpdate) SetSortOrder(v int) *GroupBuyPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableSortOrder(v *int) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *GroupBuyPlanUpdate) AddSortOrder(v int) *GroupBuyPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetLastRoundCreatedAt sets the "last_round_created_at" field.
func (_u *GroupBuyPlanUpdate) SetLastRoundCreatedAt(v time.Time) *GroupBuyPlanUpdate {
	_u.mutation.SetLastRoundCreatedAt(v)
	return _u
}

// SetNillableLastRoundCreatedAt sets the "last_round_created_at" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableLastRoundCreatedAt(v *time.Time) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetLastRoundCreatedAt(*v)
	}
	return _u
}

// ClearLastRoundCreatedAt clears the value of the "last_round_created_at" field.
func (_u *GroupBuyPlanUpdate) ClearLastRoundCreatedAt() *GroupBuyPlanUpdate {
	_u.mutation.ClearLastRoundCreatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GroupBuyPlanUpdate) SetDeletedAt(v time.Time) *GroupBuyPlanUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GroupBuyPlanUpdate) SetNillableDeletedAt(v *time.Time) *GroupBuyPlanUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GroupBuyPlanUpdate) ClearDeletedAt() *GroupBuyPlanUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_u *GroupBuyPlanUpdate) SetTargetGroup(v *Group) *GroupBuyPlanUpdate {
	return _u.SetTargetGroupID(v.ID)
}

// AddRoundIDs adds the "rounds" edge to the GroupBuyRound entity by IDs.
func (_u *GroupBuyPlanUpdate) AddRoundIDs(ids ...int64) *GroupBuyPlanUpdate {
	_u.mutation.AddRoundIDs(ids...)
	return _u
}

// AddRounds adds the "rounds" edges to the GroupBuyRound entity.
func (_u *GroupBuyPlanUpdate) AddRounds(v ...*GroupBuyRound) *GroupBuyPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoundIDs(ids...)
}

// AddSeatIDs adds the "seats" edge to the GroupBuySeat entity by IDs.
func (_u *GroupBuyPlanUpdate) AddSeatIDs(ids ...int64) *GroupBuyPlanUpdate {
	_u.mutation.AddSeatIDs(ids...)
	return _u
}

// AddSeats adds the "seats" edges to the GroupBuySeat entity.
func (_u *GroupBuyPlanUpdate) AddSeats(v ...*GroupBuySeat) *GroupBuyPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatIDs(ids...)
}

// AddEventIDs adds the "events" edge to the GroupBuyEvent entity by IDs.
func (_u *GroupBuyPlanUpdate) AddEventIDs(ids ...int64) *GroupBuyPlanUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the GroupBuyEvent entity.
func (_u *GroupBuyPlanUpdate) AddEvents(v ...*GroupBuyEvent) *GroupBuyPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the GroupBuyPlanMutation object of the builder.
func (_u *GroupBuyPlanUpdate) Mutation() *GroupBuyPlanMutation {
	return _u.mutation
}

// ClearTargetGroup clears the "target_group" edge to the Group entity.
func (_u *GroupBuyPlanUpdate) ClearTargetGroup() *GroupBuyPlanUpdate {
	_u.mutation.ClearTargetGroup()
	return _u
}

// ClearRounds clears all "rounds" edges to the GroupBuyRound entity.
func (_u *GroupBuyPlanUpdate) ClearRounds() *GroupBuyPlanUpdate {
	_u.mutation.ClearRounds()
	return _u
}

// RemoveRoundIDs removes the "rounds" edge to GroupBuyRound entities by IDs.
func (_u *GroupBuyPlanUpdate) RemoveRoundIDs(ids ...int64) *GroupBuyPlanUpdate {
	_u.mutation.RemoveRoundIDs(ids...)
	return _u
}

// RemoveRounds removes "rounds" edges to GroupBuyRound entities.
func (_u *GroupBuyPlanUpdate) RemoveRounds(v ...*GroupBuyRound) *GroupBuyPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoundIDs(ids...)
}

// ClearSeats clears all "seats" edges to the GroupBuySeat entity.
func (_u *GroupBuyPlanUpdate) ClearSeats() *GroupBuyPlanUpdate {
	_u.mutation.ClearSeats()
	return _u
}

// RemoveSeatIDs removes the "seats" edge to GroupBuySeat entities by IDs.
func (_u *GroupBuyPlanUpdate) RemoveSeatIDs(ids ...int64) *GroupBuyPlanUpdate {
	_u.mutation.RemoveSeatIDs(ids...)
	return _u
}

// RemoveSeats removes "seats" edges to GroupBuySeat entities.
func (_u *GroupBuyPlanUpdate) RemoveSeats(v ...*GroupBuySeat) *GroupBuyPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatIDs(ids...)
}

// ClearEvents clears all "events" edges to the GroupBuyEvent entity.
func (_u *GroupBuyPlanUpdate) ClearEvents() *GroupBuyPlanUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to GroupBuyEvent entities by IDs.
func (_u *GroupBuyPlanUpdate) RemoveEventIDs(ids ...int64) *GroupBuyPlanUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to GroupBuyEvent entities.
func (_u *GroupBuyPlanUpdate) RemoveEvents(v ...*GroupBuyEvent) *GroupBuyPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GroupBuyPlanUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupBuyPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GroupBuyPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupBuyPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupBuyPlanUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupbuyplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupBuyPlanUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := groupbuyplan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductKey(); ok {
		if err := groupbuyplan.ProductKeyValidator(v); err != nil {
			return &ValidationError{Name: "product_key", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.product_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalShares(); ok {
		if err := groupbuyplan.TotalSharesValidator(v); err != nil {
			return &ValidationError{Name: "total_shares", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.total_shares": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeatCount(); ok {
		if err := groupbuyplan.SeatCountValidator(v); err != nil {
			return &ValidationError{Name: "seat_count", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.seat_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceLabel(); ok {
		if err := groupbuyplan.PriceLabelValidator(v); err != nil {
			return &ValidationError{Name: "price_label", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.price_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaPerShareLabel(); ok {
		if err := groupbuyplan.QuotaPerShareLabelValidator(v); err != nil {
			return &ValidationError{Name: "quota_per_share_label", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.quota_per_share_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaLabel(); ok {
		if err := groupbuyplan.QuotaLabelValidator(v); err != nil {
			return &ValidationError{Name: "quota_label", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.quota_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LaunchMode(); ok {
		if err := groupbuyplan.LaunchModeValidator(v); err != nil {
			return &ValidationError{Name: "launch_mode", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.launch_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundMode(); ok {
		if err := groupbuyplan.RefundModeValidator(v); err != nil {
			return &ValidationError{Name: "refund_mode", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.refund_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := groupbuyplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.status": %w`, err)}
		}
	}
	if _u.mutation.TargetGroupCleared() && len(_u.mutation.TargetGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupBuyPlan.target_group"`)
	}
	return nil
}

func (_u *GroupBuyPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupbuyplan.Table, groupbuyplan.Columns, sqlgraph.NewFieldSpec(groupbuyplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuyplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(groupbuyplan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(groupbuyplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(groupbuyplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ProductKey(); ok {
		_spec.SetField(groupbuyplan.FieldProductKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalShares(); ok {
		_spec.SetField(groupbuyplan.FieldTotalShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalShares(); ok {
		_spec.AddField(groupbuyplan.FieldTotalShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SeatCount(); ok {
		_spec.SetField(groupbuyplan.FieldSeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeatCount(); ok {
		_spec.AddField(groupbuyplan.FieldSeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PricePerShare(); ok {
		_spec.SetField(groupbuyplan.FieldPricePerShare, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerShare(); ok {
		_spec.AddField(groupbuyplan.FieldPricePerShare, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PricePerSeat(); ok {
		_spec.SetField(groupbuyplan.FieldPricePerSeat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerSeat(); ok {
		_spec.AddField(groupbuyplan.FieldPricePerSeat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PriceLabel(); ok {
		_spec.SetField(groupbuyplan.FieldPriceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaPerShareLabel(); ok {
		_spec.SetField(groupbuyplan.FieldQuotaPerShareLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLabel(); ok {
		_spec.SetField(groupbuyplan.FieldQuotaLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxSharesPerUser(); ok {
		_spec.SetField(groupbuyplan.FieldMaxSharesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxSharesPerUser(); ok {
		_spec.AddField(groupbuyplan.FieldMaxSharesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TierGroupIds(); ok {
		_spec.SetField(groupbuyplan.FieldTierGroupIds, field.TypeJSON, value)
	}
	if _u.mutation.TierGroupIdsCleared() {
		_spec.ClearField(groupbuyplan.FieldTierGroupIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.TierRules(); ok {
		_spec.SetField(groupbuyplan.FieldTierRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTierRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, groupbuyplan.FieldTierRules, value)
		})
	}
	if _u.mutation.TierRulesCleared() {
		_spec.ClearField(groupbuyplan.FieldTierRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(groupbuyplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(groupbuyplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutMinutes(); ok {
		_spec.SetField(groupbuyplan.FieldTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMinutes(); ok {
		_spec.AddField(groupbuyplan.FieldTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LaunchMode(); ok {
		_spec.SetField(groupbuyplan.FieldLaunchMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundMode(); ok {
		_spec.SetField(groupbuyplan.FieldRefundMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgreementText(); ok {
		_spec.SetField(groupbuyplan.FieldAgreementText, field.TypeString, value)
	}
	if _u.mutation.AgreementTextCleared() {
		_spec.ClearField(groupbuyplan.FieldAgreementText, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(groupbuyplan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(groupbuyplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(groupbuyplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastRoundCreatedAt(); ok {
		_spec.SetField(groupbuyplan.FieldLastRoundCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRoundCreatedAtCleared() {
		_spec.ClearField(groupbuyplan.FieldLastRoundCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(groupbuyplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(groupbuyplan.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TargetGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupbuyplan.TargetGroupTable,
			Columns: []string{groupbuyplan.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupbuyplan.TargetGroupTable,
			Columns: []string{groupbuyplan.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.RoundsTable,
			Columns: []string{groupbuyplan.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyround.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoundsIDs(); len(nodes) > 0 && !_u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.RoundsTable,
			Columns: []string{groupbuyplan.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyround.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.RoundsTable,
			Columns: []string{groupbuyplan.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyround.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.SeatsTable,
			Columns: []string{groupbuyplan.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !_u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.SeatsTable,
			Columns: []string{groupbuyplan.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.SeatsTable,
			Columns: []string{groupbuyplan.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.EventsTable,
			Columns: []string{groupbuyplan.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.EventsTable,
			Columns: []string{groupbuyplan.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.EventsTable,
			Columns: []string{groupbuyplan.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupbuyplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GroupBuyPlanUpdateOne is the builder for updating a single GroupBuyPlan entity.
type GroupBuyPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GroupBuyPlanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *GroupBuyPlanUpdateOne) SetUpdatedAt(v time.Time) *GroupBuyPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTitle sets the "title" field.
func (_u *GroupBuyPlanUpdateOne) SetTitle(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableTitle(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *GroupBuyPlanUpdateOne) SetDescription(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableDescription(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *GroupBuyPlanUpdateOne) ClearDescription() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetProductKey sets the "product_key" field.
func (_u *GroupBuyPlanUpdateOne) SetProductKey(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetProductKey(v)
	return _u
}

// SetNillableProductKey sets the "product_key" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableProductKey(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetProductKey(*v)
	}
	return _u
}

// SetTotalShares sets the "total_shares" field.
func (_u *GroupBuyPlanUpdateOne) SetTotalShares(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetTotalShares()
	_u.mutation.SetTotalShares(v)
	return _u
}

// SetNillableTotalShares sets the "total_shares" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableTotalShares(v *int) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetTotalShares(*v)
	}
	return _u
}

// AddTotalShares adds value to the "total_shares" field.
func (_u *GroupBuyPlanUpdateOne) AddTotalShares(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.AddTotalShares(v)
	return _u
}

// SetSeatCount sets the "seat_count" field.
func (_u *GroupBuyPlanUpdateOne) SetSeatCount(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetSeatCount()
	_u.mutation.SetSeatCount(v)
	return _u
}

// SetNillableSeatCount sets the "seat_count" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableSeatCount(v *int) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetSeatCount(*v)
	}
	return _u
}

// AddSeatCount adds value to the "seat_count" field.
func (_u *GroupBuyPlanUpdateOne) AddSeatCount(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.AddSeatCount(v)
	return _u
}

// SetPricePerShare sets the "price_per_share" field.
func (_u *GroupBuyPlanUpdateOne) SetPricePerShare(v float64) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetPricePerShare()
	_u.mutation.SetPricePerShare(v)
	return _u
}

// SetNillablePricePerShare sets the "price_per_share" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillablePricePerShare(v *float64) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetPricePerShare(*v)
	}
	return _u
}

// AddPricePerShare adds value to the "price_per_share" field.
func (_u *GroupBuyPlanUpdateOne) AddPricePerShare(v float64) *GroupBuyPlanUpdateOne {
	_u.mutation.AddPricePerShare(v)
	return _u
}

// SetPricePerSeat sets the "price_per_seat" field.
func (_u *GroupBuyPlanUpdateOne) SetPricePerSeat(v float64) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetPricePerSeat()
	_u.mutation.SetPricePerSeat(v)
	return _u
}

// SetNillablePricePerSeat sets the "price_per_seat" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillablePricePerSeat(v *float64) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetPricePerSeat(*v)
	}
	return _u
}

// AddPricePerSeat adds value to the "price_per_seat" field.
func (_u *GroupBuyPlanUpdateOne) AddPricePerSeat(v float64) *GroupBuyPlanUpdateOne {
	_u.mutation.AddPricePerSeat(v)
	return _u
}

// SetPriceLabel sets the "price_label" field.
func (_u *GroupBuyPlanUpdateOne) SetPriceLabel(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetPriceLabel(v)
	return _u
}

// SetNillablePriceLabel sets the "price_label" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillablePriceLabel(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetPriceLabel(*v)
	}
	return _u
}

// SetQuotaPerShareLabel sets the "quota_per_share_label" field.
func (_u *GroupBuyPlanUpdateOne) SetQuotaPerShareLabel(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetQuotaPerShareLabel(v)
	return _u
}

// SetNillableQuotaPerShareLabel sets the "quota_per_share_label" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableQuotaPerShareLabel(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetQuotaPerShareLabel(*v)
	}
	return _u
}

// SetQuotaLabel sets the "quota_label" field.
func (_u *GroupBuyPlanUpdateOne) SetQuotaLabel(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetQuotaLabel(v)
	return _u
}

// SetNillableQuotaLabel sets the "quota_label" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableQuotaLabel(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetQuotaLabel(*v)
	}
	return _u
}

// SetMaxSharesPerUser sets the "max_shares_per_user" field.
func (_u *GroupBuyPlanUpdateOne) SetMaxSharesPerUser(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetMaxSharesPerUser()
	_u.mutation.SetMaxSharesPerUser(v)
	return _u
}

// SetNillableMaxSharesPerUser sets the "max_shares_per_user" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableMaxSharesPerUser(v *int) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetMaxSharesPerUser(*v)
	}
	return _u
}

// AddMaxSharesPerUser adds value to the "max_shares_per_user" field.
func (_u *GroupBuyPlanUpdateOne) AddMaxSharesPerUser(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.AddMaxSharesPerUser(v)
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *GroupBuyPlanUpdateOne) SetTargetGroupID(v int64) *GroupBuyPlanUpdateOne {
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableTargetGroupID(v *int64) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// SetTierGroupIds sets the "tier_group_ids" field.
func (_u *GroupBuyPlanUpdateOne) SetTierGroupIds(v map[string]int64) *GroupBuyPlanUpdateOne {
	_u.mutation.SetTierGroupIds(v)
	return _u
}

// ClearTierGroupIds clears the value of the "tier_group_ids" field.
func (_u *GroupBuyPlanUpdateOne) ClearTierGroupIds() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearTierGroupIds()
	return _u
}

// SetTierRules sets the "tier_rules" field.
func (_u *GroupBuyPlanUpdateOne) SetTierRules(v []domain.GroupBuyTierRule) *GroupBuyPlanUpdateOne {
	_u.mutation.SetTierRules(v)
	return _u
}

// AppendTierRules appends value to the "tier_rules" field.
func (_u *GroupBuyPlanUpdateOne) AppendTierRules(v []domain.GroupBuyTierRule) *GroupBuyPlanUpdateOne {
	_u.mutation.AppendTierRules(v)
	return _u
}

// ClearTierRules clears the value of the "tier_rules" field.
func (_u *GroupBuyPlanUpdateOne) ClearTierRules() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearTierRules()
	return _u
}

// SetValidityDays sets the "validity_days" field.
func (_u *GroupBuyPlanUpdateOne) SetValidityDays(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetValidityDays()
	_u.mutation.SetValidityDays(v)
	return _u
}

// SetNillableValidityDays sets the "validity_days" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableValidityDays(v *int) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetValidityDays(*v)
	}
	return _u
}

// AddValidityDays adds value to the "validity_days" field.
func (_u *GroupBuyPlanUpdateOne) AddValidityDays(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.AddValidityDays(v)
	return _u
}

// SetTimeoutMinutes sets the "timeout_minutes" field.
func (_u *GroupBuyPlanUpdateOne) SetTimeoutMinutes(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetTimeoutMinutes()
	_u.mutation.SetTimeoutMinutes(v)
	return _u
}

// SetNillableTimeoutMinutes sets the "timeout_minutes" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableTimeoutMinutes(v *int) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetTimeoutMinutes(*v)
	}
	return _u
}

// AddTimeoutMinutes adds value to the "timeout_minutes" field.
func (_u *GroupBuyPlanUpdateOne) AddTimeoutMinutes(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.AddTimeoutMinutes(v)
	return _u
}

// SetLaunchMode sets the "launch_mode" field.
func (_u *GroupBuyPlanUpdateOne) SetLaunchMode(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetLaunchMode(v)
	return _u
}

// SetNillableLaunchMode sets the "launch_mode" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableLaunchMode(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetLaunchMode(*v)
	}
	return _u
}

// SetRefundMode sets the "refund_mode" field.
func (_u *GroupBuyPlanUpdateOne) SetRefundMode(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetRefundMode(v)
	return _u
}

// SetNillableRefundMode sets the "refund_mode" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableRefundMode(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetRefundMode(*v)
	}
	return _u
}

// SetAgreementText sets the "agreement_text" field.
func (_u *GroupBuyPlanUpdateOne) SetAgreementText(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetAgreementText(v)
	return _u
}

// SetNillableAgreementText sets the "agreement_text" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableAgreementText(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetAgreementText(*v)
	}
	return _u
}

// ClearAgreementText clears the value of the "agreement_text" field.
func (_u *GroupBuyPlanUpdateOne) ClearAgreementText() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearAgreementText()
	return _u
}

// SetStatus sets the "status" field.
func (_u *GroupBuyPlanUpdateOne) SetStatus(v string) *GroupBuyPlanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableStatus(v *string) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *GroupBuyPlanUpdateOne) SetSortOrder(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableSortOrder(v *int) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *GroupBuyPlanUpdateOne) AddSortOrder(v int) *GroupBuyPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetLastRoundCreatedAt sets the "last_round_created_at" field.
func (_u *GroupBuyPlanUpdateOne) SetLastRoundCreatedAt(v time.Time) *GroupBuyPlanUpdateOne {
	_u.mutation.SetLastRoundCreatedAt(v)
	return _u
}

// SetNillableLastRoundCreatedAt sets the "last_round_created_at" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableLastRoundCreatedAt(v *time.Time) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetLastRoundCreatedAt(*v)
	}
	return _u
}

// ClearLastRoundCreatedAt clears the value of the "last_round_created_at" field.
func (_u *GroupBuyPlanUpdateOne) ClearLastRoundCreatedAt() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearLastRoundCreatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *GroupBuyPlanUpdateOne) SetDeletedAt(v time.Time) *GroupBuyPlanUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *GroupBuyPlanUpdateOne) SetNillableDeletedAt(v *time.Time) *GroupBuyPlanUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *GroupBuyPlanUpdateOne) ClearDeletedAt() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_u *GroupBuyPlanUpdateOne) SetTargetGroup(v *Group) *GroupBuyPlanUpdateOne {
	return _u.SetTargetGroupID(v.ID)
}

// AddRoundIDs adds the "rounds" edge to the GroupBuyRound entity by IDs.
func (_u *GroupBuyPlanUpdateOne) AddRoundIDs(ids ...int64) *GroupBuyPlanUpdateOne {
	_u.mutation.AddRoundIDs(ids...)
	return _u
}

// AddRounds adds the "rounds" edges to the GroupBuyRound entity.
func (_u *GroupBuyPlanUpdateOne) AddRounds(v ...*GroupBuyRound) *GroupBuyPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRoundIDs(ids...)
}

// AddSeatIDs adds the "seats" edge to the GroupBuySeat entity by IDs.
func (_u *GroupBuyPlanUpdateOne) AddSeatIDs(ids ...int64) *GroupBuyPlanUpdateOne {
	_u.mutation.AddSeatIDs(ids...)
	return _u
}

// AddSeats adds the "seats" edges to the GroupBuySeat entity.
func (_u *GroupBuyPlanUpdateOne) AddSeats(v ...*GroupBuySeat) *GroupBuyPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSeatIDs(ids...)
}

// AddEventIDs adds the "events" edge to the GroupBuyEvent entity by IDs.
func (_u *GroupBuyPlanUpdateOne) AddEventIDs(ids ...int64) *GroupBuyPlanUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the GroupBuyEvent entity.
func (_u *GroupBuyPlanUpdateOne) AddEvents(v ...*GroupBuyEvent) *GroupBuyPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// Mutation returns the GroupBuyPlanMutation object of the builder.
func (_u *GroupBuyPlanUpdateOne) Mutation() *GroupBuyPlanMutation {
	return _u.mutation
}

// ClearTargetGroup clears the "target_group" edge to the Group entity.
func (_u *GroupBuyPlanUpdateOne) ClearTargetGroup() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearTargetGroup()
	return _u
}

// ClearRounds clears all "rounds" edges to the GroupBuyRound entity.
func (_u *GroupBuyPlanUpdateOne) ClearRounds() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearRounds()
	return _u
}

// RemoveRoundIDs removes the "rounds" edge to GroupBuyRound entities by IDs.
func (_u *GroupBuyPlanUpdateOne) RemoveRoundIDs(ids ...int64) *GroupBuyPlanUpdateOne {
	_u.mutation.RemoveRoundIDs(ids...)
	return _u
}

// RemoveRounds removes "rounds" edges to GroupBuyRound entities.
func (_u *GroupBuyPlanUpdateOne) RemoveRounds(v ...*GroupBuyRound) *GroupBuyPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRoundIDs(ids...)
}

// ClearSeats clears all "seats" edges to the GroupBuySeat entity.
func (_u *GroupBuyPlanUpdateOne) ClearSeats() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearSeats()
	return _u
}

// RemoveSeatIDs removes the "seats" edge to GroupBuySeat entities by IDs.
func (_u *GroupBuyPlanUpdateOne) RemoveSeatIDs(ids ...int64) *GroupBuyPlanUpdateOne {
	_u.mutation.RemoveSeatIDs(ids...)
	return _u
}

// RemoveSeats removes "seats" edges to GroupBuySeat entities.
func (_u *GroupBuyPlanUpdateOne) RemoveSeats(v ...*GroupBuySeat) *GroupBuyPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSeatIDs(ids...)
}

// ClearEvents clears all "events" edges to the GroupBuyEvent entity.
func (_u *GroupBuyPlanUpdateOne) ClearEvents() *GroupBuyPlanUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to GroupBuyEvent entities by IDs.
func (_u *GroupBuyPlanUpdateOne) RemoveEventIDs(ids ...int64) *GroupBuyPlanUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to GroupBuyEvent entities.
func (_u *GroupBuyPlanUpdateOne) RemoveEvents(v ...*GroupBuyEvent) *GroupBuyPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the GroupBuyPlanUpdate builder.
func (_u *GroupBuyPlanUpdateOne) Where(ps ...predicate.GroupBuyPlan) *GroupBuyPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GroupBuyPlanUpdateOne) Select(field string, fields ...string) *GroupBuyPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GroupBuyPlan entity.
func (_u *GroupBuyPlanUpdateOne) Save(ctx context.Context) (*GroupBuyPlan, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GroupBuyPlanUpdateOne) SaveX(ctx context.Context) *GroupBuyPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GroupBuyPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GroupBuyPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *GroupBuyPlanUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := groupbuyplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GroupBuyPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := groupbuyplan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProductKey(); ok {
		if err := groupbuyplan.ProductKeyValidator(v); err != nil {
			return &ValidationError{Name: "product_key", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.product_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TotalShares(); ok {
		if err := groupbuyplan.TotalSharesValidator(v); err != nil {
			return &ValidationError{Name: "total_shares", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.total_shares": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SeatCount(); ok {
		if err := groupbuyplan.SeatCountValidator(v); err != nil {
			return &ValidationError{Name: "seat_count", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.seat_count": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PriceLabel(); ok {
		if err := groupbuyplan.PriceLabelValidator(v); err != nil {
			return &ValidationError{Name: "price_label", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.price_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaPerShareLabel(); ok {
		if err := groupbuyplan.QuotaPerShareLabelValidator(v); err != nil {
			return &ValidationError{Name: "quota_per_share_label", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.quota_per_share_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.QuotaLabel(); ok {
		if err := groupbuyplan.QuotaLabelValidator(v); err != nil {
			return &ValidationError{Name: "quota_label", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.quota_label": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LaunchMode(); ok {
		if err := groupbuyplan.LaunchModeValidator(v); err != nil {
			return &ValidationError{Name: "launch_mode", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.launch_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundMode(); ok {
		if err := groupbuyplan.RefundModeValidator(v); err != nil {
			return &ValidationError{Name: "refund_mode", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.refund_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := groupbuyplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "GroupBuyPlan.status": %w`, err)}
		}
	}
	if _u.mutation.TargetGroupCleared() && len(_u.mutation.TargetGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GroupBuyPlan.target_group"`)
	}
	return nil
}

func (_u *GroupBuyPlanUpdateOne) sqlSave(ctx context.Context) (_node *GroupBuyPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(groupbuyplan.Table, groupbuyplan.Columns, sqlgraph.NewFieldSpec(groupbuyplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GroupBuyPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, groupbuyplan.FieldID)
		for _, f := range fields {
			if !groupbuyplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != groupbuyplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(groupbuyplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(groupbuyplan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(groupbuyplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(groupbuyplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ProductKey(); ok {
		_spec.SetField(groupbuyplan.FieldProductKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalShares(); ok {
		_spec.SetField(groupbuyplan.FieldTotalShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalShares(); ok {
		_spec.AddField(groupbuyplan.FieldTotalShares, field.TypeInt, value)
	}
	if value, ok := _u.mutation.SeatCount(); ok {
		_spec.SetField(groupbuyplan.FieldSeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSeatCount(); ok {
		_spec.AddField(groupbuyplan.FieldSeatCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PricePerShare(); ok {
		_spec.SetField(groupbuyplan.FieldPricePerShare, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerShare(); ok {
		_spec.AddField(groupbuyplan.FieldPricePerShare, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PricePerSeat(); ok {
		_spec.SetField(groupbuyplan.FieldPricePerSeat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPricePerSeat(); ok {
		_spec.AddField(groupbuyplan.FieldPricePerSeat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.PriceLabel(); ok {
		_spec.SetField(groupbuyplan.FieldPriceLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaPerShareLabel(); ok {
		_spec.SetField(groupbuyplan.FieldQuotaPerShareLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.QuotaLabel(); ok {
		_spec.SetField(groupbuyplan.FieldQuotaLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxSharesPerUser(); ok {
		_spec.SetField(groupbuyplan.FieldMaxSharesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxSharesPerUser(); ok {
		_spec.AddField(groupbuyplan.FieldMaxSharesPerUser, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TierGroupIds(); ok {
		_spec.SetField(groupbuyplan.FieldTierGroupIds, field.TypeJSON, value)
	}
	if _u.mutation.TierGroupIdsCleared() {
		_spec.ClearField(groupbuyplan.FieldTierGroupIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.TierRules(); ok {
		_spec.SetField(groupbuyplan.FieldTierRules, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedTierRules(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, groupbuyplan.FieldTierRules, value)
		})
	}
	if _u.mutation.TierRulesCleared() {
		_spec.ClearField(groupbuyplan.FieldTierRules, field.TypeJSON)
	}
	if value, ok := _u.mutation.ValidityDays(); ok {
		_spec.SetField(groupbuyplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedValidityDays(); ok {
		_spec.AddField(groupbuyplan.FieldValidityDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TimeoutMinutes(); ok {
		_spec.SetField(groupbuyplan.FieldTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTimeoutMinutes(); ok {
		_spec.AddField(groupbuyplan.FieldTimeoutMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LaunchMode(); ok {
		_spec.SetField(groupbuyplan.FieldLaunchMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RefundMode(); ok {
		_spec.SetField(groupbuyplan.FieldRefundMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgreementText(); ok {
		_spec.SetField(groupbuyplan.FieldAgreementText, field.TypeString, value)
	}
	if _u.mutation.AgreementTextCleared() {
		_spec.ClearField(groupbuyplan.FieldAgreementText, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(groupbuyplan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(groupbuyplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(groupbuyplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastRoundCreatedAt(); ok {
		_spec.SetField(groupbuyplan.FieldLastRoundCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRoundCreatedAtCleared() {
		_spec.ClearField(groupbuyplan.FieldLastRoundCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(groupbuyplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(groupbuyplan.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.TargetGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupbuyplan.TargetGroupTable,
			Columns: []string{groupbuyplan.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   groupbuyplan.TargetGroupTable,
			Columns: []string{groupbuyplan.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.RoundsTable,
			Columns: []string{groupbuyplan.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyround.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoundsIDs(); len(nodes) > 0 && !_u.mutation.RoundsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.RoundsTable,
			Columns: []string{groupbuyplan.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyround.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoundsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.RoundsTable,
			Columns: []string{groupbuyplan.RoundsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyround.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.SeatsTable,
			Columns: []string{groupbuyplan.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSeatsIDs(); len(nodes) > 0 && !_u.mutation.SeatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.SeatsTable,
			Columns: []string{groupbuyplan.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SeatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.SeatsTable,
			Columns: []string{groupbuyplan.SeatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyseat.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.EventsTable,
			Columns: []string{groupbuyplan.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyevent.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.EventsTable,
			Columns: []string{groupbuyplan.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   groupbuyplan.EventsTable,
			Columns: []string{groupbuyplan.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(groupbuyevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GroupBuyPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{groupbuyplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
