// Code generated by ent, DO NOT EDIT.

package caferoundmembership

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldID, id))
}

// RoundID applies equality check predicate on the "round_id" field. It's identical to RoundIDEQ.
func RoundID(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldRoundID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldUserID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldStatus, v))
}

// PaidShares applies equality check predicate on the "paid_shares" field. It's identical to PaidSharesEQ.
func PaidShares(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldPaidShares, v))
}

// ReservedShares applies equality check predicate on the "reserved_shares" field. It's identical to ReservedSharesEQ.
func ReservedShares(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldReservedShares, v))
}

// BoundAPIKeyID applies equality check predicate on the "bound_api_key_id" field. It's identical to BoundAPIKeyIDEQ.
func BoundAPIKeyID(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldBoundAPIKeyID, v))
}

// ActivatedAt applies equality check predicate on the "activated_at" field. It's identical to ActivatedAtEQ.
func ActivatedAt(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldActivatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// RoundIDEQ applies the EQ predicate on the "round_id" field.
func RoundIDEQ(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldRoundID, v))
}

// RoundIDNEQ applies the NEQ predicate on the "round_id" field.
func RoundIDNEQ(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldRoundID, v))
}

// RoundIDIn applies the In predicate on the "round_id" field.
func RoundIDIn(vs ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldRoundID, vs...))
}

// RoundIDNotIn applies the NotIn predicate on the "round_id" field.
func RoundIDNotIn(vs ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldRoundID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldUserID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldContainsFold(FieldStatus, v))
}

// PaidSharesEQ applies the EQ predicate on the "paid_shares" field.
func PaidSharesEQ(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldPaidShares, v))
}

// PaidSharesNEQ applies the NEQ predicate on the "paid_shares" field.
func PaidSharesNEQ(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldPaidShares, v))
}

// PaidSharesIn applies the In predicate on the "paid_shares" field.
func PaidSharesIn(vs ...int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldPaidShares, vs...))
}

// PaidSharesNotIn applies the NotIn predicate on the "paid_shares" field.
func PaidSharesNotIn(vs ...int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldPaidShares, vs...))
}

// PaidSharesGT applies the GT predicate on the "paid_shares" field.
func PaidSharesGT(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldPaidShares, v))
}

// PaidSharesGTE applies the GTE predicate on the "paid_shares" field.
func PaidSharesGTE(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldPaidShares, v))
}

// PaidSharesLT applies the LT predicate on the "paid_shares" field.
func PaidSharesLT(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldPaidShares, v))
}

// PaidSharesLTE applies the LTE predicate on the "paid_shares" field.
func PaidSharesLTE(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldPaidShares, v))
}

// ReservedSharesEQ applies the EQ predicate on the "reserved_shares" field.
func ReservedSharesEQ(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldReservedShares, v))
}

// ReservedSharesNEQ applies the NEQ predicate on the "reserved_shares" field.
func ReservedSharesNEQ(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldReservedShares, v))
}

// ReservedSharesIn applies the In predicate on the "reserved_shares" field.
func ReservedSharesIn(vs ...int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldReservedShares, vs...))
}

// ReservedSharesNotIn applies the NotIn predicate on the "reserved_shares" field.
func ReservedSharesNotIn(vs ...int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldReservedShares, vs...))
}

// ReservedSharesGT applies the GT predicate on the "reserved_shares" field.
func ReservedSharesGT(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldReservedShares, v))
}

// ReservedSharesGTE applies the GTE predicate on the "reserved_shares" field.
func ReservedSharesGTE(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldReservedShares, v))
}

// ReservedSharesLT applies the LT predicate on the "reserved_shares" field.
func ReservedSharesLT(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldReservedShares, v))
}

// ReservedSharesLTE applies the LTE predicate on the "reserved_shares" field.
func ReservedSharesLTE(v int) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldReservedShares, v))
}

// BoundAPIKeyIDEQ applies the EQ predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDEQ(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldBoundAPIKeyID, v))
}

// BoundAPIKeyIDNEQ applies the NEQ predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDNEQ(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldBoundAPIKeyID, v))
}

// BoundAPIKeyIDIn applies the In predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDIn(vs ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldBoundAPIKeyID, vs...))
}

// BoundAPIKeyIDNotIn applies the NotIn predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDNotIn(vs ...int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldBoundAPIKeyID, vs...))
}

// BoundAPIKeyIDGT applies the GT predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDGT(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldBoundAPIKeyID, v))
}

// BoundAPIKeyIDGTE applies the GTE predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDGTE(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldBoundAPIKeyID, v))
}

// BoundAPIKeyIDLT applies the LT predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDLT(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldBoundAPIKeyID, v))
}

// BoundAPIKeyIDLTE applies the LTE predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDLTE(v int64) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldBoundAPIKeyID, v))
}

// BoundAPIKeyIDIsNil applies the IsNil predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDIsNil() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIsNull(FieldBoundAPIKeyID))
}

// BoundAPIKeyIDNotNil applies the NotNil predicate on the "bound_api_key_id" field.
func BoundAPIKeyIDNotNil() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotNull(FieldBoundAPIKeyID))
}

// ActivatedAtEQ applies the EQ predicate on the "activated_at" field.
func ActivatedAtEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldActivatedAt, v))
}

// ActivatedAtNEQ applies the NEQ predicate on the "activated_at" field.
func ActivatedAtNEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldActivatedAt, v))
}

// ActivatedAtIn applies the In predicate on the "activated_at" field.
func ActivatedAtIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldActivatedAt, vs...))
}

// ActivatedAtNotIn applies the NotIn predicate on the "activated_at" field.
func ActivatedAtNotIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldActivatedAt, vs...))
}

// ActivatedAtGT applies the GT predicate on the "activated_at" field.
func ActivatedAtGT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldActivatedAt, v))
}

// ActivatedAtGTE applies the GTE predicate on the "activated_at" field.
func ActivatedAtGTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldActivatedAt, v))
}

// ActivatedAtLT applies the LT predicate on the "activated_at" field.
func ActivatedAtLT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldActivatedAt, v))
}

// ActivatedAtLTE applies the LTE predicate on the "activated_at" field.
func ActivatedAtLTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldActivatedAt, v))
}

// ActivatedAtIsNil applies the IsNil predicate on the "activated_at" field.
func ActivatedAtIsNil() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIsNull(FieldActivatedAt))
}

// ActivatedAtNotNil applies the NotNil predicate on the "activated_at" field.
func ActivatedAtNotNil() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotNull(FieldActivatedAt))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotNull(FieldExpiresAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasRound applies the HasEdge predicate on the "round" edge.
func HasRound() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoundTable, RoundColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoundWith applies the HasEdge predicate on the "round" edge with a given conditions (other predicates).
func HasRoundWith(preds ...predicate.GroupBuyRound) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(func(s *sql.Selector) {
		step := newRoundStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPaymentBatches applies the HasEdge predicate on the "payment_batches" edge.
func HasPaymentBatches() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentBatchesTable, PaymentBatchesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentBatchesWith applies the HasEdge predicate on the "payment_batches" edge with a given conditions (other predicates).
func HasPaymentBatchesWith(preds ...predicate.GroupBuySeat) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(func(s *sql.Selector) {
		step := newPaymentBatchesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccountBindings applies the HasEdge predicate on the "account_bindings" edge.
func HasAccountBindings() predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountBindingsTable, AccountBindingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountBindingsWith applies the HasEdge predicate on the "account_bindings" edge with a given conditions (other predicates).
func HasAccountBindingsWith(preds ...predicate.APIKeyAccountBinding) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(func(s *sql.Selector) {
		step := newAccountBindingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CafeRoundMembership) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CafeRoundMembership) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CafeRoundMembership) predicate.CafeRoundMembership {
	return predicate.CafeRoundMembership(sql.NotPredicates(p))
}
