// Code generated by ent, DO NOT EDIT.

package groupbuyevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLTE(FieldID, id))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldPlanID, v))
}

// RoundID applies equality check predicate on the "round_id" field. It's identical to RoundIDEQ.
func RoundID(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldRoundID, v))
}

// SeatID applies equality check predicate on the "seat_id" field. It's identical to SeatIDEQ.
func SeatID(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldSeatID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldUserID, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldEventType, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotNull(FieldPlanID))
}

// RoundIDEQ applies the EQ predicate on the "round_id" field.
func RoundIDEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldRoundID, v))
}

// RoundIDNEQ applies the NEQ predicate on the "round_id" field.
func RoundIDNEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldRoundID, v))
}

// RoundIDIn applies the In predicate on the "round_id" field.
func RoundIDIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldRoundID, vs...))
}

// RoundIDNotIn applies the NotIn predicate on the "round_id" field.
func RoundIDNotIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldRoundID, vs...))
}

// RoundIDIsNil applies the IsNil predicate on the "round_id" field.
func RoundIDIsNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIsNull(FieldRoundID))
}

// RoundIDNotNil applies the NotNil predicate on the "round_id" field.
func RoundIDNotNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotNull(FieldRoundID))
}

// SeatIDEQ applies the EQ predicate on the "seat_id" field.
func SeatIDEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldSeatID, v))
}

// SeatIDNEQ applies the NEQ predicate on the "seat_id" field.
func SeatIDNEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldSeatID, v))
}

// SeatIDIn applies the In predicate on the "seat_id" field.
func SeatIDIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldSeatID, vs...))
}

// SeatIDNotIn applies the NotIn predicate on the "seat_id" field.
func SeatIDNotIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldSeatID, vs...))
}

// SeatIDIsNil applies the IsNil predicate on the "seat_id" field.
func SeatIDIsNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIsNull(FieldSeatID))
}

// SeatIDNotNil applies the NotNil predicate on the "seat_id" field.
func SeatIDNotNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotNull(FieldSeatID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotNull(FieldUserID))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldContainsFold(FieldEventType, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldContainsFold(FieldMessage, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.GroupBuyPlan) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRound applies the HasEdge predicate on the "round" edge.
func HasRound() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RoundTable, RoundColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoundWith applies the HasEdge predicate on the "round" edge with a given conditions (other predicates).
func HasRoundWith(preds ...predicate.GroupBuyRound) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := newRoundStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSeat applies the HasEdge predicate on the "seat" edge.
func HasSeat() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SeatTable, SeatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeatWith applies the HasEdge predicate on the "seat" edge with a given conditions (other predicates).
func HasSeatWith(preds ...predicate.GroupBuySeat) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := newSeatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupBuyEvent) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupBuyEvent) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupBuyEvent) predicate.GroupBuyEvent {
	return predicate.GroupBuyEvent(sql.NotPredicates(p))
}
